### ISSUE TITLE
navigation tree wrong

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#100]
This is a

* [x] bug
* [ ] enhancement

If possible please provide the exact versions of the bundles involved.
spryker/application                         2.6.3

### What you did
Adding part to navigation.xml

```
    <product>
        <label>Products</label>
        <title>Products</title>
        <bundle>product</bundle>
        <controller>index</controller>
        <action>index</action>
        <icon>fa-database</icon>
    </product>
```

### Actual Behavior
Navigation tree has a non-clickable entry Products and a sub-entry Availability

### Expected Behavior
A clickable navigation entry Products with url /product

**Comment by dereuromark** [comment]
What bundles are you on for Product etc?
Are you on the latest release there?

**Comment by AndromedaXP** [comment]
spryker/product                             3.0.2

**Comment by AndromedaXP** [comment]
When using
spryker/product                             4.1.0
we have 2 subentries:
- Availability
-  Product Options
but still no Products

**Comment by AndromedaXP** [comment]
are u still investigating?

**Comment by tvaleriy** [comment]
Sorry, I will give you an answer at the beginning of next week about the decision.

**Comment by tvaleriy** [comment]
We can confirm this issue.
I will inform when it will be fixed.

**Comment by dereuromark** [comment]
This is released with https://github.com/spryker/ZedNavigation/releases/tag/1.0.2
