### ISSUE TITLE
Search query completion is not working

### ISSUE THREAD

**Issue by mruoss** [spryker/support#101]
This is a

* [ ] bug

### What you did

I have the term "searchstring" in the field "completion-terms" in our es index.
I am visiting `/search/suggestion?q=searchstri`

### Actual Behavior

I get no suggestions for term completion.

### Expected Behavior

I get "searchstring" as a term completion suggestion.

### Supposition for bugfix

I might be wrong, but in my eyes, the function [`CompletionQueryExpanderPlugin::addAggregation()`](https://github.com/spryker/Search/blob/master/src/Spryker/Client/Search/Plugin/Elasticsearch/QueryExpander/CompletionQueryExpanderPlugin.php#L74) should create a global aggregation and assign the `$termsAggregation` to it. That way, the completion-terms are searched over the whole index, not only the search results (as the result I'm looking for might not be in the result set for `q=searchstri`). 

You might want to use a different name for the global aggregation but to demonstrate what I mean, here is the adapted function. The `CompletionResultFormatterPlugin` would have to be adapted as well of course. Does this make sense to you?

```php
    /**
     * @param \Elastica\Query $query
     * @param string $searchString
     *
     * @return void
     */
    protected function addAggregation(Query $query, $searchString)
    {
        $termsAggregation = $this->getFactory()
            ->createAggregationBuilder()
            ->createTermsAggregation(static::AGGREGATION_NAME)
            ->setField(PageIndexMap::COMPLETION_TERMS)
            ->setSize(static::SIZE)
            ->setInclude($this->getRegexpQueryString($searchString));

        $globalAggregation = $this->getFactory()->createAggregationBuilder()
            ->createGlobalAggregation(static::AGGREGATION_NAME)
            ->addAggregation($termsAggregation);

        $query->addAggregation($globalAggregation);
    }
```

**Comment by tamasnyulas** [comment]
Hi @mruoss,

The original idea was to provide autocompletion for the matched documents. In our demoshop this works fine, but you'll have to change the analyzer on the full-text search fields as documented here: http://spryker.github.io/core/bundles/search/#autocompletion

Let me know if this solves your problem.

**Comment by mruoss** [comment]
Oh yeah, I should have read the documentation first, I guess. This works like a charm, thank you very much!
