### ISSUE TITLE
Shipment table runs in error

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#102]
This is a

* [x] bug
* [ ] enhancement

If possible please provide the exact versions of the bundles involved.
spryker/money                               1.1.0
spryker/shipment                            3.1.2

### What you did
Call url /shipment

### Actual Behavior
table with shipments does not show because of
```Spryker\Shared\Money\Exception\InvalidAmountArgumentException - Current amount was expected to be int. Current type is "NULL"```
This is because we have null values for default_price in spy_shipment_method table (which is allowed from propel schema.

### Expected Behavior
table should be shown correct

**Comment by dereuromark** [comment]
We were able to reproduce this in both table and form and will provide a patch here shortly.
Thank you for reporting this.

**Comment by dereuromark** [comment]
This is fixed with https://github.com/spryker/Shipment/releases/tag/3.1.4
