### ISSUE TITLE
Changing redirect adds another redirect

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#104]
This is a

* [x] bug
* [ ] enhancement

If possible please provide the exact versions of the bundles involved.
spryker/cms                                 3.1.0 
spryker/url                                 2.2.0 

### What you did
Editing a redirect by changing the from url

### Actual Behavior
The UrlUpdateObserver creates an additional redirect with the overwritten from url.
This could be understood as an additional feature which is not needed from us and runs in our project into problems.

### Expected Behavior
Edit just the existing redirect.

**Comment by tamasnyulas** [comment]
Hi @AndromedaXP,

This feature was intended. It makes possible to not to have any dead URLs even if they were redirects before.

Could you tell us more about what problems you are facing with this feature?

**Comment by AndromedaXP** [comment]
@tamasnyulas 

We added additional rows in spy_url which are empty then. But anyways, we still don't need this feature. If we have another url, then we add a second redirect.
What if I just correct a wrong url? Then this feature is totally wrong.

**Comment by tamasnyulas** [comment]
We have a plan of building a feature where on editing urls the user would need to confirm automatic redirects by ticking a checkbox. Would this help you to solve your problem?

Alternatively you can disable the `\Spryker\Zed\Url\Business\Redirect\Observer\UrlUpdateObserver` by not attaching it to the URL updater by overriding `\Spryker\Zed\Url\Business\UrlBusinessFactory::createUrlUpdaterAfterSaveObservers()`. This will however turn off automatic redirects for every URL change (cms page, product, category), not only URL redirects.

**Comment by AndromedaXP** [comment]
ok, thanks for the quick fix. Then I must turn it off everywhere, a checkbox would be still nice.
