### ISSUE TITLE
Upgrade to Codeception 2.2.x

### ISSUE THREAD

**Issue by bazoo0815** [spryker/support#105]
This is a

* [ ] bug
* [x] enhancement

I wanted to upgrade Codeception to any 2.2.x version to benefit from the new features and improvements.
But the dependency in spryker/testify (at least) does not allow this upgrade:
```
  "require": {
    "codeception/codeception": "~2.1.5",
```
Could you upgrade to Codeception 2.2.x on core level to allow using that version on project level as well?
That would be great.

Best,
Bernd

**Comment by tvaleriy** [comment]
@bazoo0815 https://github.com/spryker/Testify/compare/3.0.2...3.1.0

**Comment by dereuromark** [comment]
The core is now compatible with 2.2.11+ ( https://github.com/spryker/demoshop/blob/master/composer.json#L144 ).
