### ISSUE TITLE
vendor/bin/console cache:delete-all throws ErrorException if cache directory is already deleted

### ISSUE THREAD

**Issue by mirsch** [spryker/support#106]
This is a

* [x] bug
* [ ] enhancement

exact versions:

spryker/cache 2.1.1
this seems to be fixed in 3.0.0 (https://github.com/spryker/Cache/compare/2.1.1...3.0.0#diff-e78dec8fd82f88bed3434145b51b9032R41) but we are still on 2.x

### What you did
vendor/bin/console cache:delete-all

### Actual Behavior
ErrorException - Exception: unlink(<path>/cache): No such file or directory 

### Expected Behavior
no error if cache directory is already deleted

**Comment by dereuromark** [comment]
There are patches now for https://github.com/spryker/Cache/releases/tag/3.1.0 to empty instead of deleting a folder.
The commands also changed, we will soon release more info on this one.

**Comment by mirsch** [comment]
No bugfix for 2.x?
