### ISSUE TITLE
Documentation failure in 'Transfer Data from Yves to Zed' section

### ISSUE THREAD

**Issue by vmigel** [spryker/support#107]
This is a

* [x] bug
* [ ] enhancement

For questions please consult the [Spryker Forum](http://discuss.spryker.com/).

If possible please provide the exact versions of the bundles involved.

### What you did
I went through Onboarding section 'b) Building a HelloSpryker bundle in Yves'. There is so meager information so I moved to section ['Transfer Data from Yves to Zed'](http://spryker.github.io/tutorials/yves/communication-yves-zed/#transfer-data-from-yves-to-zed). And I found couple issues in section ['Implement the stub'](http://spryker.github.io/tutorials/yves/communication-yves-zed/#implement-the-stub)

### Actual Behavior
1) Using wrong class in HelloWorldStub class
```
use Spryker\Client\ZedRequest\Stub\BaseStub;

class HelloWorldStub extends BaseStub
```

2) use undefined method 'getZedRequestClient()' in class HelloWorldFactory

3) Absent class with 'HelloWorldDependencyProvider'

### Expected Behavior
1) should be 
```
use Spryker\Client\ZedRequest\Stub\ZedRequestStub;

class HelloWorldStub extends ZedRequestStub
```

2) This method should be define in this HelloWorldFactory class:
```
/**
     * @return \Spryker\Client\ZedRequest\ZedRequestClientInterface
     */
    protected function getZedRequestClient()
    {
        return $this->getProvidedDependency(HelloSprykerDependencyProvider::CLIENT_ZED_REQUEST);
    }
```

3) Should have class 'HelloWorldDependencyProvider'
```
<?php

/**
 * Copyright © 2016-present Spryker Systems GmbH. All rights reserved.
 * Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 */

namespace Pyz\Client\HelloWorld;

use Spryker\Client\Kernel\AbstractDependencyProvider;
use Spryker\Client\Kernel\Container;

class HelloWorldDependencyProvider extends AbstractDependencyProvider
{

    const CLIENT_ZED_REQUEST = 'HelloWorld client';

    /**
     * @param \Spryker\Client\Kernel\Container $container
     *
     * @return \Spryker\Client\Kernel\Container
     */
    public function provideServiceLayerDependencies(Container $container)
    {
        $container = $this->addZedRequestClient($container);

        return $container;
    }

    /**
     * @param \Spryker\Client\Kernel\Container $container
     *
     * @return \Spryker\Client\Kernel\Container
     */
    protected function addZedRequestClient(Container $container)
    {
        $container[static::CLIENT_ZED_REQUEST] = function (Container $container) {
            return $container->getLocator()->zedRequest()->client();
        };

        return $container;
    }

}
```

**Comment by debbiedocs** [comment]
Hi, 

Thank you for your feedback. 
We have taken your feedback into consideration and updated the documentation accordingly. 
Please feel free to keep on suggesting improvements.

Regards,

The Academy Team

**Comment by tvaleriy** [comment]
Test comment.
