### ISSUE TITLE
[DemoShop] Product imageSets for different locales do not appear correctly in the PDPs under the defined locales.

### ISSUE THREAD

**Issue by philipposkard** [spryker/support#109]
The problem apparently lies in the ProductAbstractCollector and ProductConcreteCollector localized imageSet generation.
The imageSet query in generateProductAbstractImageSets() and generateProductConcreteImageSets() is not being filtered through the current export locale so the wrong images are stored in Redis.

**Comment by tvaleriy** [comment]
Should be fixed with https://github.com/spryker/ProductImage/releases/tag/3.2.0 and https://github.com/spryker/ProductManagement/releases/tag/0.5.0
