### ISSUE TITLE
ProductCategoryQueryContainer doesn't match Interface

### ISSUE THREAD

**Issue by NilsEvers** [spryker/support#112]
This is a

* [x] bug
* [ ] enhancement

`\Spryker\Zed\ProductCategory\Persistence\ProductCategoryQueryContainer` does not match its interface.

The parameters of the method`queryProductCategoryMappingByIds` are switched and named differently, compared to the interface.

```
// Signature of interface
public function queryProductCategoryMappingByIds($idProductAbstract, $idCategoryNode)

// Signature of implementation
public function queryProductCategoryMappingByIds($idCategory, $idProductAbstract)
```

**Comment by dereuromark** [comment]
Released with https://github.com/spryker/ProductCategory/releases/tag/4.1.1
