### ISSUE TITLE
Product Management can not handle arrays in product attributes

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#113]
This is a

* [x] bug
* [ ] enhancement

If possible please provide the exact versions of the bundles involved.
spryker/product-management                  0.3.2 

### What you did
We store also array data in product attributes. It is json anyways, so no reason to use only strings

### Actual Behavior
error on AbstractProductFormDataProvider:510
mb_strlen($value) > 255;
$value is expected to be a string, array given

### Expected Behavior
Product management should also work with arrays as Attribute values for concrete and abstract Products

**Comment by AndromedaXP** [comment]
4month no feedback...

**Comment by ridculy** [comment]
This report is now 8 Month Old

**Comment by NilsEvers** [comment]
I believe this is something you have to tackle yourself. What kind of form-element should handle this kind of data? I don't think there is a general solution for this, it really depends on your data.

If you just want to assign multiple values and don't have a nested Array structure, you could just save it as a String and use some specific character as a separator. For example: "value1; value2; value3". When collecting this field, you just split the string and save it as an Array. This way you still have a good way to edit the field from the backend and your data will also be exported as an Array.

**Comment by AndromedaXP** [comment]
Said that we hear that so often to tackle that by ourself while paying for a framework which should handle that.
The form-element would be the same, just on a second or third level. Doesn't sound so complicated to us to build a gui for that but you seem to respond to other requirements than our business must handle.

**Comment by NilsEvers** [comment]
I am no member of the spryker team, I just offered some help...

And again, I don't think there is a general solution as data can vary per client.

Have a nive day

**Comment by tvaleriy** [comment]
@AndromedaXP @ridculy Sorry for this inconvenience. It is still in our backlog. Should be implement in the nearest future (no specific time frame).

**Comment by tvaleriy** [comment]
I've moved this ticket here - https://spryker.ideas.aha.io/ideas/CUSTIDEAS-I-11. You can track the progress there.
I'm closing this ticket here.
