### ISSUE TITLE
error because of missing fk_product_abstract in spy_price_product 

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#114]
This is a

* [x] bug
* [ ] enhancement

If possible please provide the exact versions of the bundles involved.
spryker/product                             5.1.1
spryker/product-management                  0.3.2

### What you did
Having a Abstract Product will correct taxSet in DB
calling /product-management/view?id-product-abstract=1

### Actual Behavior
ViewController.php:82 calling $this->getFactory()->getTaxFacade()->getTaxSet($productAbstractTransfer->getIdTaxSet())
$productAbstractTransfer->getIdTaxSet() is null because the field in Database is fkTaxSet and will therefore not be matched in ProductTransferMapper

### Expected Behavior
no error

**Comment by aurisl** [comment]
It's set `\Spryker\Zed\TaxProductConnector\Business\Product\ProductAbstractTaxSetMapper::mapTaxSet` by `TaxSetProductAbstractReadPlugin`

**Comment by AndromedaXP** [comment]
Do we have to "activate" this plugin somehow?

**Comment by aurisl** [comment]
Yes, add it to `\Pyz\Zed\Product\ProductDependencyProvider::getProductAbstractReadPlugins` plugin stack.

**Comment by AndromedaXP** [comment]
Thx, do we have to add even more Plugins?
Because now I get...
Impossible to access an attribute ("price") on a null variable in "@ProductManagement/View/_partials/info-price-tax.twig" at line 8

**Comment by aurisl** [comment]
this comes from `\Spryker\Zed\Price\Communication\Plugin\ProductAbstract\PriceProductAbstractReadPlugin` please check our demoshop, so you have all required plugins '\Pyz\Zed\Product\ProductDependencyProvider'

**Comment by AndromedaXP** [comment]
Even when adding PriceProductAbstractReadPlugin I still get the error, because we have no prices in spy_price_product linked to productAbstract but to productConcrete, which is fine with your propel model. But still it should be possible that a product doesn't have any prices without an error.

**Comment by tvaleriy** [comment]
Thank you for pointing it out.
It is in the backlog of feature requests now.

**Comment by the-colorant** [comment]
According to the discussion it sounds like you had a local issue. I will be closing this issue. Please create a new one in case you still have any problems. 

Thanks for you input!
