### ISSUE TITLE
Produktsuche im Backend fehlerhaft

### ISSUE THREAD

**Issue by spryker-twt** [spryker/support#115]
This is a

* [x] bug
* [ ] enhancement

For questions please consult the [Spryker Forum](http://discuss.spryker.com/).

If possible please provide the exact versions of the bundles involved.

### What you did
Bei Eingabe einer Produkt ID in der Suche wird das Produkt nicht angezeigt, obwohl es in der Produktliste angezeigt wird.

### Actual Behavior
In der Suche wird das Produkt nicht angezeigt, obwohl es in der Produktliste angezeigt wird.

### Expected Behavior
Das Produkt mit der jeweiligen ID wird bei Suche angezeigt.

**Comment by tvaleriy** [comment]
I've moved this ticket here - https://spryker.ideas.aha.io/ideas/CUSTIDEAS-I-12. You can track the progress there.
I'm closing this ticket here.
