### ISSUE TITLE
Is the //TRANSLIT feature required?

### ISSUE THREAD

**Issue by twolfy** [spryker/support#116]
Hi,

This is a

* [ ] bug
* [x] enhancement

### What you did

TLTR:
Build docker images for spryker demoshop with alpine linux as their base system.

Long version:
we would prefer Alpine Linux as our container linux distribution (because of size and therefor security), which uses the musl clib. musl clib [does not support](http://wiki.musl-libc.org/wiki/Functional_differences_from_glibc#iconv) ([reason](https://github.com/akrennmair/newsbeuter/issues/364#issuecomment-250208235)) the `//TRANSLIT` feature from glibc, which is in use by [/vendor/spryker/util-text/src/Spryker/Service/UtilText/Model/Slug.php](https://github.com/spryker/UtilText/blob/master/src/Spryker/Service/UtilText/Model/Slug.php#L21).

### Actual Behavior

It does not build without workarounds.

### Expected Behavior

So my question is, do you need the `//TRANSLIT` feature? Or are we able to drop it in favor of an
easy alpine setup?

Kind regards
Tony

**Comment by tvaleriy** [comment]
Hi @twolfy, it should be optional. So you are able to drop it.
