### ISSUE TITLE
Demoshop compose.json repositories are using SSH based git clone

### ISSUE THREAD

**Issue by twolfy** [spryker/support#117]
Hi,

This is a

* [x] bug
* [ ] enhancement

### What you did

the [composer.json](https://github.com/spryker/demoshop/blob/2.12/composer.json#L202) in the demoshop repository uses two additional repositories, specified to communicate via SSH with github. This is problematic for our automated builds as it requires an SSH-key registered at github and our automated build environments are volatile.

### Actual Behavior

Uses git+ssh in composer.json repository reference.

### Expected Behavior

Using https in composer.json repository reference.

Kind regards
Tony

**Comment by dereuromark** [comment]
You are right, we can switch that to https.

**Comment by dereuromark** [comment]
Resolved with https://github.com/spryker/demoshop/commit/1dac5828390647d4fa4153aec7e26f29cba969fc
Thank you for reporting it!
