### ISSUE TITLE
glossary bundle mysql incompatible

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#118]
This is a

* [x] bug
* [ ] enhancement

For questions please consult the [Spryker Forum](http://discuss.spryker.com/).

If possible please provide the exact versions of the bundles involved.
spryker/glossary 3.1.0

### What you did
Calling backend /glossary

### Actual Behavior
error because of https://github.com/spryker/Glossary/commit/76a097a8b02ee611980ccbd510f08d97487cae8c
in TranslationTable.php:135 there u use a PostgreSQL comparison type ILIKE

### Expected Behavior
a mysql friendly framework ;)

**Comment by tvaleriy** [comment]
@AndromedaXP Thank you for your feedback. Should be fixed soon (nearest release or one after).

**Comment by tvaleriy** [comment]
http://spryker.github.io/release/2017/may-2/#glossary-mysql-compatibility
