### ISSUE TITLE
[Demoshop] Product category order has no impact

### ISSUE THREAD

**Issue by NilsEvers** [spryker/support#119]
This is a

* [x] bug
* [ ] enhancement

On Zed, when assigning products to a category, changing the order of the assigned products has no impact on the catalog-pages in Yves.

### What you did
On Zed, I went to `Category` > `Assign products to category` for a given category. Then I changed the values in the `Order` fields for a bunch of assigned products. Then I exported search and navigated to the catalog-page of the category in Yves.

### Actual Behavior
The products are not sorted according to the defined order values.

### Expected Behavior
The products are sorted as defined in Zed.

**Comment by tvaleriy** [comment]
@NilsEvers Thank you for pointing it out. Will be fixed in future.

**Comment by tvaleriy** [comment]
https://github.com/spryker/Search/releases/tag/6.1.0
