### ISSUE TITLE
Bundle spryker/category: re-sort save action is triggered twice

### ISSUE THREAD

**Issue by mruoss** [spryker/support#121]
This is a

* [x] minor bug

When I re-order my category nodes and click on save, the ajax request to save the new order is fired twice. 

The reason: re-sort.js includes re-sort/bootstrap.js. Otherwise both files contain the same code. Therefore the click action is handled twice. See the files:

https://github.com/spryker/Category/blob/master/assets/Zed/js/modules/re-sort.js
https://github.com/spryker/Category/blob/master/assets/Zed/js/modules/re-sort/bootstrap.js

**Comment by dereuromark** [comment]
Resolved with https://github.com/spryker/Category/releases/tag/3.2.3
