### ISSUE TITLE
ShipmentMethod DeliveryTime type inconsistency

### ISSUE THREAD

**Issue by NilsEvers** [spryker/support#122]
As defined via the interface `Spryker\Zed\Shipment\Communication\PluginShipmentMethodDeliveryTimePluginInterface` the method `getTime` returns an integer but `getDeliveryTime` of the model `\Spryker\Zed\Shipment\Business\Model\Method` returns a string.

This inconsistent and kind of confusing.

**Comment by tvaleriy** [comment]
Yes, thank you for your feedback. We will fix this.

**Comment by tvaleriy** [comment]
https://github.com/spryker/Shipment/releases/tag/5.0.2
