### ISSUE TITLE
[Payone] Credit Card state machine is missing a timeout 

### ISSUE THREAD

**Issue by NilsEvers** [spryker/support#123]
The Credit Card state machine from the Payone bundle has no timeout set for "3d secure validation". If a customer, for one or another reason, doesn't come back from the 3d secure redirect, which happens quite often, the order items will stay in this state and flood the `spy_oms_order_item_state_history` table over time.

We just stumbled over this, because we had some order items with a state history of about 100.000 rows...

**Comment by tvaleriy** [comment]
Thank you for reporting this issue. I can confirm it. It is in our backlog now.

**Comment by tvaleriy** [comment]
Hi @NilsEvers . Please update Sales module in your project and this problem should be gone.
https://github.com/spryker/Sales/releases/tag/7.1.3
