### ISSUE TITLE
[Demoshop] search-form is rendered twice

### ISSUE THREAD

**Issue by DSB** [spryker/support#125]
This is a

* [x] bug
* [ ] enhancement

### What you did
Call any page in demoshop.

### Actual Behavior
The search form is included and rendered twice. See https://github.com/spryker/demoshop/blob/master/src/Pyz/Yves/Application/Theme/default/layout/layout.twig#L43
and https://github.com/spryker/demoshop/blob/master/src/Pyz/Yves/Application/Theme/default/layout/partials/navigation.twig#L10

### Expected Behavior
Form should be rendered once.

**Comment by tvaleriy** [comment]
@DSB What is your initial problem? This form included in two different twig-templates for a reason.

**Comment by DSB** [comment]
I added some javascript for testing purposes to this template and saw that it is executed twice. Imho it is not expected behavior to render this template twice. Also I didn't recognize any disavantage when I commented out the second include in navigation.twig. What is the reason to render it twice?

**Comment by tamasnyulas** [comment]
@DSB Our demoshop has responsive design and because of this some elements has to be placed differently for mobile view. If you want, you can remove the search field from mobile view in your project, but we are not planning to change this in the future.
