### ISSUE TITLE
Error when Migrate CmsBlock

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#126]
This is a

* [x] bug
* [ ] enhancement

If possible please provide the exact versions of the bundles involved.
spryker/cms-block                    1.0.2

### What you did
running propel:migrate

### Actual Behavior
table cannot be created because of duplicate key which is defined in spy_cms_block.schema.xml
```
        <unique name="spy_cms_block_glossary_key_mapping-unique-fk_cms_block">
            <unique-column name="fk_cms_block"/>
            <unique-column name="placeholder"/>
        </unique>

        <index name="spy_cms_block_glossary_key_mapping-fk_cms_block">
            <index-column name="fk_cms_block"/>
            <index-column name="placeholder"/>
        </index>
```

### Expected Behavior
no errors

**Comment by tvaleriy** [comment]
Thanks for reporting this. We need to investigate this first.

**Comment by PhilinTv** [comment]
@AndromedaXP do you mean that "spy_cms_block_glossary_key_mapping-fk_cms_block" is already taken by foreign key? Could you please remember what exactly the error message you had from Propel?

**Comment by AndromedaXP** [comment]
`  [Propel\Runtime\Exception\RuntimeException]                                                                 
  <error>Failed to execute SQL "CREATE TABLE `spy_cms_block_glossary_key_mapping`                             
  (                                                                                                           
      `id_cms_block_glossary_key_mapping` INTEGER NOT NULL AUTO_INCREMENT,                                    
      `fk_cms_block` INTEGER NOT NULL,                                                                        
      `fk_glossary_key` INTEGER NOT NULL,                                                                     
      `placeholder` VARCHAR(255) NOT NULL,                                                                    
      PRIMARY KEY (`id_cms_block_glossary_key_mapping`),                                                      
      UNIQUE INDEX `spy_cms_block_glossary_key_mapping-unique-fk_cms_block` (`fk_cms_block`, `placeholder`),  
      INDEX `spy_cms_block_glossary_key_mapping-fk_cms_block` (`fk_cms_block`, `placeholder`),                
      INDEX `spy_cms_glossary_key_mapping-fi_glossary_key` (`fk_glossary_key`),                               
      CONSTRAINT `spy_cms_block_glossary_key_mapping-fk_cms_block`                                            
          FOREIGN KEY (`fk_cms_block`)                                                                        
          REFERENCES `spy_cms_block` (`id_cms_block`)                                                         
          ON DELETE CASCADE,                                                                                  
      CONSTRAINT `spy_cms_glossary_key_mapping-fk_glossary_key`                                               
          FOREIGN KEY (`fk_glossary_key`)                                                                     
          REFERENCES `spy_glossary_key` (`id_glossary_key`)                                                   
          ON DELETE CASCADE                                                                                   
  ) ENGINE=InnoDB". Aborting migration.</error>                                                               
                                                                                                              

                                                                                                                                  
  [PDOException]                                                                                                                  
  SQLSTATE[23000]: Integrity constraint violation: 1022 Can't write; duplicate key in table 'spy_cms_block_glossary_key_mapping' `

**Comment by AndromedaXP** [comment]
Error also occurs when running this command directly on
mysql  Ver 14.14 Distrib 5.6.29, for debian-linux-gnu (x86_64) using  EditLine wrapper

**Comment by tvaleriy** [comment]
Should be fixed with https://github.com/spryker/CmsBlock/releases/tag/1.2.1 .
