### ISSUE TITLE
spy_cms_version INSERT error

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#127]
This is a

* [x] bug
* [ ] enhancement

If possible please provide the exact versions of the bundles involved.
spryker/cms                          6.0.3

### What you did
Publishing a page

### Actual Behavior
SQL error:
"SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'data' at row 1"

`<column name="data" type="LONGVARCHAR"/>` doesn't seems to be enough

### Expected Behavior
no error

**Comment by tvaleriy** [comment]
Thanks for reporting this. Should be fixed in future.

**Comment by PhilinTv** [comment]
@AndromedaXP Could you please provide the actual type of "data' column in your DB? And the length of the data you are trying to save.

"LONGVARCHAR" should be transferred by Propel to TEXT type, and it should be enough for a common CMS page case.

**Comment by AndromedaXP** [comment]
I don't remember which data I wanted to save, just that TEXT didn't seem to be enough.
What do you mean with "common CMS page case"?

**Comment by PhilinTv** [comment]
@AndromedaXP  you are right TEXT in Mysql is not enough for Cms page. Will be fixed to smth real, like mediumtext (up to 16 MB).

**Comment by AndromedaXP** [comment]
great.
when?

**Comment by PhilinTv** [comment]
@AndromedaXP we will notify you when it's planned.

**Comment by AndromedaXP** [comment]
1,5m ago and no feedback on a bug...

**Comment by tvaleriy** [comment]
@AndromedaXP Should be fixed soon.

**Comment by PhilinTv** [comment]
@AndromedaXP it's a 3rd-party vendor issue, that's why it can't be resolved on the module level quickly.
But you always can solve it on the project level by redefining size for 'data' column.

E.g.
src/Pyz/Zed/Cms/Persistence/Propel/Schema/spy_cms.schema.xml
```
<?xml version="1.0"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="zed" xsi:noNamespaceSchemaLocation="http://static.spryker.com/schema-01.xsd" namespace="Orm\Zed\Cms\Persistence" package="src.Orm.Zed.Cms.Persistence">
    <table name="spy_cms_version">
        <column name="data" type="LONGVARCHAR" size="4294967295"/>
    </table>
</database>
```

**Comment by AndromedaXP** [comment]
ok, thanks for that hint.

**Comment by AndromedaXP** [comment]
@PhilinTv 
Problem with this solution is that propel:diff always wants to change the value of "data" to TEXT(4294967295) but in mysql this will result in LONGTEXT.
Why is this a 3rd-party vendor issue when it is declared in spy_cms.schema.xml?
