### ISSUE TITLE
CRUD of Blocks missing

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#128]
This is a

* [x] bug
* [ ] enhancement

If possible please provide the exact versions of the bundles involved.
spryker/cms-block                    1.0.2 
spryker/cms-gui                      4.0.1 

### What you did
Upgrading to your extraction of block into a separate bundle.

### Actual Behavior
Backend Navigation has no Table or Forms of listing or editing Blocks

### Expected Behavior
CRUD of blocks like before

**Comment by PhilinTv** [comment]
Thank you for your report. 
Regarding the new decoupling of CMS modules, you need to install spryker/cms-block-gui module to get an access to GUI of CMS Block module. 
Pure spryker/cms-block module is interesting alone if you have own managing tool.

**Comment by AndromedaXP** [comment]
Missed that. Thanks.

**Comment by AndromedaXP** [comment]
But it would be nice if the Migration Command would also support copying the glossary_key_mapping
https://academy.spryker.com/enablement/migration_guides/mg_cms_to_cms_block_console.html
