### ISSUE TITLE
Empty redis password won't work for predis 1.1.1

### ISSUE THREAD

**Issue by NilsEvers** [spryker/support#129]
When updating _spryker/redis_ to v2.0.1, which will require _predis/predis_ v1.1.1, it is not possible to connect to a redis-db with no password set.

> Fatal error: Uncaught Predis\Connection\ConnectionException: AUTH failed: ERR Client sent AUTH, but no password is set [tcp://127.0.0.1:6379] in /var/www/vhosts//httpdocs/vendor/predis/predis/src/Connection/AbstractConnection.php:155 

This will mostly affect the devvm, as redis is running without a password by default.

The problem is that the parameter `password` will still be set, even though the password is an empty string, which won't work in newer predis versions (see https://github.com/nrk/predis/pull/422).

In `\Spryker\Client\Storage\StorageFactory::getConnectionParameters` you only check if the key `STORAGE_REDIS_PASSWORD` is set in the config, but not if it is empty or false.

**Comment by dereuromark** [comment]
This should be fixed with https://github.com/spryker/Collector/releases/tag/5.1.6 and https://github.com/spryker/Storage/releases/tag/3.1.1
