### ISSUE TITLE
Suggestion to simplify DataImporter code

### ISSUE THREAD

**Issue by a-ast** [spryker/support#131]
This is a

* [ ] bug
* [x] enhancement

spryker/data-import, version: 1.0.0

Class: Spryker/Zed/DataImport/Business/Model/DataImporter.php
Method: importDataSet
Lines: 167-171

```
            } catch (Exception $exception) {
                throw $exception;
            }
```
Catching and throwing exception immediately makes no sense.

Suggestion to without try/catch
```
        foreach ($this->dataSetStepBroker as $dataSetImporter) {
                $dataSetImporter->execute($dataSet);
        }
```

**Comment by tvaleriy** [comment]
Thanks for your feedback. I will notify when it is implemented.

**Comment by dereuromark** [comment]
Solved with https://github.com/spryker/DataImport/releases/tag/1.0.1
