### ISSUE TITLE
Collector Exception when changing Product-Url back to a former Url

### ISSUE THREAD

**Issue by skck** [spryker/support#132]
This is a

* [x] bug
* [ ] enhancement

Module Versions

`spryker/collector: 5.3.0`
`spryker/product: 5.2.0`

Reproduced in latest demoshop (Commit 3d9addab87d965d0823069d82e19fd6c2e5beca7)

### What you did

1. Disable scheduled collectors (to see Exception, not having to look it up in jenkins logs)
2. Go to Zed UI -> Products
3. Change name of any product to something new
4. Run Storage Collector
5. Change name of the product back to former name
5. Run Storage Collector

> Note: Maybe you have to repeat steps 3 and 4 another time to get the error.

### Actual Behavior

On collector execution, an exception is thrown:

```
...
* url (2)PDOException - Exception: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "spy_touch_storage-unique-fk_locale"
DETAIL:  Key (fk_locale, key)=(66, de.en_us.url./en/canon-powershot-n-35) already exists.
in /data/shop/development/current/vendor/propel/propel/src/Propel/Runtime/Connection/PdoConnection.php (117)

Command: /data/shop/development/current/vendor/bin/console collector:storage:export
```

### Expected Behavior

Collector does not throw exception.

**Comment by skck** [comment]
Forgot to mention one important thing:

On the next collector execution, the error is gone, and everything was exported correctly.

But imagine having this error on 500 products, would mean collector would throw errors for 500 minutes, if those are being executed every minute.

**Comment by tvaleriy** [comment]
Fixed with https://github.com/spryker/Collector/releases/tag/5.4.0.
