### ISSUE TITLE
Facet search - number of options is wrong

### ISSUE THREAD

**Issue by mruoss** [spryker/support#133]
This is a

* [x] bug
* [ ] enhancement

### What you did

I'm using Spryker Catalog and Search bundles in order to configure product search on our project. Concretely, I'm trying to configure Facets to return a specific number of filter options (per default Elasticsearch returns 10 options). In our class `CatalogSearchConfigBuilder` I add two facet configurations as follows. Please not the `setSize(5)` and `setSize(6)`:

```php
<?php
$facetConfigBuilder->addFacet(
    (new FacetConfigTransfer())
        ->setName('width')
        ->setParameterName('width')
        ->setFieldName(PageIndexMap::STRING_FACET)
        ->setIsMultiValued(true)
        ->setSize(5)
        ->setType(SearchConfig::FACET_TYPE_ENUMERATION)
);
$facetConfigBuilder->addFacet(
    (new FacetConfigTransfer())
        ->setName('length')
        ->setParameterName('length')
        ->setFieldName(PageIndexMap::STRING_FACET)
        ->setIsMultiValued(true)
        ->setSize(6)
        ->setType(SearchConfig::FACET_TYPE_ENUMERATION)
);
```

Spryker creates an Elasticsearch query with one aggregation for all facets. Obviousely this cannot include the different bucket sizes for the two facets. The result therefore always contains 10 filter options.

### Actual Behavior

Spryker creates an Elasticsearch query with the following aggregation for my facets:

```json
"aggs": {
  "string-facet": {
    "nested": {
      "path": "string-facet"
    },
    "aggs": {
      "string-facet-name": {
        "terms": {
          "field": "string-facet.facet-name"
        },
        "aggs": {
          "string-facet-value": {
            "terms": {
              "field": "string-facet.facet-value"
            }
          }
        }
      }
    }
  }
}
```

### Expected Behavior

I would expect a query that lists the facets separately - perhaps like this:

```json
"aggs": {
  "string-facet": {
    "nested": {
      "path": "string-facet"
    },
    "aggs": {

      "width": {
        "filter": {
          "term": {
            "string-facet.facet-name": {
              "value": "width",
              "boost": 1
            }
          }
        },
        "aggs": {
          "string-facet-value": {
            "terms": {
              "field": "string-facet.facet-value",
              "size": 5
            }
          }
        }
      },

      "length": {
        "filter": {
          "term": {
            "string-facet.facet-name": {
              "value": "length",
              "boost": 1
            }
          }
        },
        "aggs": {
          "string-facet-value": {
            "terms": {
              "field": "string-facet.facet-value",
              "size": 6
            }
          }
        }
      }
    }
  }
}
```

**Comment by tvaleriy** [comment]
Thank you for your feedback. We will notify when it is fixed.

**Comment by tvaleriy** [comment]
https://github.com/spryker/Search/releases/tag/6.7.0

**Comment by mruoss** [comment]
Thanks a lot @tvaleriy! In the release text I see something about `isStandalone` flag. However, in the [included commits](https://github.com/spryker/Search/compare/6.6.0...6.7.0) I can't find anything about it. They are now standalone per default, right?

**Comment by dereuromark** [comment]
On a side note: The project related changes are in https://github.com/spryker/demoshop/commit/5306f6fa1ec2bce92be39e43f8655fbdfc39df11
But they are optional as the current way should still work for BC reasons.

**Comment by mruoss** [comment]
Thank you @dereuromark. Also just on a side note: I don't think 0 is an allowed value for the bucket size. At least in our version of elastic, I would get `Search failed with the following reason: [terms] failed to parse field [size].` if I set size to 0 (`static::SIZE_UNLIMITED`).

that was really just a side note - in my view, the new version works as expected.

**Comment by PhilinTv** [comment]
@mruoss 
1. `isStandalone` was a middle way solution. Documentation will be adjusted.

Now each facet filter is managed as a separate aggregation if it contains configuration. This keeps BC and gives an ability for advanced usage.

2. `If set to `0`, the `size` will be set to Integer.MAX_VALUE.` was deprecated and then removed after 2.4.
