### ISSUE TITLE
missing script

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#136]
This is a

* [x] bug
* [ ] enhancement

spryker/Cms 6.1.3

### Actual Behavior

in Zed/Cms/Presentation/Layout/layout.twig:12 is a missing js file included
    ```<script src="/assets/js/spryker-zed-cms-content-widget-main.js"></script>```

**Comment by abelspry** [comment]
Bugfix has been released:
https://release.spryker.com/releases/view/270/CORE-2182-decouple-js-hidden-dependency-in-cms

**Comment by tvaleriy** [comment]
https://github.com/spryker/Cms/releases/tag/6.3.1
