### ISSUE TITLE
Handling of controller action not found

### ISSUE THREAD

**Issue by dantleech** [spryker/support#138]
This is a

* [ ] bug
* [x] enhancement

Please provide the exact versions of the modules involved (see composer.lock file).

Note sure what is responsible for this behavior, `spryker/application 3.4.0`

### What you did

Had a typo in the action name of a controller, e.g. `hello` and requesting `/blah/gateway/hello`

### Actual Behavior

```
Argument 2 passed to Symfony\Component\HttpKernel\Event\FilterControllerEvent::__construct() must be callable, array given, called in vendor/symfony/http-kernel/HttpKern
el.php on line 138
```

### Expected Behavior

An exception with something like:

```
Could not find action "helloAction" in controller "Acme\HelloController"
```

**Comment by tvaleriy** [comment]
I've moved this ticket here - https://spryker.ideas.aha.io/ideas/CUSTIDEAS-I-15. You can track the progress there.
I'm closing this ticket here.
