### ISSUE TITLE
Static constructors for transfer objects

### ISSUE THREAD

**Issue by dantleech** [spryker/support#139]
Currently it is necessary to first instantiate a transfer object, and then to initialize it with `->fromArray`
It would be nicer if it had a static constructor: `$xxx = xxxTransfer::fromArray([]);`

* [ ] bug
* [x] enhancement

### Actual

```php
$barTransfer = new BarTransfer;
$barTransfer->fromArray([]);
```

### Desired Behavior

```php
$barTransfer = BarTransfer::fromArray([]);
```

**Comment by dereuromark** [comment]
I would rather propose a factory method and then use the methods:
```
BarTransfer::create()->fromArray(...)->toArray()->...
```
otherwise you need to many such static class methods.

**Comment by dantleech** [comment]
> otherwise you need too many such static class methods.

What others could there be?

**Comment by dereuromark** [comment]
- unserialize()?
- ... future ones.

Keeping it agnostic would allow any method on top then.

**Comment by dantleech** [comment]
hmm, guess I am coming from an immutable object perspective, both `::fromArray` and `::unserialize` seem to be things that could create a fully valid object so would make sense from that POV. `Transfer::unserialize($json)` would be wierd though.

**Comment by dereuromark** [comment]
I'd agree with you, IF we had an immutable approach here. So until that is the case I would not recommend to pollute the constructor here with a "lie". Once immutable is really true, I would not object :)

So are you OK with my approach from above given the circumstances?

**Comment by dantleech** [comment]
Yeah, I think it makes sense as it has a fluent interface `Transfer::create()->fromArray([])->setFkCustomer(12)`

**Comment by dereuromark** [comment]
We are not implementing this.
