### ISSUE TITLE
Autoload definition of test helpers in Product module wrong

### ISSUE THREAD

**Issue by ThomasKuehnel** [spryker/support#140]
This is a

* [x] bug

### What you did
I required `SprykerTest\Shared\Product\Helper\ProductDataHelper` in one of my project level tests

### Actual Behavior
`vendor/bin/codecept build` fails with 
```
[Codeception\Exception\ConfigurationException]
Module \SprykerTest\Shared\Product\Helper\ProductDataHelper could not be found and loaded
```

### Expected Behavior
The test helper can be loaded

It seems to be an issue in _Product_ module's `composer.json` file which has a typo for the PSR-4 auto-load definition:
https://github.com/spryker/Product/blob/5.2.0/composer.json#L27

**Comment by dereuromark** [comment]
https://github.com/spryker/Product/releases/tag/5.2.1
