### ISSUE TITLE
CodeSniffer doesnt remove unused use statements

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#141]
This is a

* [x] bug
* [ ] enhancement

spryker/code-sniffer                 dev-master aec92a8

### What you did
Upgrading bundle
Using the last ruleset.xml from demoshop

### Actual Behavior
unused use statements are not removed anymore
The class with the problems is checked but no warnings or errors are shown

###EXTRA
when using the -module paramater, this module on project level is not taking into regard

### Expected Behavior
unused use statements should be removed

**Comment by dereuromark** [comment]
Can you show an example of what code is not removed even though it should be?
The sniffer so far never removed any use statements that are not necessary due to the same namespace.
We will soon also add this, but for any other use statement we cannot reproduce the issue.

As for the -module, this was always a core feature (--help: `Name of core module to fix code style for (or "all"`).
For project level you so far must specify the path, e.g.

    src/Pyz/Zed/Customer

etc.
We are thinking about allowing -module to work for project, but that is not trivial as the module is split across multiple namespaces compared to the core level.

**Comment by AndromedaXP** [comment]
we copied the ruleset.xml and added some extra exclude pattern, not more.
When running `vendor/bin/console code:sniff -e` I dont see the spryker Sniffs, how do I add them?

`Generic (15 sniffs)
-------------------
  Generic.Arrays.DisallowLongArraySyntax
  Generic.CodeAnalysis.ForLoopShouldBeWhileLoop
  Generic.CodeAnalysis.ForLoopWithTestFunctionCall
  Generic.CodeAnalysis.JumbledIncrementer
  Generic.CodeAnalysis.UnconditionalIfStatement
  Generic.CodeAnalysis.UnnecessaryFinalModifier
  Generic.Files.LineEndings
  Generic.Formatting.DisallowMultipleStatements
  Generic.Formatting.NoSpaceAfterCast
  Generic.PHP.DeprecatedFunctions
  Generic.PHP.ForbiddenFunctions
  Generic.PHP.LowerCaseConstant
  Generic.PHP.NoSilencedErrors
  Generic.WhiteSpace.DisallowTabIndent
  Generic.WhiteSpace.ScopeIndent

PEAR (3 sniffs)
---------------
  PEAR.ControlStructures.ControlSignature
  PEAR.Functions.ValidDefaultValue
  PEAR.NamingConventions.ValidClassName

PSR2 (7 sniffs)
---------------
  PSR2.ControlStructures.ControlStructureSpacing
  PSR2.ControlStructures.ElseIfDeclaration
  PSR2.ControlStructures.SwitchDeclaration
  PSR2.Files.EndFileNewline
  PSR2.Methods.FunctionCallSignature
  PSR2.Namespaces.NamespaceDeclaration
  PSR2.Namespaces.UseDeclaration

Squiz (18 sniffs)
-----------------
  Squiz.Arrays.ArrayBracketSpacing
  Squiz.Classes.LowercaseClassKeywords
  Squiz.Commenting.DocCommentAlignment
  Squiz.ControlStructures.ForEachLoopDeclaration
  Squiz.ControlStructures.LowercaseDeclaration
  Squiz.Functions.FunctionDeclaration
  Squiz.Functions.FunctionDeclarationArgumentSpacing
  Squiz.Functions.MultiLineFunctionDeclaration
  Squiz.Operators.ValidLogicalOperators
  Squiz.PHP.Eval
  Squiz.PHP.NonExecutableCode
  Squiz.Scope.MemberVarScope
  Squiz.Scope.MethodScope
  Squiz.Scope.StaticThisUsage
  Squiz.WhiteSpace.LanguageConstructSpacing
  Squiz.WhiteSpace.LogicalOperatorSpacing
  Squiz.WhiteSpace.SemicolonSpacing
  Squiz.WhiteSpace.SuperfluousWhitespace

Zend (1 sniff)
---------------
  Zend.Files.ClosingTag`

**Comment by AndromedaXP** [comment]
Found it.
I must define a rule for spryker Sniffs
`<rule ref="vendor/spryker/code-sniffer/Spryker/Sniffs">
    </rule>`

**Comment by dereuromark** [comment]
Indeed, please see https://github.com/spryker/demoshop/blob/master/config/ruleset.xml

As for the other issues, we are fixing them right now.
https://github.com/spryker/code-sniffer/commit/456fcd8cc3fd71e8aefd54d159bee9bd25a1824f was part of the problem and was also ignoring some PHP files, please use latest dev-master until we release a bugfix patch.

**Comment by AndromedaXP** [comment]
Alright. Thanks for that hint.
I did somehow looked at the wrong file without this nice trick `<rule ref="vendor/spryker/code-sniffer/Spryker/ruleset.xml"/>`
