### ISSUE TITLE
Undeclared dependency in spryker-eco/payone 1.0.4

### ISSUE THREAD

**Issue by srmarsov** [spryker/support#142]
This is a

* [x] bug
* [x] enhancement

In version 1.0.4 of the spryker-eco/payone module, there is a dependency introduced to the spryker/step-engine module v3.0.1, but it is not declared in composer.json.

### What you did
- Upgrade spryker-eco/payone module from version 1.0.3 to 1.0.4. 
- Install composer dependencies

### Actual Behavior
- Dependency to step-engine 3.0.1 not declared in composer.json.
- Exception thrown because of interface SubFormProviderNameInterface is not found.

### Expected Behavior
- Dependency added to composer.json.
- Should not throw exceptions.

**Comment by darius-telycenas** [comment]
Actually, `SubFormProviderNameInterface` was introduced in `v3.1.0`…

**Comment by srmarsov** [comment]
Exactly. The problem appears when you upgrade spryker-eco/payone to v1.0.4, but you have step-engine v2.*. Probably the 'Expected Behaviour' above is not clear enough.

###Expected Behavior

- Dependency to spryker/step-engine v3.1.0 should be added to composer.json in module spryker-eco/payone v1.0.4.

**Comment by tvaleriy** [comment]
Hi Mirche! Finally fixed in https://github.com/spryker-eco/payone/releases/tag/1.2.0.
