### ISSUE TITLE
Hardcoded path in spryker/Setup

### ISSUE THREAD

**Issue by fuhbar** [spryker/support#143]
This is a

* [x] bug

For questions please consult the [Spryker Forum](http://discuss.spryker.com/).

Please provide the exact versions of the modules involved (see composer.lock file).

- Most recent demoshop
- Most recent spryker/setup 

### What you did

Run console command `setup:jenkins:generate`.

### Actual Behavior

The jobs to be created have hard coded pathes in the command section like the following (line 3):

```
export APPLICATION_ENV=development
export APPLICATION_STORE=DE
cd /data/shop/development/current
. ./config/Zed/cronjobs/cron.conf
$PHP_BIN vendor/bin/console oms:check-condition
```

This code is generated by https://github.com/spryker/Setup/blob/master/src/Spryker/Zed/Setup/Communication/Controller/JenkinsController.php#L171. 

### Expected Behavior

There are plenty of smarter options: 

* Use `APPLICATION_ROOT_DIR`
* Make this configurable like for non development environments. See https://github.com/spryker/Setup/blob/master/src/Spryker/Zed/Setup/Communication/Controller/JenkinsController.php#L164

**Comment by tvaleriy** [comment]
Thank you for your feedback. I will notify when it is changed.

**Comment by fuhbar** [comment]
Perhaps this could be restated in more general terms:
```
/data/shop # grep -r /data/shop vendor/spryker/*
vendor/spryker/error-handler/src/Spryker/Shared/ErrorHandler/Plugin/ServiceProvider/WhoopsErrorHandlerServiceProvider.php:                $serverPath = Config::get(ErrorHandlerConstants::SERVER_BASE_PATH, '/data/shop/development/current');
vendor/spryker/error-handler/src/Spryker/Shared/ErrorHandler/ErrorHandlerConstants.php:     * - This is used to replace the path from server (/data/shop/development/current) with the user path.
vendor/spryker/error-handler/src/Spryker/Shared/ErrorHandler/ErrorHandlerConstants.php:     * - Path to the project on virtual machine, defaults to `/data/shop/development/current`
vendor/spryker/kernel/src/Spryker/Shared/Kernel/Exception/Backtrace.php:    const CURRENT_PATH = '/data/shop/development/current';
vendor/spryker/setup/src/Spryker/Zed/Setup/Communication/Controller/JenkinsController.php:cd /data/shop/development/current/config/Zed/cronjobs
vendor/spryker/setup/src/Spryker/Zed/Setup/Business/Model/Cronjobs.php:cd /data/shop/development/current
```

**Comment by tvaleriy** [comment]
Should fixed in https://github.com/spryker/setup/releases/tag/4.1.0.
