### ISSUE TITLE
Missing twig variable for zed sales detail view

### ISSUE THREAD

**Issue by NilsEvers** [spryker/support#144]
This is a

* [x] bug
* [ ] enhancement

The template `Zed\Sales\Presentation\Detail\boxes\no-group-items.twig` is missing the **image** variable definition:
```
{% embed '@Sales/Detail/boxes/order-item.twig' with {orderItem: orderItem, displayImage: true, displayTotals: true, group: false} %}{% endembed %}
```
When you compare it with `Zed\Sales\Presentation\Detail\boxes\item-group.twig`
```
{% embed '@Sales/Detail/boxes/bundle-group.twig' with {items: group.groupItems, image: group.groupImage, rowCount: group.rowCount, bundleItem: group.bundleItem} %}{% endembed %}
```

This causes the twig error _"**image** is not defined"_ for non-grouped items and therefore makes the detail view unusable.

I am on version 7 of the Sales module, but judging from the code, the current release seems to have the same problem as well.

**Comment by tvaleriy** [comment]
Thank you for your feedback. I will notify when it is fixed.

**Comment by tvaleriy** [comment]
Hi @NilsEvers. Should be fixed with https://github.com/spryker/Sales/releases/tag/8.0.4 .
