### ISSUE TITLE
Calculation 4.2.0 requires Discount 5.0.0

### ISSUE THREAD

**Issue by mruoss** [spryker/support#145]
This is a

* [x] bug

We recently upgraded our Spryker bundles. Amongst the updates the Calculation bundle update from version 4.1.1 to 4.2.0. In 4.2.0 the DiscountAmountAggregator was [changed](https://github.com/spryker/Calculation/compare/4.1.1...4.2.0#diff-88798538e8b2de98bbc659221c662e0cR100). It now calls `$calculatedDiscountTransfer->getUnitAmount()` - before was `calculatedDiscountTransfer->getUnitGrossAmount()`. However, the field unit_amount on the `CalculatedDiscountTransfer` was only introduced in version 5.0.0 of the Discount bundle which is not a dependency of Calculation 4.2.0. 

It would be nice to be able to upgrade Calculation without upgrading to Discount 5.0.0

Thanks,
Michael

**Comment by tvaleriy** [comment]
@mruoss should be fixed with https://github.com/spryker/Calculation/releases/tag/4.2.1 .
