### ISSUE TITLE
spryker/flysystem - FileSystemReaderPlugin::listContents() does not forward recursive flag

### ISSUE THREAD

**Issue by mruoss** [spryker/support#146]
This is a

* [x] bug

For questions please consult the [Spryker Forum](http://discuss.spryker.com/).

Please provide the exact versions of the modules involved (see composer.lock file).

### What you did
Using the `Aws3v3FilesystemBuilderPlugin`, I execute the following code:

```php
        $fileSystemListTransfer = new FileSystemListTransfer();
        $fileSystemListTransfer->setFileSystemName('media');
        $fileSystemListTransfer->setPath('/');
        $fileSystemListTransfer->setRecursive(true);

        $fileSystemResourceTransfers = $this->getFactory()->getFileSystemService()->listContents($fileSystemListTransfer);
        foreach ($fileSystemResourceTransfers as $fileSystemResourceTransfer) {
            $output->writeln("{$fileSystemResourceTransfer->getFilename()}.{$fileSystemResourceTransfer->getExtension()}");
        }
```

### Actual Behavior

This returns the list of files in the requested directory.

### Expected Behavior

Since I'm setting `$fileSystemListTransfer->setRecursive(true);` I expect the call to return the list of files in the requested directory **and its subdirectories**. However, in `Spryker\Service\Flysystem\Plugin\FileSystem\FileSystemReaderPlugin::listContents()` the recursive-flag is not forwarded:

```php

    /**
     * @param \Generated\Shared\Transfer\FileSystemListTransfer $fileSystemListTransfer
     *
     * @return \Generated\Shared\Transfer\FileSystemResourceTransfer[]
     */
    public function listContents(FileSystemListTransfer $fileSystemListTransfer)
    {
        $flysystemTransferCollection = $this->getService()->listContents(
            $fileSystemListTransfer->getFileSystemName(),
            $fileSystemListTransfer->getPath()
        );
        // ... more code
    }
```

**Comment by tvaleriy** [comment]
@mruoss Thank you for the bugreport. I will notify when it is fixed.

**Comment by tvaleriy** [comment]
Finally fixed in https://github.com/spryker/flysystem/releases/tag/1.0.3.
