### ISSUE TITLE
Payone module: Missing house number for shipping street

### ISSUE THREAD

**Issue by NilsEvers** [spryker/support#147]
This is a

* [x] bug
* [ ] enhancement

The Payone module is not setting the shipping street correctly.

[\SprykerEco\Zed\Payone\Business\Payment\MethodMapper\AbstractMapper::mapShippingAddressToShippingContainer](https://github.com/spryker-eco/payone/blob/master/src/SprykerEco/Zed/Payone/Business/Payment/MethodMapper/AbstractMapper.php#L170) is missing the house number when calling `setShippingStreet`.

This is especially a problem with PayPal, as they demand a proper shipping address for their purchase protection service.

**Comment by sergeysikachev** [comment]
Yes, there should be similar setter argument as in the method above.

**Comment by tvaleriy** [comment]
https://github.com/spryker-eco/payone/releases/tag/1.1.0.
