### ISSUE TITLE
Variable "money_pattern" does not exist.

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#148]
This is a

* [x] bug
* [ ] enhancement

Please provide the exact versions of the modules involved (see composer.lock file).
spryker/discount   5.0.0

### What you did
calling /discount/index/create

### Actual Behavior
Variable "money_pattern" does not exist.
/data/pim/development/current/vendor/symfony/twig-bridge/Resources/views/Form/bootstrap_3_layout.html.twig:24

### Expected Behavior
I did this http://academy.spryker.com/developing_with_spryker/migration_guides/mg_shipment.html but because this is a view problem only, I don't think that I missed a point there.

**Comment by aurisl** [comment]
Hi, Have you upgraded Discounts?

**Comment by AndromedaXP** [comment]
what do u mean? I have no discounts in DB, I wanted to create one..

**Comment by aurisl** [comment]
I mean that discounts version 5 coming with multicurrency support, have be migrated also.

**Comment by AndromedaXP** [comment]
I know, and I think I did all points in migration correctly. But still...

**Comment by aurisl** [comment]
Looks like you have incorrectly migrated CalculationForm maybe? I not sure what is the issue, can you paste form to git gist?

**Comment by AndromedaXP** [comment]
CalculatorForm is not overwritten from us

**Comment by aurisl** [comment]
Well you have to debug and find out more about whats happending, As this is manual work anything can go wrong.

**Comment by AndromedaXP** [comment]
twig is hard to debug. I found that normally it is globally set through
```$this->vars['money_pattern']```
but in the template its missing

**Comment by aurisl** [comment]
Discounts using `  {{ form_money_collection(discountForm.discountCalculator.moneyValueCollection) }}`  to render inputs for fixed amount. Do you have this in your template, if you extended? What you have extended in project overall?

**Comment by AndromedaXP** [comment]
Not much.
Anyways, we decided to stop upgrading spryker, way to much manual work to do.
