### ISSUE TITLE
Plain text email leading whitespace

### ISSUE THREAD

**Issue by dantleech** [spryker/support#150]
This is a

* [x] bug
* [ ] enhancement

When sending a mail in plain text using the mail module, whitespace is prefixed

```
spryker/mail                                       4.0.1              Mail bundle
```

### What you did

Send email in plain text with template:

```
Hello
World
```

### Actual Behavior

```
            Hello
World
````

### Expected Behavior

```
Hello
World
```

## Solution

Use `{% spaceless %}` in `vendor/spryker/mail/src/Spryker/Zed/Mail/Presentation/Mail/layout/mail_layout.text.twig`:

```jinja
{% for template in mail.templates %}{% spaceless %}
    {% if not template.isHtml %}
        {% include "@" ~ template.name with {mail: mail} %}
    {% endif %}
{% endspaceless %}{% endfor %}
```

**Comment by tvaleriy** [comment]
Thank you for your feedback. I will notify when it is fixed.

**Comment by tvaleriy** [comment]
This is fixed in https://github.com/spryker/mail/releases/tag/4.0.2 .
