### ISSUE TITLE
duplicate index

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#151]
This is a

* [x] bug
* [ ] enhancement

Please provide the exact versions of the modules involved (see composer.lock file).
spryker/cms-block                    1.4.1

### What you did
running propel migrate

### Actual Behavior
2 indices in spy_cms_block_template on the same attribute

spy_cms_block.schema.xml:

>          <unique name="spy_cms_block_template-unique-template_path">
>             <unique-column name="template_path"/>
>         </unique>
> 
>         <index name="spy_cms_block_template-template_path">
>             <index-column name="template_path"/>
>         </index>

### Expected Behavior
no duplicate index on spy_cms_block_template

**Comment by tvaleriy** [comment]
Hi @AndromedaXP. Thank you for your feedback. Should be fixed soon. I will notify when it is released.

**Comment by dereuromark** [comment]
This is resolved with https://github.com/spryker/CmsBlock/releases/tag/1.4.2
