### ISSUE TITLE
GatwayController::adddressAction returns null and causes Fatal error

### ISSUE THREAD

**Issue by dantleech** [spryker/support#152]
This is a

* [x] bug
* [ ] enhancement

For questions please consult the [Spryker Forum](http://discuss.spryker.com/).

Please provide the exact versions of the modules involved (see composer.lock file).

```
spryker/customer                                   6.2.4              Customer module
```

### What you did

Tried to locate an address from the customer facade which did not belong to the given customer:

```
        $addressId = 1234; // address does not belong to customer below
        $customerId = 5678;

        $addressTransfer = new AddressTransfer();
        $addressTransfer
            ->setIdCustomerAddress($addressId)
            ->setFkCustomer($customerId);

        $address = $this->customerClient->getAddress($addressTransfer);
```

### Actual Behavior

Exception:

```
Spryker\Shared\ZedRequest\Client\Exception\TransferNotFoundException: No class name given for Transfer generation." in vendor/spryker/zed-request/src/Spryker/Shared/ZedRequest/Client/AbstractResponse.php:260                                     
      Stack trace:                                                                                                                       
      #0 vendor/spryker/zed-request/src/Spryker/Shared/ZedRequest/Client/AbstractZedClient.php(84): Spryker\Shared\ZedRequest\Client\Abst
ractResponse->getTransfer()                                                                                                              
      #1 vendor/spryker/zed-request/src/Spryker/Client/ZedRequest/ZedRequestClient.php(55): Spryker\Shared\ZedRequest\Client\AbstractZedC
lient->call('/customer/gatew...', Object(Generated\Shared\Transfer\AddressTransfer), NULL)                                               
      #2 vendor/spryker/customer/src/Spryker/Client/Customer/Zed/CustomerStub.php(167): Spryker\Client\ZedRequest\ZedRequestClient->call(
```

### Expected Behavior

The problem is because the GatewayController [returns null](https://github.com/spryker/Customer/blob/master/src/Spryker/Zed/Customer/Communication/Controller/GatewayController.php#L156)  instead of the transfer object.

I think:

1. The above exception _should_ have described the controller not returning a transfer object[1]
2. but I think an exception should be thrown if the address is not found (`Could not find address with ID "%s" for customer "%s"`). Currently the action catches it and fails.

[1] I think this is a problem developers run into frequently when writing GatewayControllers.

**Comment by tvaleriy** [comment]
Thank you for your feedback. We will notify when it is fixed.

**Comment by tvaleriy** [comment]
Hi @dantleech. Sorry that it took so long, but it should be fixed in https://github.com/spryker/customer/releases/tag/7.10.2 .

**Comment by dantleech** [comment]
Thanks :+1:
