### ISSUE TITLE
Title not set by default in add new address

### ISSUE THREAD

**Issue by alexbiddle** [spryker/support#153]
This is a

* [x] bug
* [ ] enhancement

Please provide the exact versions of the modules involved (see composer.lock file).
Latest demoshop

When you add an address, it populates your firstname and lastname, but not your title

https://github.com/spryker/demoshop/blob/d47ebd6280ffc6de6fc493bb8e592722ac5483d9/src/Pyz/Yves/Customer/Form/DataProvider/AddressFormDataProvider.php#L71

I think you need `AddressForm::FIELD_SALUTATION => $customerTransfer->getSalutation(),`

**Comment by tvaleriy** [comment]
Thank your for your feedback. I will notify when it is fixed.

**Comment by tvaleriy** [comment]
This should be fixed with https://github.com/spryker-shop/customer-page/releases/tag/0.1.2 .
