### ISSUE TITLE
CmsBlockFormDataProvider doesn't catch invalid id

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#154]
This is a

* [x] bug
* [ ] enhancement

Please provide the exact versions of the modules involved (see composer.lock file).
spryker/cms-block-gui                1.1.5

### What you did
calling /cms-block-gui/edit-block?id-cms-block=xxx with an ID which doesn't exist

### Actual Behavior
Becoming exception because DataProvider of block plugins doesn't have an object

Thats why in CmsBlockFormDataProvider:getData is no check if $cmsBlockTransfer === null when $idCmsBlock is present.

### Expected Behavior
normal error that a block with this ID doesn't exist

**Comment by AndromedaXP** [comment]
nearly 2 months no status update?

**Comment by tvaleriy** [comment]
Sorry that it takes so much time. It is in the queue and should be fixed soon. We will notify when it is fixed, of course.

**Comment by tvaleriy** [comment]
This should be fixed in https://github.com/spryker/cms-block-gui/releases/tag/2.0.1 .
