### ISSUE TITLE
page cannot add new localized attributes

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#155]
This is a

* [x] bug
* [ ] enhancement

Please provide the exact versions of the modules involved (see composer.lock file).
spryker/cms                          6.3.3
spryker/cms-gui                      4.3.2

### What you did

editing an existing page which has less localized attributes saved then the shop has.

Save a page with just DE locale active for your shop => just DE localized attributes are created
Add EN locale to your shop
Edit the page again. You cannot edit EN localized attributes, just DE

### Expected Behavior
dataProvider must add all possible locales to the transfer object

**Comment by AndromedaXP** [comment]
nearly 2 months no status update on a BUG!

**Comment by tvaleriy** [comment]
Sorry that it takes so much time. It is in the queue and should be fixed soon. We will notify when it is fixed, of course.

**Comment by tvaleriy** [comment]
Finally should be fixed in https://github.com/spryker/cms/releases/tag/6.6.0 and https://github.com/spryker/cms-gui/releases/tag/4.4.0.

**Comment by AndromedaXP** [comment]
The same for spryker/category   v4.10.0... I will add a new ticket
