### ISSUE TITLE
Unable to load TwigRenderer

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#157]
This is a

* [x] bug
* [ ] enhancement

Please provide the exact versions of the modules involved (see composer.lock file).
    "spryker/symfony": "3.1.1", which will result in installing symfony/twig-bridge (v3.3.2)

### What you did
calling any formular

### Actual Behavior
Unable to load the “Symfony\Bridge\Twig\Form\TwigRenderer” runtime in “@Shipment/Cost/edit.twig” at line 34

### Expected Behavior
no error

**Comment by tvaleriy** [comment]
It is fixed with https://github.com/spryker/Symfony/releases/tag/3.1.2 and https://github.com/spryker/SetupFrontend/releases/tag/1.0.1.
