### ISSUE TITLE
Bug in bin/spryker touch:cleanup command

### ISSUE THREAD

**Issue by egobude** [spryker/support#158]
This is a

* [x] bug
* [ ] enhancement

For questions please consult the [Spryker Forum](http://discuss.spryker.com/).

Please provide the exact versions of the modules involved (see composer.lock file).

`spryker/touch: 3.1.2`

### What you did

Executed the command `bin/spryker touch:cleanup`

### Actual Behavior

Currently the command only removes 100 Entries.  

### Expected Behavior

The command should fetch all deletable entries and remove 100 per batch.

**Comment by tvaleriy** [comment]
Thank you for your feedback. I will notify when it is fixed.

**Comment by egobude** [comment]
Perfect, thank you :)

**Comment by tvaleriy** [comment]
Hi @egobude, this should have been finally fixed in https://github.com/spryker/touch/releases/tag/4.2.0.
