### ISSUE TITLE
better acl rules

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#159]
This is a

* [ ] bug
* [x] enhancement

Please provide the exact versions of the modules involved (see composer.lock file).
spryker/acl                          3.0.4 

### What you did
creating acl rules with * in bundle name

### Actual Behavior
Because spryker goes the way to separate context into different bundles like cms => cms, cms-block, cms-block-gui, cms-gui it would make acl things easier if we could add acl rules with the Wildcard * inside the name e.g. bundle name: "cms-*" instead of adding 4 rules for 4 bundles

**Comment by tvaleriy** [comment]
I've moved this ticket here - https://spryker.ideas.aha.io/ideas/CUSTIDEAS-I-36. You can track the progress there.
I'm closing this ticket here.
