### ISSUE TITLE
wrong navigation tree

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#160]
This is a

* [x] bug
* [ ] enhancement

### What you did
our config/Zed/navigation.xml looks like
`<?xml version="1.0" encoding="UTF-8"?>
<config>
    <category/>
    <cms-gui/>
    <glossary/>
    <product/>
    <discount/>
    <tax/>
    <shipment/>
    <acl/>
    <maintenance/>
</config>
`

### Actual Behavior
the navigation tree has all the point from navigation.xml in the correct order but Customers and Sales at the end. Why?

I ran `vendor/bin/console navigation:build-cache`

**Comment by dereuromark** [comment]
The comment above states

    

Entries here are only for sorting, if you omit them, they will just be added from the core modules again at the end of the tree.

If you want to silence/hide them (which I assume your intention was), then I recommend using the visible flag:

    <sales>
        <visible>0</visible>
    </sales>
    <customer>
        <visible>0</visible>
    </customer>

**Comment by AndromedaXP** [comment]
Perfect.
"Entries here are only for sorting, if you omit them, they will just be added from the core modules again at the end of the tree." => Does it take all navigation.xml files from all installed modules into account or is there a "general" navigation.xml somewhere?

**Comment by dereuromark** [comment]
It merges all of them.

**Comment by AndromedaXP** [comment]
Alright.
