### ISSUE TITLE
PageMapBuilder::ensureArrayValues() returns wrong structure

### ISSUE THREAD

**Issue by mruoss** [spryker/support#161]
This is a

* [x] bug

The class `PageMapBuilder` contains a function [`ensureArrayValues($value)`](https://github.com/spryker/Search/blob/a58390e2a4ad0bcb4f24f89440e1fb2750b15275/src/Spryker/Zed/Search/Business/Model/Elasticsearch/DataMapper/PageMapBuilder.php#L256) that turns `$value` into an array if it is not already an array. Finally, it also calls array_filter($value) on the array.

The problem now is that array_filter($value) does not change the keys of the array. Imagine `ensureArrayValues` is called passing an array where the first item is empty (e.g. `ensureArrayValues(['', 'value1', 'value2'])`). The return value of the function will be (with array keys):

```
[
1 => 'value1',
2 => 'value2',
]
```

In order to send this data to Elasticsearch, it is turned into json using `json_encode`. Now `json_encode` sees this array and will turn it into an object `{"1" => "value1", "2" => "value2"}` istead of `["value1", "value2"]` (because of the keys not being 0,1,2,...). **Elasticsearch will fail to index the object.**

Solution: pass the result of `ensureArrayValues()` through `array_values()` (i.e. change as follows):

```php
    /**
     * @param mixed $value
     *
     * @return array
     */
    protected function ensureArrayValues($value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }

        return array_values(array_filter($value));
    }
```

**Comment by tvaleriy** [comment]
Thank you for your feedback. I will notify when it is fixed.

**Comment by tvaleriy** [comment]
This is fixed in https://github.com/spryker/search/releases/tag/8.2.1.
