### ISSUE TITLE
Table filters are not saved

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#162]
This is a

* [ ] bug
* [x] enhancement

### What you did
When changing a table in zed (use search filter, sort a column or change number of results), then so an action on a object and using the browser back button, I would expect to have the same filters/sorting applied.

Also after saving an object I would at least expect that the number of results and the column sorting is persisted. Our content team goes crazy e.g. when then have to edit a bunch of filtered blocks and type that every time again.

**Comment by tvaleriy** [comment]
Thank you for your feedback. It is in our backlog now.

**Comment by tvaleriy** [comment]
I've moved this ticket here - https://spryker.ideas.aha.io/ideas/CUSTIDEAS-I-37. You can track the progress there.
I'm closing this ticket here.
