### ISSUE TITLE
datepicker popup twice in firefox

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#163]
This is a

* [x] bug
* [ ] enhancement

spryker/cms                          6.3.4 
spryker/cms-gui                      4.3.3 
spryker/gui                          3.12.1
Firefox 57 on Mac

### What you did
edit a page in zed and click on the valid from field to insert a date

### Actual Behavior
besides the jquery datepicker also the native datepicker from firefox pops up

### Expected Behavior
native datepicker should be disabled

**Comment by tvaleriy** [comment]
Thank you for your feedback. We will notify when it is fixed.

**Comment by abelspry** [comment]
fix is in QA right now

**Comment by tvaleriy** [comment]
It should be fixed now:
https://github.com/spryker/ProductManagement/releases/tag/0.9.2
https://github.com/spryker/ProductLabelGui/releases/tag/2.0.2
https://github.com/spryker/Discount/releases/tag/5.2.1
https://github.com/spryker/CmsGui/releases/tag/4.3.4
https://github.com/spryker/CmsBlockGui/releases/tag/1.1.7
https://github.com/spryker/NavigationGui/releases/tag/2.1.0
https://github.com/spryker/Gui/releases/tag/3.13.0
