### ISSUE TITLE
spryker/sales 8.3.0 breaks BC (with checkout version < 4.0.0)

### ISSUE THREAD

**Issue by mruoss** [spryker/support#164]
This is a

* [x] bug

In `spryker/sales` version 8.3.0 the function declaration of SalesOrderExpanderPlugin::preSave() [was changed](https://github.com/spryker/Sales/compare/8.2.1...8.3.0#diff-a99da4de29661cfa77d3bf0453a80b2cL29), (probably in order to be compatible with checkout version 4.0.0). This breaks when using checkout version < 4.0.0:

```
FATAL ERROR - Declaration of Spryker\\Zed\\Sales\\Communication\\Plugin\\SalesOrderExpanderPlugin::preSave(Generated\\Shared\\Transfer\\QuoteTransfer $quoteTransfer) must be compatible with Spryker\\Zed\\Checkout\\Dependency\\Plugin\\CheckoutPreSaveHookInterface::preSave(Generated\\Shared\\Transfer\\QuoteTransfer $quoteTransfer, Generated\\Shared\\Transfer\\CheckoutResponseTransfer $checkoutResponseTransfer)
```

**Comment by tvaleriy** [comment]
Hi @mruoss . Thank you for your feedback. We will notify when it is fixed.

**Comment by tvaleriy** [comment]
Hi @mruoss. Please update to https://github.com/spryker/Checkout/releases/tag/4.0.1 and https://github.com/spryker/Sales/releases/tag/8.4.1 . Should be fixed.

**Comment by mruoss** [comment]
Hi @tvaleriy 
We're currently on checkout version 3.X. I would like to stay on 3.X Is the sales bundle not backwards compatible?

**Comment by PhilinTv** [comment]
Hi @mruoss,
Checkout v3 is compatible with the new Sales module. The patch for v3 will be released soon and we will notify you about it.

**Comment by PhilinTv** [comment]
Hi @mruoss,
The release of Checkout 4.0.1 is not relevant to you. Checkout 3.x is compatible with Sales 8.x.
Please take the Sales 8.4.1 patch and let us know if it fits you. 
Thank you for your question.

**Comment by mruoss** [comment]
Okay, thanks.
