### ISSUE TITLE
Attributes missing (spryker/product)

### ISSUE THREAD

**Issue by msecker** [spryker/support#165]
This is a

* [X] bug
* [ ] enhancement

Version: spryker/product 5.4.0

### What you did
Updated to spryker/product 5.4.0

### Actual Behavior
`AttributeLoader::getCombinedAbstractAttributeKeys()` now return an array with fewer fields, so some attributes are missing

### Expected Behavior
I want to retrieve all attributes as before I updated the package.

### Reason
`AttributeLoader::getCombinedAbstractAttributeKeys()` now makes use of an internal protected method `getCombinedAbstractAttributeKeysForEntity()`, but the second argument `$localeTransfer` is not set, so it defaults to NULL

**Comment by tvaleriy** [comment]
Thank you for your feedback. We will notify when it is fixed.

**Comment by MarcBoeing** [comment]
@tvaleriy I believe it has already been fixed with https://github.com/spryker/product/releases/tag/5.4.1 
Best regards
Marc

**Comment by tvaleriy** [comment]
Yes. And https://github.com/spryker/Product/releases/tag/5.4.2 . It was released yesterday, have no chance to notify yesterday.

**Comment by MarcBoeing** [comment]
Was released on 9.1. or is released when it´s part of a full release with release note on the accademy?

**Comment by tvaleriy** [comment]
@MarcBoeing I'm tracking tickets internally through Jira and status of this ticket was changed to "released" yesterday in the evening. Sorry for the inconvenience.
