### ISSUE TITLE
Search: transport config setting 'https' does not result in SSL request

### ISSUE THREAD

**Issue by bazoo0815** [spryker/support#166]
This is a

* [x] bug

Using:
`spryker/search: 6.10.0`
`ruflin/elastica: 3.2.3`

We want to use an external ElasticSearch instance in our project and added the required settingsd in the configuration, like `$config[SearchConstants::ELASTICA_PARAMETER__HOST]` etc..
This includes `$config[SearchConstants::ELASTICA_PARAMETER__TRANSPORT]` set to `https`, because we want to use a SSL connection for accessing ES.

But setting this does not result in a proper request URL prefixed with `https://`, but still `http://` is used, because in `\Spryker\Shared\Search\Provider\AbstractSearchClientProvider::getClientConfig()` the config key `transport` will never be set based on this value (except when you provide the whole client config in a predefined array named `$config[SearchConstants::ELASTICA_CLIENT_CONFIGURATION]` which is kind of a dirty workaorund from my point of view).
Only the key `protocol` is set from the config value, but that's not resulting in a properly prefixed URL.

In `\Elastica\Transport\AbstractTransport::create()` the correct transport class will be loaded based on the transport setting.
See also:
`\Elastica\Connection::getTransportObject`
`\Elastica\Connection::getTransport`

IMHO just adding the setting of this config key to `\Spryker\Shared\Search\Provider\AbstractSearchClientProvider::getClientConfig()` right after line 40 would fix this issue:
```
        $config['protocol'] = ucfirst(Config::get(SearchConstants::ELASTICA_PARAMETER__TRANSPORT));
        $config['transport'] = Config::get(SearchConstants::ELASTICA_PARAMETER__TRANSPORT);
```

**Comment by tvaleriy** [comment]
Thank you for the feedback. We will notify when it is fixed.

**Comment by tvaleriy** [comment]
Hi @bazoo0815, finally it's fixed in https://github.com/spryker/collector/releases/tag/6.1.7 and https://github.com/spryker/search/releases/tag/8.3.1.
