### ISSUE TITLE
PropelSchemaPathPatterns is not get from Constant

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#167]
This is a

* [x] bug
* [ ] enhancement

spryker/propel 3.3

### What you did
a new function was introduced when updating spryker/propel
```    public function getPropelSchemaPathPatterns()
    {
        return array_merge(
            $this->getCorePropelSchemaPathPatterns(),
            $this->getProjectPropelSchemaPathPatterns()
        );
    }
 ```

So I would think that both methods would use a PropelConstant which can be defined to make a overwrite of PropelConfig on project side unnecessary like in 
https://github.com/spryker/demoshop/blob/master/src/Pyz/Zed/Propel/PropelConfig.php

But why does getCorePropelSchemaPathPatterns return an empty array and getProjectPropelSchemaPathPatterns the core pattern instead?

**Comment by PhilinTv** [comment]
Hi @AndromedaXP ,

The method name probably is confusing `getCorePropelSchemaPathPatterns`, its main task is to return internal paths, which Spryker team uses during development. All project specific paths, even for Spryker modules, are coming from getProjectPropelSchemaPathPatterns.

Please check the value in config files, defined by `Spryker\Shared\Propel\PropelConstants::SCHEMA_FILE_PATH_PATTERN` to find the source of these paths.

**Comment by AndromedaXP** [comment]
So, we are still forced to overwrite the PropelConfig like in demoshop?

**Comment by PhilinTv** [comment]
If the question is "Should you extend PropelConfig on the project level (eg demoshop) to add a project path?", then yes.

Environment nonspecific values always come from module config (eg. PropelConfig). Propel schema paths are not specific to an environment (eg dev/staging/live).

**Comment by AndromedaXP** [comment]
ok. Thanks.
