### ISSUE TITLE
missing dependency from discount to product-option

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#168]
This is a

* [x] bug
* [ ] enhancement

spryker/discount                     4.6.0

### What you did

removed product-option bundle from project which is fine with composer BUT run into propel errors

### Actual Behavior

https://github.com/spryker/discount/blob/master/composer.json
doesn't show any dependency to product-option bundle BUT
https://github.com/spryker/discount/blob/master/src/Spryker/Zed/Discount/Persistence/Propel/Schema/spy_sales.schema.xml
shows a dependency to the table `spy_sales_order_item_option` which is created in
https://github.com/spryker/product-option/blob/master/src/Spryker/Zed/ProductOption/Persistence/Propel/Schema/spy_sales.schema.xml

### Expected Behavior

no dependency

**Comment by tvaleriy** [comment]
Thank you for the feedback. We will fix this. I will notify when it is released.

**Comment by AndromedaXP** [comment]
for us it would be a great advantage if you not just add product-option as a dependency but also remove this dependency from this bundle, because we use your old "product-option syntax" and won't need your bundle at all

**Comment by tvaleriy** [comment]
Ok, taken into account.

**Comment by AndromedaXP** [comment]
We upgraded to 6.1, this problem still exists!

**Comment by tvaleriy** [comment]
It wasn't fixed yet.

**Comment by tvaleriy** [comment]
Hi @AndromedaXP, sorry for the delay here. It has been fixed in the other ticket so I didn't see this update.
Unfortunately this dependency hasn't been removed but just added here - https://github.com/spryker/discount/compare/6.3.1...6.3.2.

So please update to https://github.com/spryker/discount/releases/tag/6.3.2.

Best,
Spryker Support Team
