### ISSUE TITLE
tax forms cannot edit existing taxes

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#169]
This is a

* [x] bug
* [ ] enhancement

### What you did
upgraded spryker/tax to 5.1.5

### Actual Behavior
The change of the factory doesn't take into account passing an existing tax id to ``` $this->createTaxRateFormDataProvider()->getData()```
so it is not possible to edit existing taxes
https://github.com/spryker/tax/compare/5.1.4...5.1.5#diff-a37d2f1dca6acb99f16fb2363fdaa32e

**Comment by tvaleriy** [comment]
Thank you for the feedback. I can confirm this. Will notify when it is fixed and released.

**Comment by tvaleriy** [comment]
@AndromedaXP Should be fixed with https://github.com/spryker/tax/releases/tag/5.1.7 . Please check.
