### ISSUE TITLE
SessionHandlerRedisLocking connects already in constructor

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#170]
This is a

* [x] bug
* [ ] enhancement

spryker/session 3.2.2

running unit tests on a jenkins which doesn't have a redis resulted in an error because the SessionHandlerRedisLocking connects to redis already in constructor.

**Comment by dereuromark** [comment]
This is to be expected when you instantiate such a class.
Either the server should provide the necessary tooling for the classes to work/run, or the service (in this case this class) should be mocked away in test mode.

**Comment by AndromedaXP** [comment]
Sorry, I do not think that this behavior is expected. It is not supposed to be doing work in the constructor, that is a known anti-pattern. Albeit that providing the infrastructure would solve the issue at hand, it is definitely advisable to move the connecting out of the constructor, especially if there is a designated method for doing that: the open-Method. It is a very simple fix, but should still be done to uphold a high software quality standard.

**Comment by dereuromark** [comment]
It should indeed not do any business logic. I took a look into the class itself and it can be improved using a $connected attribute and lazy-connect then.

Classifying as enhancement/improvement then.

**Comment by AndromedaXP** [comment]
Great. Thanks!

**Comment by tvaleriy** [comment]
I've moved this ticket here - https://spryker.ideas.aha.io/ideas/CUSTIDEAS-I-39. You can track the progress there.
I'm closing this ticket here.
