### ISSUE TITLE
FIELD_META_TITLE in cms gui must be limit to 255

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#172]
This is a

* [x] bug
* [ ] enhancement

spryker/cms                          6.4.2  
spryker/cms-gui                      4.3.5 

### What you did
Inserting a meta title to a page which is longer than 255 will be truncated because the database field is this long.
this is confusing for the user and should be avoided e.g. with a maxlength

**Comment by tvaleriy** [comment]
Thank you for the feedback. I will notify when it is fixed and released.

**Comment by dereuromark** [comment]
Since the recommendation is
```
There are no hard and fast rules regarding the length of title and meta description tags. However, the recommended length of title is somewhere between 65 to 70 characters including spaces, because more than this likely to be truncated in the search results. So try to keep the title length to 65 characters including spaces for best possible rendering. You can go up to 70 characters in total, but try not to exceed this.
```

Adding a max imit of 255 (instead of going to text type) makes sense :+1:

**Comment by AndromedaXP** [comment]
great. html5 attribute should be enough instead of a extra Validator.

**Comment by tvaleriy** [comment]
Hi @AndromedaXP, this should have been fixed in https://github.com/spryker/cms-gui/releases/tag/5.5.2.

Best,
Spryker Support Team
