### ISSUE TITLE
propel migration does wrong order

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#173]
This is a

* [x] bug
* [ ] enhancement

spryker/propel                       3.5.

### What you did
changing an index and adding a row on a project table. Migration file for mysql will DROP INDEX first, then ALTER TABLE and ADD INDEX at last. But this will result in an error in mysql because dropping an index will set the table to dirty and the ALTER TABLE will result in an `SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint`
Changing the order by ALTER TABLE first and then DROP INDEX and ADD INDEX will work fine.

**Comment by tvaleriy** [comment]
Thank you for the feedback. We need to investigate this at first.

**Comment by ridculy** [comment]
FYI : Used Database was mysql 5.6.30

**Comment by ilyakubanov** [comment]
Could you please clarify the structure and changes in the tables?

**Comment by tvaleriy** [comment]
@AndromedaXP, @ridculy could you please update us with the required information or should I close this issue?
