### ISSUE TITLE
CategoryToTouchInterface uses removed functions

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#174]
This is a

* [x] bug
* [ ] enhancement

spryker/category                     4.3.3
spryker/touch                        4.0.0

### What you did
category bundle has dependency `  "spryker/touch": "^3.0.0 || ^4.0.0",` but in CategoryToTouchInterface functions are used/listed (bulkTouchActive, bulkTouchInactive) which are removed in spryker/touch v4

**Comment by tvaleriy** [comment]
Thank you for the feedback. We will notify when it is fixed.

**Comment by tvaleriy** [comment]
Sorry for the late notification. Should be fixed in https://github.com/spryker/category/releases/tag/4.4.1.
