### ISSUE TITLE
symfony/forms v3 will break old spryker bundles

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#175]
This is a

* [x] bug
* [ ] enhancement

### What you did
update to `spryker/symfony 3.1.4` which is supposed to be a minor update but it has a BC break in it that all symfony2 forms will not work anymore (when forms are instantiated). So all bundles which are not up2date e.g. we are still using ` spryker/discount 4.6.0` will not work anymore even it requires `  spryker/symfony (^3.0.0)`

**Comment by tvaleriy** [comment]
Thank you for the feedback. We are on this Symfony update already. I will notify when it is fixed.

**Comment by tvaleriy** [comment]
I'm closing it as not relevant anymore.
