### ISSUE TITLE
getKeySuggestions uses mysql EQUAL instead of LIKE

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#176]
This is a

* [x] bug
* [ ] enhancement

spryker/glossary                     3.3.3
spryker/shipment                     6.2.2

the shipment carrier form has a ajax field to get a glossary key. This uses the `KeyManager:getKeySuggestions()` function which puts '%' around the search phrase but in `queryActiveKeysByName` the function `filterByKey` is used instead of `filterByKey_Like`.
Therefore the ajax field in shipment form will never become a result.

**Why is this form field `glossaryKeyName` there anyway? I don't see any usage of this value when saving?**

**Comment by tvaleriy** [comment]
Thank you for the feedback. It is in our backlog now. I will notify when the status is changed.

**Comment by tvaleriy** [comment]
Hi @AndromedaXP. This should be fixed already in:
https://github.com/spryker/glossary/releases/tag/3.3.4
https://github.com/spryker/shipment/releases/tag/6.4.2

Sorry for the delay.
