### ISSUE TITLE
saveTouchRecord() tries to change item_event and fails because of duplicate DB entries

### ISSUE THREAD

**Issue by mruoss** [spryker/support#177]
This is a

* [x] bug
* [ ] enhancement

Let's assume you have only the following two entries in `spy_touch`:

**id_touch** | **item_type** | **item_event** | **item_id** | **touched** 
------- | ------- | ------- | ------- | -------
1 | category | deleted | 1 | _some timestamp_ 
1 | category | active | 1 | _some timestamp_ 

Now upon touchActive the function `saveTouchRecord` of class `Spryker\Zed\Touch\Business\Model\TouchRecord` is called with values `saveTouchRecord('category', 'active', 1);`.

The code on [line 84](https://github.com/spryker/touch/blob/master/src/Spryker/Zed/Touch/Business/Model/TouchRecord.php#L84) will first try to find a touch entry by **item_type** and **item_id**. It will find both records above but returns the first record (where `item_event` is `deleted`). On line 90 the record is overwritten with the new values passed to the function. This results in changing the item_event from `deleted` to `active`. However, the database will not allow to have two rows for the same item with the same item_type => duplicate entry.

To me it seems the call to `queryUpdateTouchEntry()` on [line 84](https://github.com/spryker/touch/blob/master/src/Spryker/Zed/Touch/Business/Model/TouchRecord.php#L84) should also filter by item_event, not only item_type and id. 

Thanks,
Michael

**Comment by tvaleriy** [comment]
Thank you for the feedback. I will notify when it is fixed and released.

**Comment by mruoss** [comment]
Actually, after having a second look at the code, we're not totally sure about what's the bug here. The main question is: Is the assumption in the bug report above (a table with two entries for the same item) okay? Or should there always only be one entry, either active, inactive or deleted? If that is the case, the DB schema should be improved. Currently we have a unique constraint that looks like this:

```xml
        <unique name="spy_touch-unique-item_id">
            <unique-column name="item_id"/>
            <unique-column name="item_event"/>
            <unique-column name="item_type"/>
        </unique>
```
If there should only be one record per item, `item_event` should not occur in the constraint:

```xml
        <unique name="spy_touch-unique-item_id">
            <unique-column name="item_id"/>
            <unique-column name="item_type"/>
        </unique>
```

**Comment by tvaleriy** [comment]
Hi @mruoss, finally should be fixed in https://github.com/spryker/touch/releases/tag/4.0.2 and https://github.com/spryker/product/releases/tag/6.8.2.
