### ISSUE TITLE
Wrong use statement in Aws3v3AdapterBuilder of spryker/flysystem-aws3v3-file-system

### ISSUE THREAD

**Issue by bazoo0815** [spryker/support#180]
This is a

* [x] bug

In the Aws3v3AdapterBuilder of the bundle `spryker/flysystem-aws3v3-file-system` (v1.0.1), there seems to be a wrong use statement in line 12.
```
use League\Flysystem\Adapter\AwsS3v3\AwsS3Adapter;
```
has to be 
```
use League\Flysystem\AwsS3v3\AwsS3Adapter;
```

The same wrong namespace is used in line 23.

https://github.com/spryker/flysystem-aws3v3-file-system/blob/ab906166c9f09f8cc873f18410fba28a1b6a76a8/src/Spryker/Service/FlysystemAws3v3FileSystem/Model/Builder/Adapter/Aws3v3AdapterBuilder.php#L12

**Comment by tvaleriy** [comment]
Thank you for the feedback. It should be fixed soon.

**Comment by tvaleriy** [comment]
@bazoo0815 It is fixed in https://github.com/spryker/flysystem-aws3v3-file-system/releases/tag/1.0.2 .

**Comment by bazoo0815** [comment]
thx a lot
