### ISSUE TITLE
Compatibility to PHP 7.2

### ISSUE THREAD

**Issue by mruoss** [spryker/support#182]
This is a

* [x] bug

With your last update you state that Spryker OS is now compatible with PHP 7.2. However, the bundle spryker/guzzle still depends on guzzle/guzzle:~6.2.1 and guzzle is compatible with PHP 7.2 starting with 6.3.0. Could you please update this dependency?

The error that occurs:
```
ErrorException - count(): Parameter must be an array or an object that implements Countable
in /u01/git_repos/jmb-www/spryker/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php (67)
```

Commit on guzzle/guzzle: https://github.com/guzzle/guzzle/commit/375c01b636cbbe967d4b180628abdf94c0b9070f

**Comment by tvaleriy** [comment]
Hi @mruoss . Thank you for the feedback. We are on it. I will notify when it is fixed.

**Comment by dereuromark** [comment]
This module is not used in core anymore. In what Spryker class are you still using it?
Otherwise please just remove this module from your dependency list and directly use Guzzle in the version you need.

**Comment by mruoss** [comment]
How about spryker/zed-request? It depends on spryker/guzzle

**Comment by dereuromark** [comment]
True. That should be a rather BC upgrade then, hopefully.

**Comment by mruoss** [comment]
Hopefully. I'm testing with this in my composer.json for now:

`"guzzlehttp/guzzle": "6.3.0 as 6.2.3"`

**Comment by dereuromark** [comment]
We checked the compatibility and released https://github.com/spryker/guzzle/releases/tag/2.2.0
Thank you for reaching out.
