### ISSUE TITLE
Developer VM fails acceptance codeception tests

### ISSUE THREAD

**Issue by alexbiddle** [spryker/support#183]
This is a

* [x] bug
* [ ] enhancement

Please provide the exact versions of the modules involved (see composer.lock file).
Latest developer VM.

### What you did
Installed the devvm.
`./setup_test -f`
`codecept run`

### Actual Behavior
Multiple test failures

### Expected Behavior
All tests green

**Comment by tvaleriy** [comment]
Hi @alexbiddle. Thank you for the feedback. Could you please clarify exact version of the devvm you are using? v2.0.0?

**Comment by alexbiddle** [comment]
I'm following your instructions here: https://academy.spryker.com/getting_started/installation_guide.html

So I assume  devvm1.0.4

**Comment by tvaleriy** [comment]
Ok, thanks. I will check both then: 1.0.4 and 2.0.0.

**Comment by alexbiddle** [comment]
Thank you very much. Is 2.0.0 the recommended VM now?

**Comment by tvaleriy** [comment]
It is released already. https://github.com/spryker/devvm/releases/tag/v2.0.0
Though I'm not sure that it is recommended already.

> This DevVM release includes major Elasticsearch upgrade from version 2.x to 5.x. Those are not compatible. Your Spryker code needs to handle new Elasticsearch properly and the underlaying library (ruflin/Elastica) must be set to proper version (5.x).

**Comment by alexbiddle** [comment]
Can you confirm that the test failures on the VM is a spryker issue--or is there some piece of configuration I am missing?

**Comment by tvaleriy** [comment]
Hi @alexbiddle. Sorry for the late reply. I have checked different combinations. So this is definitely an issue in Spryker. But this is an old script. We are using now new scripts. So the recommended approach is: install new devvm -> `vendor/bin/install -r testing` -> `codecept run`.

Regarding problems about an old `./setup_test -f` script I will create a ticket and will notify how and when it will be fixed.

**Comment by alexbiddle** [comment]
This ticket can be closed. I ran all the tests using the latest VM and they seem to be OK now.

```Time: 11.53 minutes, Memory: 38.00MB

OK, but incomplete, skipped, or risky tests!
Tests: 122, Assertions: 310, Skipped: 17.```
