### ISSUE TITLE
Gross Price and NetPrice Table is missing in Discount Module | Error on update

### ISSUE THREAD

**Issue by egobude** [spryker/support#184]
This is a

* [X] bug
* [ ] enhancement

Please provide the exact versions of the modules involved (see composer.lock file).

```
"name": "spryker/discount",
"version": "6.1.0",
"reference": "ae978bc07c0a73530195d0cf19bbd2543f32aece"
```

### What you did

I have created a new discount in the discount module. 

### Actual Behavior

When i try to update the discount the Gross Price and NetPrice Table is missing. On save i get the following error message: 

```
SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "spy_discount_amount-unique-currency-discount"\n
DETAIL:  Key (fk_currency, fk_discount)=(93, 46) already exists.\n
```

### Expected Behavior

The Gross Price and NetPrice Table should be visible in edit mode. There should be not error on update.

**Comment by aurisl** [comment]
Can you please give us  more information how did you get to that point? We did testing in latest demoshop and it seems to be working correctly.  Could you please check if it's saved in `spy_discount_amount` database table?  Have you created using ZED UI?

**Comment by egobude** [comment]
Hi @aurisl,

yes i have created the discounts with the ZED UI. The discounts are stored in the table `spy_discount_amount` on initial save but on update i get the mysql error.

**Comment by tvaleriy** [comment]
Hi @egobude. So we have tried to reproduce this issue several times (with Postgres, with Mysql) but we couldn't. It works ok with latest master branch of the demoshop repo.
Maybe you can share more details? Some steps to reproduce? Is it a project or just clean demoshop?

**Comment by egobude** [comment]
Hi @aurisl @tvaleriy,

i have found the error. The problem was a custom template which we had overridden in PYZ. 

Sorry for the noise and thanks for helping :)
