### ISSUE TITLE
session redis constants are mandatory

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#185]
This is a

* [x] bug
* [ ] enhancement

spryker/session 3.2.4.

### What you did
setting session save handler to file in config
```$config[SessionConstants::ZED_SESSION_SAVE_HANDLER] = SessionConstants::SESSION_HANDLER_FILE;```

### Actual Behavior
getting error that
```$config[SessionConstants::ZED_SESSION_REDIS_PROTOCOL]
$config[SessionConstants::ZED_SESSION_REDIS_HOST]
$config[SessionConstants::ZED_SESSION_REDIS_PORT]
```
is missing.

### Expected Behavior
if I don't have/use a redis, why should I configure it?

**Comment by tvaleriy** [comment]
I've moved this ticket here - https://spryker.ideas.aha.io/ideas/CUSTIDEAS-I-40. You can track the progress there.
I'm closing this ticket here.
