### ISSUE TITLE
Date fields have the format Y-m-d H:i:s.u instead of Y-m-d

### ISSUE THREAD

**Issue by mruoss** [spryker/support#186]
This is a

* [x] bug
* [ ] enhancement

Hi there

In this [commit](https://github.com/spryker/propel-orm/commit/02529b70bcfc925fe43c25bf557ee4095b15a7c7) you overwrite propel's ObjectBuilder. Now all fields, no matter whether they are of type DATE, TIMESTAMP or TIME are formatted as 'Y-m-d H:i:s.u' when calling `->toArray()` on the object.
This is especially bad if you use it like this `$customerTransfer->fromArray($customerEntity->toArray());`. `$customerTransfer->getDateOfBirth()` now returns `2018-01-01 00:00:00.000000` instead of `2018-01-01`.

This is a quite crucial bug to our project as we use this field with external providers. What was the reason for changing this? And would it make sense to use the function `ObjectBuilder::getTemporalFormatter(Column $column)` to get the correct format? (just a guess).

Thanks,
Michael

**Comment by stereomon** [comment]
Hello,

we have reviewed the changes we made. In previous versions the behavior was exactly the same. The only difference here is that we use in `toArray()` and in the setter the same formatting. Previously the one method used `->format('Y-m-d H:i:s.u')` and the other one used `->format('c')`.

This leads to the problem that all entities always marked as modified although they weren't.

All temporal field types are converted to DateTime as you can see in the `@var` annotation of your entity properties. 

You can set the default format's for all temporal fields types in your config_propel.php

E.g.:

```
'generator' => [
        ...
        'dateTime' => [
            'defaultTimeFormat' => '...',
            'defaultDateFormat' => '...',
            'defaultTimeStampFormat' => '...',
        ],
        ...
],
```

**Comment by mruoss** [comment]
Oh... just found your ticket https://github.com/propelorm/Propel2/issues/1459.
Will add my proposal also there.

**Comment by dereuromark** [comment]
In the meantime we could probably shim it then in our side.

**Comment by dereuromark** [comment]
Resolved with https://github.com/spryker/propel-orm/releases/tag/1.6.2
