### ISSUE TITLE
Deleting Documents From Elasticsearch Results in Error

### ISSUE THREAD

**Issue by ThomasKuehnel** [spryker/support#187]
This is a

* [x] bug

Please provide the exact versions of the modules involved (see composer.lock file).
`spryker/search 8.0.0`

### What you did
Calling `\Spryker\Client\Search\SearchClient::delete()` to remove a document from Elasticsearch

### Actual Behavior
Deletion fails with the following error:
```
Fatal error: Uncaught TypeError: Argument 1 passed to Elastica\Index::flush() must be of the type array, boolean given, called in /var/www/vendor/spryker/search/src/Spryker/Client/Search/Model/Elasticsearch/Writer/Writer.php on line 118 and defined in /var/www/vendor/ruflin/elastica/lib/Elastica/Index.php on line 508

TypeError: Argument 1 passed to Elastica\Index::flush() must be of the type array, boolean given, called in /var/www/vendor/spryker/search/src/Spryker/Client/Search/Model/Elasticsearch/Writer/Writer.php on line 118 in /var/www/vendor/ruflin/elastica/lib/Elastica/Index.php on line 508
```

### Expected Behavior
Document(s) get deleted from Elasticsearch

It seem like the method signature of `\Elastica\Index::flush()` changed (https://github.com/ruflin/Elastica/blob/5.3.1/lib/Elastica/Index.php#L508) with the recent update of _Elastica_ and the call in https://github.com/spryker/search/blob/master/src/Spryker/Client/Search/Model/Elasticsearch/Writer/Writer.php#L118 is not valid any more.

**Comment by tvaleriy** [comment]
Hey Thomas! Thank you for the feedback. Ticket is created. I will notify when it is fixed and released.

**Comment by tvaleriy** [comment]
Hey @ThomasKuehnel. It is fixed and released. Thanks for the report!
https://github.com/spryker/collector/releases/tag/6.1.5
https://github.com/spryker/search/releases/tag/8.0.1

**Comment by ThomasKuehnel** [comment]
Great! Thanks for the quick support 👍
