### ISSUE TITLE
ACL bundle is not compatible with Symfony 3

### ISSUE THREAD

**Issue by mruoss** [spryker/support#188]
This is a

* [x] bug
* [ ] enhancement

The field "Assigned Roles" on the "Edit Group" page of the ACL bundle seems to be broken. The choices array passed to the form field of type `Select2ComboBoxType` are passed inversed (see the infos and warnings on the [2.8 docs](https://symfony.com/doc/2.8/reference/forms/types/choice.html#choices-as-values)).

```php
[
1 => 'role 1',
2 => 'role 2',
]
```
Symfony 3 requires the choices to be passed inversed:

```php
[
'role 1' => 1,
'role 2' => 2,
]
```

**Comment by mruoss** [comment]
Swapping the values on [this line](https://github.com/spryker/acl/blob/7813f91a42ed22a674c951619e168315afddd353/src/Spryker/Zed/Acl/Communication/Form/DataProvider/AclGroupFormDataProvider.php#L78) fixes it for me.

**Comment by tvaleriy** [comment]
Hi @mruoss. Thank you for the report. It is already known issue. I will notify when it is released.

**Comment by cfladerer** [comment]
When will the fix for the bug be released?

**Comment by tvaleriy** [comment]
Hi @cfladerer. Should be fixed soon enough. We are working on it now.

**Comment by dereuromark** [comment]
Resolved with https://github.com/spryker/acl/releases/tag/3.0.8
