### ISSUE TITLE
redundant field fk_category_template in spy_cms_block_category_connector

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#189]
This is a

* [ ] bug
* [ ] enhancement

spryker/category                     4.3.3    
spryker/cms                          6.4.3           
spryker/cms-block                    2.0.0
spryker/cms-block-category-connector 2.1.4 

### What you did
When looking at the database, table spy_cms_block_category_connector has a field fk_category_template, which is a copy of fk_category_template from spy_category.
There is no chance in forms that these fields can differ, then why having this redundant field in database anyway?

**Comment by tvaleriy** [comment]
Hi @AndromedaXP. Thank you for the feedback. We need to investigate this. Maybe there are different usages.
If this an issue then it has to wait until next major release among with others things.

**Comment by PhilinTv** [comment]
@AndromedaXP 
Spryker CMS Block Category Connector module allows you to have a set of CMS blocks assigned per Category per Category template. So basically you could have block1 and block2 with a template1 and block3 with a template2 on the same category page. 

It's a helpful feature when you want to set up a new look for your category for a while (during a marketing campaign), then return to a regular template and not lose CMS blocks on it.

**Comment by AndromedaXP** [comment]
But I don't see any possibility in the forms to input your described situation. I have text fields per position and I can add there categories with autocompletion, the template is then used from the category.

**Comment by PhilinTv** [comment]
Hi @AndromedaXP,

Probably you don't have a good use case to check it. To reproduce it I would suggest following the described above scenario. 
First, choose Template #1, assign a couple of CMS blocks, Block #1 and Block #2. Save the result. 
Then let's improvise and make a marketing campaign: switch your template to Template #2 and assign CMS Block #3. Save the result. Now switch back to Template #1 and find that previously assigned CMS blocks are in place: Block #1 and Block #2. Now each time you will switch a template for a category, CMS blocks will be still assigned to each template in a different way.

**Comment by AndromedaXP** [comment]
If a connect a category and block, change the template of the category then the block will not be shown on category form neither the category on the block form, but in database they are still connected. I don't feel this is a desired behaviour....

**Comment by PhilinTv** [comment]
@AndromedaXP did you apply modifications to CMS Block/CMS Block Category Connector, Category modules?

@tvaleriy could you confirm with our public Demoshop the described behavior? If it's not true, it's a bugfix ticket. Thank you!

**Comment by tvaleriy** [comment]
Hi @AndromedaXP. I've checked described behaviour. I can confirm it but it is working as supposed.

If the block is assigned to the category's template 1 but the active template at the moment is template 2, then this connection won't be shown at the block's edit page.

Or I misunderstood something in your message?

**Comment by AndromedaXP** [comment]
Exactly and the same on the category edit page

**Comment by tvaleriy** [comment]
So, in our opinion, it is working as it should.
I'm closing this ticket now. Please feel free to re-open it if you have further questions.

**Comment by AndromedaXP** [comment]
I don't understand that missing data not shown on a form is a desired behaviour?
I can not see the connection, I cannot edit it, I cannot delete it, with which intention?
