### ISSUE TITLE
resetPassword email not possible in zed

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#190]
This is a

* [x] bug
* [ ] enhancement

spryker/auth                           3.0.2
spryker/mail                                4.0.2 

### What you did
function AuthDependencyProvider:getPasswordResetNotificationSender wants to return `\Spryker\Zed\Auth\Dependency\Plugin\AuthPasswordResetSenderInterface`. This interface method `send` returns a `SendMailResponsesTransfer` which was removed from mail bundle.
In which way can I then send a resetPassword email?
Why is this feature not even implemented in demoshop?

**Comment by AndromedaXP** [comment]
Btw: spryker/auth-mail-connector requires spryker/mail ^4.0 but the same problem, a MailTransfer object is used which is not available anymore

**Comment by tvaleriy** [comment]
Hi @AndromedaXP. Thank you for the feedback. We are going to fix this. I will notify when it is released.

**Comment by AndromedaXP** [comment]
And even the spryker/mail bundle doesn't require any version of swiftmailer... how can this work then?

**Comment by stereomon** [comment]
The mail bundle does not require anything and it would not make any sense to require something here as every project makes use of a different provider. 

As everywhere in Spryker we also make use of Plugins here and plugins are optional. Thats why there is a only a suggest to swiftmailer in the module's composer.json and not a require.

**Comment by AndromedaXP** [comment]
MailDependencyProvider::addMailer will throw an exception when class Swift_Message is not known

**Comment by AndromedaXP** [comment]
...and ResetPasswordForm from spryker/auth v3.0.2 is not even symfony3 compatible by having `'type' => 'password'` :(

**Comment by stereomon** [comment]
When you get the demoshop, SwiftMailer is required in the "projects" composer.json and you can start developing your mails. If you start without a demoshop you will need to add this dependency on your own, if you want to use the swiftmailer. If you don't want to use swiftmailer you will need to change the `MailBusinessFactory::createMailer()` method anyway. 

About SF3, we know about this topic and we are already working on this. Thanks fopr the hint.

**Comment by AndromedaXP** [comment]
but this is a BC break! you demoshop should not work at all.
current "spryker/symfony": "^3.0.0" bundle (in demoshop!) uses symfony/form v3. How can this incompatible form then work?!

**Comment by tvaleriy** [comment]
https://github.com/spryker/auth/releases/tag/3.0.3 fixed 'type' => 'password'.
I'm closing the issue.
