### ISSUE TITLE
Multiselect Product Attributes

### ISSUE THREAD

**Issue by gengjozsef** [spryker/support#191]
This is a

* [ ] bug
* [x] enhancement

### What you did
At the moment there is no support for multiselect product attributes. 

For example i have the attribute “Colors” which has the following options: Red, Green, Blue. The attribute is not a super attribute. A product can have more the one of the values, for example Product X for the colors has the values: Red and Blue.

**Comment by tvaleriy** [comment]
Thank you for your feedback.
It is in our backlog now.
But, unfortunately, I can't tell you at the moment when it can be implemented.

**Comment by qwe2003** [comment]
@gengjozsef did you find an solution till the spryker guys update the module?

**Comment by gengjozsef** [comment]
Hi @qwe2003 ,

we solved it with the help of the  Text Type.

**Comment by tvaleriy** [comment]
I've moved this ticket here - https://spryker.ideas.aha.io/ideas/CUSTIDEAS-I-11. You can track the progress there.
I'm closing this ticket here.
