### ISSUE TITLE
Empty Elastica auth header causes basic auth

### ISSUE THREAD

**Issue by NilsEvers** [spryker/support#192]
If the application configuration has an defined entry for  `SearchConstants::ELASTICA_PARAMETER__AUTH_HEADER` this will set the authorisation to basic, even though it is set to false or an empty string.

The condition in [AbstractSearchClientProvider:44](https://github.com/spryker/search/blob/007cbdc53f55a909268008c215ed823575679209/src/Spryker/Shared/Search/Provider/AbstractSearchClientProvider.php#L44) isn't sufficient enough.

**Comment by tvaleriy** [comment]
Hi @NilsEvers. Thank you for the feedback. It is in our backlog now, but isn't prioritised yet.
I will notify when this is changed and released.

**Comment by tvaleriy** [comment]
I've moved this ticket here - https://spryker.ideas.aha.io/ideas/CUSTIDEAS-I-38. You can track the progress there.
I'm closing this ticket here.

**Comment by tvaleriy** [comment]
https://api.release.spryker.com/release-group/3284
