### ISSUE TITLE
IDE auto complete generation is broken

### ISSUE THREAD

**Issue by mruoss** [spryker/support#193]
This is a

* [x] bug
* [ ] enhancemen

Currently our IDE autocomplete generator produces empty files.

In [this commit](https://github.com/spryker/development/commit/18fc26e9eb3eb85d0375e68186fe88ac65283d07#diff-11cfa3934be039d7b864fe6f02996ff6) in the function `getSearchDirectory()` you changed the format in sprintf from `'%s/*/Business/'` to `'%s%s/Business/'`. In our setup there's a missing slash between the path and the file name. [SplFileInfo::getPath()](http://php.net/manual/de/splfileinfo.getpath.php) returns the path without a trailing slash, so the format for `sprintf` should be `'%s/%s/Business/'`.

**Comment by dereuromark** [comment]
We are actually trying to always use paths with a trailing separator as consistent and clean path handling.
There seems to be indeed some small regression here that we will fix ASAP.
We will let you know once it is released.

**Comment by dereuromark** [comment]
Further analysis shows that Symfony Finder 2.x recently changed their path returns in a BC breaking way in a patch release that triggers this regression.
We will now have to intervene and make sure the paths on our end are all properly trailing slash appended.

**Comment by mruoss** [comment]
Oh I see. That's unfortunate. But thanks for the update.

**Comment by dereuromark** [comment]
Resolved with https://github.com/spryker/development/releases/tag/3.7.1
