### ISSUE TITLE
Incorrect installation instructions for Spryker B2B suite

### ISSUE THREAD

**Issue by alexbiddle** [spryker/support#195]
This is a

* [x] bug
* [ ] enhancement

### What you did

Follow the installation instructions on https://github.com/spryker-shop/suite-b2b

`vagrant up run VM_PROJECT=suite SPRYKER_REPOSITORY="git@github.com:spryker-shop/suite.git" vagrant up.`

### Actual Behavior
It uses, naturally `git@github.com:spryker-shop/suite.git` instead of `git@github.com:spryker-shop/suite-b2b.git`

### Expected Behavior
It uses `git@github.com:spryker-shop/suite-b2b.git`

The documentation appears incorrect.

**Comment by tvaleriy** [comment]
Hi @alexbiddle. Thank you for the feedback. And sorry for the inconvenience, but at the moment this repository isn't ready yet. We are making it "private" until it is ready.
Please use https://github.com/spryker-shop/suite instead.
