### ISSUE TITLE
Spryker Suite B2B does not install 

### ISSUE THREAD

**Issue by alexbiddle** [spryker/support#196]
This is a

* [x] bug
* [ ] enhancement

For questions please consult the [Spryker Forum](http://discuss.spryker.com/).

Please provide the exact versions of the modules involved (see composer.lock file).

### What you did
`VM_PROJECT=suite-b2b SPRYKER_REPOSITORY="git@github.com:spryker-shop/suite-b2b.git" vagrant up`
`composer install`
`vendor/bin/install -r testing`

### Expected Behavior
Yves is installed correctly.

### Actual Behavior
```Build Yves frontend

> spryker-suite-b2b@1.0.0 yves /data/shop/development/current
> node ./node_modules/@spryker/shop-ui-builder/tasks/build

Scanning for components...
Spryker: 33 found
Project: 0 found
Building...
/data/shop/development/current/node_modules/webpack/lib/webpack.js:19
		throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
		^

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'mode'. These properties are valid:
```

**Comment by tvaleriy** [comment]
Hi @alexbiddle. Thank you for the feedback. And sorry for the inconvenience, but at the moment this repository isn't ready yet. We are making it "private" until it is ready.
Please use https://github.com/spryker-shop/suite instead.

**Comment by alexbiddle** [comment]
What is the difference between suite and demoshop? 

Does the suite still contain a `Users` table?

**Comment by tvaleriy** [comment]
@alexbiddle Demoshop (https://github.com/spryker/demoshop) is an example of B2C solution. Suite repository (https://github.com/spryker-shop/suite) is an example of B2B solution.
Table spy_user is presented in both example solutions.
