### ISSUE TITLE
CategoryToTouchBridge calls undefined TouchFacadeInterface::bulkTouchActive()

### ISSUE THREAD

**Issue by mruoss** [spryker/support#198]
This is a

* [x] bug
* [ ] enhancement

The newest version of Category bundle is compatible with Touch version ^4.0.0 but the `CategoryToTouchBridge` calls an undefined method `bulkTouchActive()` on the `TouchFacade`.

**Comment by dereuromark** [comment]
Indeed, the method has been removed in favor of bulkTouchSetActive().
The bridge should forward here properly to that Facade interface method.

**Comment by dereuromark** [comment]
Fixed in https://github.com/spryker/category/releases/tag/4.4.1

**Comment by mruoss** [comment]
Thanks @dereuromark.
What's still a bit problematic: The `CategoryToTouchInterface` does not correlate with the `TouchFacadeInterface`. We currently have to extend the Category `TouchFacadeInterface` in our `TouchFacade`. Now we have to implement these two old functions in our `TouchFacade`...

**Comment by dereuromark** [comment]
How do they cause a problem here?
Are you using the bridge on project level, as well?
Maybe you can elaborate on the issue you are facing.

**Comment by mruoss** [comment]
Sure. We're not using the bridge. The following is the case:
* We are overwriting the `TouchFacade` in project space - obviousely with its interface
* We overwrite the `CategoryDependencyProvider` to return the `TouchFacade` in the project space instead of the `CategoryToTouchBridge`
* The core models still require a `CategoryToTouchInterface` to be passed, that's why my `TouchFacadeInterface` extends `CategoryToTouchInterface`.
* `CategoryToTouchInterface` defines two functions `bulkTouchActive()` and `bulkTouchInactive()` which are not implemented in the `TouchFacade` of the core bundle anymore.
* We are forced to implement the two functions in the `TouchFacade` in project space 

=> It's not a big deal, I can just define the two methods in the `TouchFacade` and forward the calls - it's just not very nice.
