### ISSUE TITLE
AbstractTable lost data on each request

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#200]
This is a

* [x] bug
* [ ] enhancement

spryker/gui                          3.13.1

### What you did
Changing the page/sorting/search on a table in backend. When reloading the page all these inputs are gone because the table identifier is set random on every request.
This identifier should rely on the table data, so the local storage is used to reset the table to the last status and page/sorting/search is kept.

**Comment by tvaleriy** [comment]
Thank you for the feedback.
I will notify when it is fixed.

**Comment by tvaleriy** [comment]
Should be fixed in https://github.com/spryker/gui/releases/tag/3.18.0.

**Comment by darius-telycenas** [comment]
That was fast…
