### ISSUE TITLE
CmsBlockGlossaryWriter touches inactive blocks

### ISSUE THREAD

**Issue by mruoss** [spryker/support#201]
This is a

* [x] bug
* [ ] enhancement

If you save placeholders of a block, the block gets touched (touchActive) even if it is inactive. This happens in the [`CmsBLockGlossaryWriter`](https://github.com/spryker/cms-block/blob/master/src/Spryker/Zed/CmsBlock/Business/Model/CmsBlockGlossaryWriter.php#L127)

**Comment by dereuromark** [comment]
Fixed in https://github.com/spryker/cms-block/releases/tag/2.1.1
