### ISSUE TITLE
Unnecessary database queries

### ISSUE THREAD

**Issue by egobude** [spryker/support#203]
This is a

* [ X ] bug
* [ X ] enhancement

Please provide the exact versions of the modules involved (see composer.lock file).

`spryker/gui:3.13.1`

### What you did

I'm in the backend on the customer overview page and i'm searching for a customer. 

### Actual Behavior

Currently the search functionality generates a request for each letter that you type into the search field. This generates a lot of database load on the server if you have a big database.

### Expected Behavior

It would be better if the search would send the request with a delay. 

I think the problem is the throttle method `spryker-zed-gui-commons.js:32030`. The method could be optimized as follows:

```
throttle: function ( fn, freq ) {
    var
        frequency = freq !== undefined ? freq : 200,
        timer;

    return function () {
        var
            that = this,
            args = arguments;

        clearTimeout( timer );
        timer = setTimeout( function () {
            fn.apply( that, args );
        }, frequency );
    };
},
```

**Comment by tvaleriy** [comment]
Thank you for the feedback. It is in our backlog. I will notify when it is fixed.

**Comment by tvaleriy** [comment]
Hi @egobude, this should be fixed in https://github.com/spryker/category/releases/tag/4.12.1, https://github.com/spryker/gui/releases/tag/3.16.3 and https://github.com/spryker/product-category-filter-gui/releases/tag/1.1.10.
