### ISSUE TITLE
unresolvable.cache cannot be accessed

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#204]
This is a

* [x] bug
* [ ] enhancement

spryker/kernel                              3.20.0

### What you did
After running cache:empty-all the next request (maybe also a timing issue) results in an error in Spryker\Shared\Kernel\ClassResolver\Cache\Storage\File.php because it wants file_put_contents into /data/STORE/cache/YVES/unresolvable.cache but the directory YVES was just deleted from clearing cache and there is no check if this directory exists

**Comment by tvaleriy** [comment]
Hi @AndromedaXP. Could you please clarify what type of requests you are referring to? Just some navigation in Yves?
I mean that I wasn't able to reproduce mentioned issue.
I'm not saying that there is no issue or nothing to fix.
But I'm curious if this reproducible at all.

**Comment by AndromedaXP** [comment]
Hi,
We just saw the ErrorException on NewRelic with an ajax request. There is a try catch block so normally this should not happen, but anyways, even its no Exception but a logging the unresolvable.cache file will not be created. We added a funktion before the file_put_contents
`    /**
     * @param string $dir
     *
     * @throws \Exception
     *
     * @return void
     */
    private function ensureExistingDirectory($dir)
    {
        if (!file_exists($dir)) {
            mkdir($dir, 0777, true);
            
            return;
        }

        if (!is_dir($dir)) {
            throw new Exception('Expected ' . $dir . ' to be a directory, but it is not');
        }
    }`

**Comment by tvaleriy** [comment]
Still I wasn't able to reproduce it while simulating prod env with load testing.
But I've created a ticket for developers to check.

Thank you for the feedback.

**Comment by a-sabaa** [comment]
Hello, this ticket will be closed due to lack of reproducible steps. We tried to reproduce locally but we were unable to, an adhoc "blind" solution was added to Kernel but it would have a big impact on request handling performance so it was scrapped.
