### ISSUE TITLE
Zed API: (potential) logging of sensitive data included in ApiRequestTransfer

### ISSUE THREAD

**Issue by bazoo0815** [spryker/support#208]
This is a

* [x] bug

Using:
- spryker/api 0.1.3

There is a security issue in the `ApiControllerListenerPlugin` of the Zed API which we consider a serious one.

The `ApiRequestTransfer` object is populated with all data of the PHP `$_SERVER` array:
```
        $serverData = $request->server->all();
        $requestTransfer->setServerData($serverData);
```
(see https://github.com/spryker/api/blob/e619ad390ac6d32cd8c89938a25455fd10933e1a/src/Spryker/Zed/Api/Communication/Plugin/ApiControllerListenerPlugin.php#L119-L120)

This includes all environmental variables. In our case it includes credentials e.g. for database user/pw, external services etc, because we are running Spryker in a Docker environment on a Kubernetes cluster where providing credentials via env vars is the common way to do this.

By default, all API requests are logged, including a JSON encoded dump of the whole `ApiRequestTransfer` object (see https://github.com/spryker/api/blob/1d657432086e5dbc5aed24ede75cdf6b98669bb4/src/Spryker/Zed/Api/Communication/Plugin/ApiControllerListenerPlugin.php#L142).
So all sensitive data provided via env vars is either written to a log file or - in our case - streamed to an external logging service and therefore externally exposed.

So the `ApiRequestTransfer` should not be so 'verbose'.

This problem exists in any version of the API module.

We fixed this issue temporarily by adding a whitelisting for server variables:

```
<?php
declare(strict_types = 1);

namespace Pyz\Zed\Api\Communication\Plugin;

use Generated\Shared\Transfer\ApiRequestTransfer;
use Spryker\Zed\Api\Communication\Plugin\ApiControllerListenerPlugin as SprykerApiControllerListenerPlugin;
use Symfony\Component\HttpFoundation\Request;

/**
 * @method \Pyz\Zed\Api\Communication\ApiCommunicationFactory getFactory()
 * @method \Spryker\Zed\Api\Business\ApiFacadeInterface getFacade()
 */
class ApiControllerListenerPlugin extends SprykerApiControllerListenerPlugin
{

    /**
     * @param \Symfony\Component\HttpFoundation\Request $request
     *
     * @return \Generated\Shared\Transfer\ApiRequestTransfer
     */
    protected function getRequestTransfer(Request $request): ApiRequestTransfer
    {
        $requestTransfer = parent::getRequestTransfer($request);

        $serverData = $this->filterServerData($request->server->all());
        $requestTransfer->setServerData($serverData);

        return $requestTransfer;
    }

    /**
     * @param array $serverData
     *
     * @return array
     */
    protected function filterServerData(array $serverData): array
    {
        $allowedVariables = $this->getAllowedServerVariables();

        return array_filter($serverData, function ($key) use ($allowedVariables) {
            return \in_array($key, $allowedVariables, true);
        }, ARRAY_FILTER_USE_KEY);
    }

    /**
     * @return array
     */
    protected function getAllowedServerVariables(): array
    {
        return [
            'REQUEST_URI',
        ];
    }

}
```

**Comment by tvaleriy** [comment]
Thank you for the feedback. I will notify when it is changed/fixed.

**Comment by tvaleriy** [comment]
Hi @bazoo0815, this should be fixed in https://github.com/spryker/api/releases/tag/0.1.4. Please update.
