### ISSUE TITLE
memory limit exhausted in OrderItemMatrix in spryker/oms

### ISSUE THREAD

**Issue by msecker** [spryker/support#210]
This is a

* [x] bug
* [ ] enhancement

Used version of `spryker/oms` is 7.3.1
But I think the problem should occur even with current master

### What you did

I click on "Order Matrix" in backend to get an overview for my orders on a live system.

### Actual Behavior
I get a server error instead of an overview. Investigation told me that to many `spy_sales_order_item` were loaded from database in `Spryker\Zed\Oms\Business\Util\OrderItemMatrix.php`. The constructor of this class loads the entities from DB.  The calculation and aggregation of data is then done in PHP. So the final error is **memory limit exhausted**.
I suggest to SELECT counts() from database instead. Maybe (used) states und paymentMethods could be determined via SELECT DISTINCT and SQL filtering instead of traversing all records.

### Expected Behavior
OrderMatrix module works without long time delay and memory limit errors even if a lot of `spy_sales_order_item` exist.

If you need further information, just let me know.
Thanks!

**Comment by tvaleriy** [comment]
Hi and thank you for the valuable feedback! We need to investigate this and then I will notify when this behaviour is changed/fixed.

**Comment by tvaleriy** [comment]
This should be fixed in https://github.com/spryker/oms/releases/tag/8.6.0.
