### ISSUE TITLE
Enable TLS 1.1/1.2 support for spryker/mail

### ISSUE THREAD

**Issue by bazoo0815** [spryker/support#211]
This is a

* [x] enhancement

The current spryker/mail package only supports Swiftmailer up to version 5.4.9.
This version of Swiftmailer is only supporting TLS 1.0 for secure transport which is deprecated since 30.06.2018 (see https://en.wikipedia.org/wiki/Transport_Layer_Security#TLS_1.0).
We ran into this issue just today, because Sparkpost denies mail transport with TLS 1.0 from today on, causing our application being not able to send out emails anymore.

Support for TLS 1.1/1.2 has been added in version 6.1.0 (https://github.com/swiftmailer/swiftmailer/blob/49819a4381cf0d8dd3c811d37b9680c784d35db2/CHANGES#L29).

In order to get spryker/mail working the newer Swiftmailer version (6.1.2) I had to overwrite \Spryker\Zed\Mail\MailDependencyProvider::createMailer() on project level and modify the instantiation of Swiftmailer classes by replacing `<SwiftmailerClass>::newInstance()` with `new <SwiftmailerClass>()`:

```
 Swift_Message::newInstance()       -> new Swift_Message()
 Swift_SmtpTransport::newInstance() -> new Swift_SmtpTransport()
 Swift_Mailer::newInstance()        -> new Swift_Mailer()
```

I don't know if this modification is sufficient for the spryker/mail package as well or if more changes are required, because we only use very basic mailing functionality.

**Comment by tvaleriy** [comment]
Should be fixed in https://github.com/spryker/mail/releases/tag/4.1.0. Please update.
