### ISSUE TITLE
Wrong method signature in AvailabilityToStockInterface

### ISSUE THREAD

**Issue by senor-dingdong** [spryker/support#212]
This is a

* [x] bug
* [ ] enhancement

With availability 6.1.0 you added the method _getStockProductsByIdProduct(int $idProductConcrete)_ to _AvailabilityToStockInterface_ and _AvailabilityToStockBridge_ with a different signature than in stock facade (no typehint there), which causes problems with extending on project level.

https://github.com/spryker/availability/blob/master/src/Spryker/Zed/Availability/Dependency/Facade/AvailabilityToStockInterface.php#L69

and

https://github.com/spryker/stock/blob/master/src/Spryker/Zed/Stock/Business/StockFacadeInterface.php#L201

**Comment by tvaleriy** [comment]
Thank you for the bugreport. I will notify here when it is fixed and released.

**Comment by tvaleriy** [comment]
This should be fixed in https://github.com/spryker/availability/releases/tag/6.3.0.
