### ISSUE TITLE
Error when generating empty transfer object

### ISSUE THREAD

**Issue by dantleech** [spryker/support#215]
This is a

* [x] bug
* [ ] enhancement

```
spryker/transfer                                      3.6.2              Transfer module
```

### What you did

Generate transfer objects with a transfer that has no properties:

```
    <transfer name="MyTransfer">
    </transfer>
```

### Actual Behavior

```
$ docker-compose exec web ./vendor/bin/console transfer:generate
Store: ... | Environment: development-docker
ErrorException - Exception: Undefined index: property 
in /app/vendor/spryker/transfer/src/Spryker/Zed/Transfer/Business/Model/Generator/DefinitionNormalizer.php (34)
```

### Expected Behavior

Transfer to be generated.

**Comment by dereuromark** [comment]
This should create a more graceful error message (also in transfer:validate) and be handled more graceful/defensive, not to trigger undefined index issues.
But we so far never allowed empty transfers to be generated as they are not useful.
What is your use case here?

**Comment by tvaleriy** [comment]
Thank you for the report. I will notify when it is fixed.

**Comment by dereuromark** [comment]
Solved with https://github.com/spryker/transfer/releases/tag/3.6.4

**Comment by mattherick** [comment]
I get an error, if I call `vendor/bin/console transfer:validate` on empty transfer objects. How can this be fixed?

**Comment by dereuromark** [comment]
This was also fixed - in https://github.com/spryker/transfer/releases/tag/3.11.1

**Comment by mattherick** [comment]
Ah thx @dereuromark
