### ISSUE TITLE
Existing Category with name cannot be saved

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#218]
This is a

* [x] bug
* [ ] enhancement

spryker/category                     4.6.0

### What you did
Editing an existing category with a localized name will always result in an error.
```Category with name "xxx" already in use in this category level, please choose another one. ```
That is because the name is checked with hasFirstLevelChildrenByName if already exists but not excluding the current category.

**Comment by tvaleriy** [comment]
Thank you for the issue. Can confirm. I will notify when it is fixed and released.

**Comment by MarcBoeing** [comment]
https://github.com/spryker/category/releases/tag/4.8.0
