### ISSUE TITLE
Payone Module's Transaction Controller Falsely Loads Sales-Orders Instead Of Sales-Order-Items

### ISSUE THREAD

**Issue by ThomasKuehnel** [spryker/support#220]
This is a

* [x] bug
* [ ] enhancement

Module: `SprykerEco/Payone` version `1.3.1`

### What you did
We receive callbacks from Payone after purchases are made using prepayment payment option

### Actual Behavior
Receving callbacks from Payone results in exceptions

```
Propel\\Runtime\\Exception\\BadMethodCallException - Call to undefined method: getIdSalesOrderItem. in \"/var/www/src/Orm/Zed/Sales/Persistence/Base/SpySalesOrder.php::7162

Trace:
/var/www/vendor/spryker/oms/src/Spryker/Zed/Oms/Business/OrderStateMachine/LockedOrderStateMachine.php:183
/var/www/vendor/spryker/oms/src/Spryker/Zed/Oms/Business/OrderStateMachine/LockedOrderStateMachine.php:154
/var/www/vendor/spryker/oms/src/Spryker/Zed/Oms/Business/OrderStateMachine/LockedOrderStateMachine.php:44
/var/www/vendor/spryker/oms/src/Spryker/Zed/Oms/Business/OmsFacade.php:422
/var/www/vendor/spryker-eco/payone/src/SprykerEco/Zed/Payone/Dependency/Facade/PayoneToOmsBridge.php:37
/var/www/vendor/spryker-eco/payone/src/SprykerEco/Zed/Payone/Communication/Controller/TransactionController.php:92
/var/www/vendor/spryker-eco/payone/src/SprykerEco/Zed/Payone/Communication/Controller/TransactionController.php:66
```

### Expected Behavior
Callbacks from Payone are processed without any errors

### Hint
It looks like the query in [SprykerEco\Zed\Payone\Communication\Controller\TransactionController::triggerEventsOnSuccess()](https://github.com/spryker-eco/payone/blob/master/src/SprykerEco/Zed/Payone/Communication/Controller/TransactionController.php#L80) is not terminating a _use_ properly which results in a collection of `SpySalesOrder` being returned instead of `SpySalesOrderItem`.

**Comment by tvaleriy** [comment]
Hey Thomas! :) Thank you for the feedback. I will notify when it is fixed and released.

**Comment by ThomasKuehnel** [comment]
Hi Valeriy, do you have any news on when we might expect a release for this?

**Comment by tvaleriy** [comment]
Hi Thomas, I can't say anything useful here except that we are working on it at the moment.

**Comment by ThomasKuehnel** [comment]
Hey Valeriy, do you have any updates on this bug?

**Comment by tvaleriy** [comment]
Hi @ThomasKuehnel, the issue is in QA at the moment...

**Comment by ThomasKuehnel** [comment]
Hi Valerii, thanks for the heads up. This is great news 👍

**Comment by tvaleriy** [comment]
@ThomasKuehnel https://github.com/spryker-eco/payone/releases/tag/2.1.0.
