### ISSUE TITLE
Self-Disabling Zed users might lead to Zed without users

### ISSUE THREAD

**Issue by christianvonschassen** [spryker/support#221]
This is a

* [x ] enhancement

This suggestion was provided by developer Petar Dambovaliev in the [Spryker Forum](https://discuss.spryker.com/t/disabling-zed-users/272).

### What you did
In ZED: 
You can disable yourself, as a zed user, even if you are the only one.
This means that the system could be left without any active zed users.

### Actual Behavior
Disabling your own account is enabled.

### Expected Behavior
Disabling your own account is disabled. 

Alternative suggestion: check if ZED user is the last active one, then prevent disablement of its account.

**Comment by tvaleriy** [comment]
This should be fixed in https://github.com/spryker/user/releases/tag/3.4.0.
