### ISSUE TITLE
Bundle PriceProduct > 2.0.0 creates new prices instead of updating them

### ISSUE THREAD

**Issue by mruoss** [spryker/support#222]
This is a

* [x] bug
* [ ] enhancement

In the [PriceProductStoreWriter](https://github.com/spryker/price-product/commit/ba33b51d076e2c3b41a577322ec4b42b29650455?diff=unified#diff-c0f13118e7edf2b7934863289cf94534R87) you added a new function `findPriceProductStoreEntity` that finds the `priceProductStoreEntity` for a given price. The query however was extended by price filters `filterByNetPrice` and `filterByGrossPrice` on line 98 and 99:
```php        
return $this->priceProductQueryContainer
            ->queryPriceProductStoreByProductCurrencyStore(
                $priceProductTransfer->getIdPriceProduct(),
                $moneyValueTransfer->getFkCurrency(),
                $moneyValueTransfer->getFkStore()
            )
            ->filterByNetPrice($moneyValueTransfer->getNetAmount())
            ->filterByGrossPrice($moneyValueTransfer->getGrossAmount())
            ->findOneOrCreate();
```

[Before the change](https://github.com/spryker/price-product/commit/ba33b51d076e2c3b41a577322ec4b42b29650455?diff=unified#diff-c0f13118e7edf2b7934863289cf94534L39), the query was:

```php
$priceProduceStoreEntity = $this->priceProductQueryContainer
            ->queryPriceProductStoreByProductCurrencyStore(
                $priceProductTransfer->getIdPriceProduct(),
                $moneyValueTransfer->getFkCurrency(),
                $moneyValueTransfer->getFkStore()
            )->findOneOrCreate();
```

The added filters have a side effect: When calling `PriceProductFacade::setPriceForProduct()` with a new amount for an existing price, Spryker adds a new `priceProductStoreEntity` to the database instead of updating the existing one.

Thanks,
Michael

**Comment by tvaleriy** [comment]
Thank you for the feedback. I will notify when it's fixed and released.

**Comment by Incognito** [comment]
Hi @mruoss , I believe the migration guide you received was missing an important detail about Default Price Dimensions.

In PriceProduct 2.0.0 we introduce "Price Dimensions" which supports multiple prices for one product (for example, this is used when a customer negotiates a special price, bulk discounts, currency advantages, etc..).

This means there is a slight behavior change between 1.0 and 2.0, but we do support the previous behavior with the "Default Price Dimension". You can see a working example from another place we have an implementation of this logic in [PriceProductDataImport](https://github.com/spryker/price-product-data-import/blob/master/src/Spryker/Zed/PriceProductDataImport/Business/Model/PriceProductWriterStep.php#L80).

When a product is added to the cart the system needs to find the price which fits to the current context (Store, Currency, ....). If no price applies then the Default Price is used. It also may happen that several prices apply. In this case the lowest value is selected (See [SinglePriceProductFilterMinStrategy](https://github.com/spryker/spryker/blob/902a446b3401d592a596669d663c000c51f60526/Bundles/PriceProduct/src/Spryker/Service/PriceProduct/FilterStrategy/SinglePriceProductFilterMinStrategy.php#L14)->findOne() ).

I hope this new information help unblock your development. I'm sorry to see it was missing in the guide, we'll have that fixed.

**Comment by mruoss** [comment]
Hi @Incognito 

My problem is this: The `PriceProductFacade` defines a method `setPriceForProduct()` with the specification according to the code:

```php
/**
     * Specification:
     * - Updates existing product price entity with the newly provided data.
     * - If the price type is not defined, then the default price type will be used.
     * - The product to assign can be either concrete or abstract, depending on the provided IDs.
     * - If the product doesn't have price, it throws exception.
     * - Touches product.
*/
``` 
However, the function does not do this anymore. It does not update the existing product price entity anymore if I change the price of the entity... The reason being the problem I mentioned above. 
Or am I missing something? 

Thanks,
Michael

**Comment by matweew** [comment]
Hi @mruoss. Sorry for long response.

Yes, from v.2.0.0 behavior is changed. 
Having multiple Price Dimensions now we can't change records in `spy_price_product_store` directly, because this price could be used in another dimension (e.g. specific customer prices). And when you want to change Default Dimension prices we can't modify previous record, because it could be connected to another price dimension.

To understand how it works, please check `spy_price_product_default`. This table is maker for Default Price Dimension, when you create/update prices here `fk_price_product_store` will be modified.

So now Default Prices reader working like 
```
SELECT * FROM spy_price_product_store
INNER JOIN spy_price_product_default ON (spy_price_product_store.id_price_product_store = spy_price_product_default.fk_price_product_store)
WHERE ...
```

**Comment by tvaleriy** [comment]
I will close this ticket now. But feel free to contact us as soon as you have question.
