### ISSUE TITLE
Akeneo Module Refers To Non-Existing Plugins Of Middleware/Process

### ISSUE THREAD

**Issue by ThomasKuehnel** [spryker/support#223]
This is a

[x] bug

`spryker-eco/akeneo-pim-middleware-connector`: `1.0.0`
`spryker-middleware/process`: `1.0.1`

### What you did
After setting up data-import plugins for importing products from Akeneo, I started the import process as descibed here: https://academy.spryker.com/developing_with_spryker/industry_partner_integration/akeneo/pim-akeneo-integration.html

### Actual Behavior
After executing `vendor/bin/console middleware:process:run -p PRODUCT_IMPORT_PROCESS`, the following execption occurs:
```
Error - Exception: Class 'SprykerMiddleware\Zed\Process\Communication\Plugin\Stream\JsonRowInputStreamPlugin' not found
in /var/www/vendor/spryker-eco/akeneo-pim-middleware-connector/src/SprykerEco/Zed/AkeneoPimMiddlewareConnector/AkeneoPimMiddlewareConnectorDependencyProvider.php (541)
```

### Expected Behavior
I expect the missing plugin classes to be present

### Remarks
The plugin files referenced in 
https://github.com/spryker-eco/akeneo-pim-middleware-connector/blob/master/src/SprykerEco/Zed/AkeneoPimMiddlewareConnector/AkeneoPimMiddlewareConnectorDependencyProvider.php#L86 
are missing in the current release of `spryker-middleware/process` in 
https://github.com/spryker-middleware/process/tree/master/src/SprykerMiddleware/Zed/Process/Communication/Plugin/Stream

There seems to be an open pull request that might solve that issue:
https://github.com/spryker-middleware/process/pull/45

**Comment by tvaleriy** [comment]
Hi Thomas!
You are right. This issue will be fixed by merging that PR. Lets wait for it.

**Comment by ThomasKuehnel** [comment]
Hi Valeyi,
thank you for the quick response. Can you please give a rought ETA on when this will be released?

**Comment by tvaleriy** [comment]
I can be wrong in my estimations as all are busy with DMEXCO at the moment, but I would say that it is more likely that it can be released at the beginning of the next week.

**Comment by ThomasKuehnel** [comment]
Great, thanks

**Comment by ThomasKuehnel** [comment]
Hi Valeriy, any news on this bug?

**Comment by tvaleriy** [comment]
Thank you for pinging. :)
Mentioned PR is merged and new version is released.
https://github.com/spryker-middleware/process/releases/tag/1.1.0
Please re-open the issue if it's still actual.
