### ISSUE TITLE
[Discount] Hydrating Grouped Discounts to Order are not cumulating the total amount 

### ISSUE THREAD

**Issue by skck** [spryker/support#225]
This is a

* [x] bug
* [ ] enhancement

Involved module version:

```
spryker/discount: 6.3.0
```

### What you did

- Place an Order with an Item with a quantity of 2 and used a Voucher of 10%
- Loading the Order through SalesFacade (so hydrators are being executed)

### Actual Behavior

As soon as there is a discount on the order, order items will be split per quantity, resulting in multiple spy_sales_discount entities for the same discount.

When loading the Order and the Discount Order Hydrator Plugin is executed, it's grouping the calculated discounts by display name. This "grouping" will basically just skip adding a calculated discount with the same display name:

https://github.com/spryker/discount/blob/master/src/Spryker/Zed/Discount/Business/Persistence/DiscountOrderHydrate.php#L36

```php
        $groupedDiscounts = [];
        foreach ($salesOrderDiscounts as $salesOrderDiscountEntity) {
            $calculatedDiscountTransfer = $this->hydrateCalculatedDiscountTransfer($salesOrderDiscountEntity);

            $this->addCalculatedDiscount($orderTransfer, $salesOrderDiscountEntity, $calculatedDiscountTransfer);

            if (!isset($groupedDiscounts[$salesOrderDiscountEntity->getDisplayName()])) {
                $groupedDiscounts[$salesOrderDiscountEntity->getDisplayName()] = $calculatedDiscountTransfer;
            }

            $calculatedDiscountTransfer = $groupedDiscounts[$salesOrderDiscountEntity->getDisplayName()];

            $groupedDiscounts[$salesOrderDiscountEntity->getDisplayName()] = $calculatedDiscountTransfer;
        }
```

Given that each split order item will be discounted with 130 cents, you will get just one `CalculatedDiscountTransfer` with a `sumAmount` of `130`.  

### Expected Behavior

As calculated discounts are grouped, I expect a cumulated `sumAmount` of `260` and `quantity` of `2` or at least no grouping at all for the discounts.

Currently the information you can get from the `CalculatedDiscountTransfer` Objects will not contain correct information.

**Comment by tvaleriy** [comment]
Thank you for the feedback. We are looking into it.

**Comment by egobude** [comment]
Hey @tvaleriy, 

can confirm. I just stumbled over the same bug.

**Comment by tvaleriy** [comment]
PR is opened, it's waiting to be approved and released if everything is ok.

**Comment by tvaleriy** [comment]
Hi @skck and @egobude, this finally should be fixed in https://github.com/spryker/discount/releases/tag/7.4.1. Please update.
