### ISSUE TITLE
redundant method call in ProductOptionWidgetPlugin

### ISSUE THREAD

**Issue by lsmith77** [spryker/support#227]
This is a

* [x] bug
* [ ] enhancement

For questions please consult the [Spryker Forum](http://discuss.spryker.com/).

Please provide the exact versions of the modules involved (see composer.lock file).

1.0.0

https://github.com/spryker-shop/product-option-widget/blob/1.0.0/src/SprykerShop/Yves/ProductOptionWidget/Plugin/ProductDetailPage/ProductOptionWidgetPlugin.php#L58

### Actual Behavior

```
        $productAbstractOptionStorageTransfer = $this->getStorageProductOptionGroupCollectionTransfer($productViewTransfer);
        if (!$productAbstractOptionStorageTransfer) {
            return new ArrayObject();
        }

        return $this->getStorageProductOptionGroupCollectionTransfer($productViewTransfer)->getProductOptionGroups();
```

### Expected Behavior

```
        $productAbstractOptionStorageTransfer = $this->getStorageProductOptionGroupCollectionTransfer($productViewTransfer);
        if (!$productAbstractOptionStorageTransfer) {
            return new ArrayObject();
        }

        return productAbstractOptionStorageTransfer->getProductOptionGroups();
```

**Comment by dereuromark** [comment]
Do you consider this a bug? It seems that this is just an optimization, as the result is the same in both cases, just slightly overhead to re-call the method.

**Comment by dereuromark** [comment]
See https://github.com/spryker-shop/product-option-widget/releases/tag/1.0.1

**Comment by lsmith77** [comment]
Yeah .. its just a "performance bug" .. wasn't sure how to classify it .. will classify such issues as "enhancement" next time.
