### ISSUE TITLE
ProductPackagingUnitTypeInstaller not idempotent anymore 

### ISSUE THREAD

**Issue by bazoo0815** [spryker/support#228]
This is a

* [x] bug

When running the console command `vendor/bin/console setup:init-db` more than once, the installer ProductPackagingUnitTypeInstaller crashes any version >= 1.x 

This is caused by a change in release 1.0.0 in `\Spryker\Zed\ProductPackagingUnit\Persistence\ProductPackagingUnitEntityManager::saveProductPackagingUnitType()`:
The method to check for an existing packaging unit type was changed from `filterByName()` to `filterByIdProductPackagingUnitType()`. This method does not return existing packaging unit types for the installer, because there is only the name provided, not an id  
 (see https://github.com/spryker/product-packaging-unit/compare/0.0.1...1.0.0#diff-0482ba6e4ca23086aff41b487d821398R28).

The installer is supposed to run multiple times without errors, either creating or updating database entries, just like the other installers.

**Comment by tvaleriy** [comment]
Thanky for the report. I will notify when it is fixed and released.

**Comment by tvaleriy** [comment]
Should be fixed in https://github.com/spryker/product-packaging-unit/releases/tag/1.0.6.
