### ISSUE TITLE
OauthCustomerInstaller not idempotent

### ISSUE THREAD

**Issue by bazoo0815** [spryker/support#229]
This is a

* [x] bug

When running the console command `vendor/bin/console setup:init-db` more than once, the installer OauthCustomerInstaller crashes, because eventually in `\Spryker\Zed\Oauth\Persistence\OauthEntityManager` both methods `saveClient` and `saveScope` are not working in an idempotent way.
This applies to all version of `spryker/oauth`.

**Comment by tvaleriy** [comment]
Thank you for the report. I will notify when it is fixed and released.

**Comment by tvaleriy** [comment]
Should be fixed in https://github.com/spryker/oauth/releases/tag/1.1.0 and https://github.com/spryker/oauth-customer-connector/releases/tag/1.1.0.
