### ISSUE TITLE
propel:migration:check doesn't work for more than one missing migration

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#230]
This is a

* [x] bug
* [ ] enhancement

spryker/propel 3.5.3

### What you did
running `vendor/bin/console propel:migration:check` doesn't work if more than one migration needs to be executed, because the needle 'migration needs to be executed' will not be found, rather it must also be searched for 'migrations need to be executed' or the easy way just 'to be executed:' to have one case for all.

**Comment by tvaleriy** [comment]
Thank you for the report. I will notify when it is fixed and released.

**Comment by tvaleriy** [comment]
Hi Benjamin, this finally should be fixed in https://github.com/spryker/propel/releases/tag/3.8.1.
