### ISSUE TITLE
PriceProductDataImportPlugin instanced twice

### ISSUE THREAD

**Issue by AngelVazquezArroyo** [spryker/support#231]
This is a

* [x] bug

PriceProductDataImportPlugin twice instanced on method DataImportDependencyProvider::getDataImporterPlugins()

**Comment by tvaleriy** [comment]
Thank you for the report. I will notify when it is fixed and released.

**Comment by dereuromark** [comment]
Can you please check master.
This has been removed in a recent publish and sync update @ https://github.com/spryker-shop/suite/blob/master/src/Pyz/Zed/DataImport/DataImportDependencyProvider.php

**Comment by AngelVazquezArroyo** [comment]
Actually we are working with a old suite version. I saw that this Bug is not more on the newest version. Thank you so much.
