### ISSUE TITLE
CategoryType missing 'is_clickable' field

### ISSUE THREAD

**Issue by namikk** [spryker/support#232]
This is a

* [x] bug

spryker/category 4.0.0 

### What you did
Upgrade to 4.0.0 from 3.2.4.

### Actual Behavior
Category create/edit pages started breaking since the project-level .twig files were rendering form rows one by one with `form_row`, instead of using `form_widget` to render all fields. After checking 3.2.4/4.0.0 diff (https://github.com/spryker/category/compare/3.2.4...4.0.0), I noticed that the field `FIELD_IS_CLICKABLE` was removed from the `CategoryType`, but it was kept unchanged in the database. 

This caused our project-level .twig files to fail (`form_row` failed due to missing field), but the spryker .twig files were working fine since they now used `form_widget`. The missing `is_clickable` field was simply not rendered with the spryker .twig files. I'm unsure if this is intended or not.

### Expected Behavior
* If the field was removed on purpose, then it's a project-level issue (ideally should be mentioned on the migration page: https://academy.spryker.com/developing_with_spryker/migration_guides/mg_category.html#3-4)
* If the field was removed by accident, then I would expect it to be restored to the `CategoryType`.
**Note:** I appears that the current version (4.8.0) is still missing this field.

For reference, this is what was removed in 4.0.0:
```
    /**
     * @param \Symfony\Component\Form\FormBuilderInterface $builder
     *
     * @return $this
     */
    protected function addIsClickableField(FormBuilderInterface $builder)
    {
        $builder->add(static::FIELD_IS_CLICKABLE, CheckboxType::class, [
            'label' => 'Clickable',
            'required' => false,
        ]);
         return $this;
    }
```

**Comment by tvaleriy** [comment]
Thank you for the report. I will notify when it is fixed or the documentation is updated.

**Comment by tvaleriy** [comment]
The documentation should be updated - http://documentation.spryker.com/content/module_migration_guides/mg-category.htm.
