### ISSUE TITLE
Password changed confirmation e-mail not sent

### ISSUE THREAD

**Issue by harmavenso** [spryker/support#235]
This is a

* [ x] bug
* [ ] enhancement

For questions please consult the [Spryker Forum](http://discuss.spryker.com/).

Please provide the exact versions of the modules involved (see composer.lock file).

Customer Bundle (7.11.0)

### What you did

Bug Description: 

Preconditions: registered customer account

Click Flow to reproduce Bug:

Request password reset on login page.

### Actual Behaviour

No confirmation mail send when password has been changed

### Expected Behaviour

When customer successfully changes his password with password reset mail, a confirmation email should be sent, see:

vendor/spryker/customer/src/Spryker/Zed/Customer/Business/Customer/Customer.php (421)

On this line "sendPasswordRestoreConfirmation" is called, but it doesn't successfully complete this.

**Comment by tvaleriy** [comment]
Can't reproduce. Works as expected using Customer Bundle (7.11.0).
