### ISSUE TITLE
Spryker breaks down with huge data in CMS maintenance /ZED

### ISSUE THREAD

**Issue by manuelhutter** [spryker/support#236]
This is a

* [x] bug
* [ ] enhancement
_(ordered by Dennis Krüger on 17th of october)_

**How / What:** 
- When a user will edit a CMS block, then the response is not completely built up because the system tries to load all the categories and products in the background. 
- https://zed-stage.wfhosting.ch/cms-block-gui/edit-block?id-cms-block=11 
- In the W+F Akona project these are too much to load them initially. 
Browser will break down

Please provide the exact versions of the modules involved (see composer.lock file):
>> CMS module & version: 
- “name”: “spryker/cms”
- “version”: “6.5.2"
- “name”: “spryker/cms-block-gui”,
“version”: “2.0.1"
- “name”: “spryker/cms-gui”
“version”: “4.3.8"

### What you did
1. Login to Spryker /ZED
2. Open CMS modul
3. Edit block

### Actual Behavior
Browser has no response and breaks down, because the CMS will load for preparing the edit suggest informations all in the background - in our case too much products (houndreds of thousands)

### Expected Behavior
The CMS Block will properly loading

Reference with a screen: https://winterhalter-fenner.atlassian.net/browse/WF-1436 and here https://www.dropbox.com/s/yhg6vso5ivyi8rp/CMS-Edit-Block-Spryker-Browser-breaks-down.png?dl=0

**Comment by tvaleriy** [comment]
Thank you for the report. I will notify here when it is fixed and released.

**Comment by tvaleriy** [comment]
Hi @manuelhutter, this should have been fixed in next modules:
https://github.com/spryker/cms-block-product-connector/releases/tag/1.2.0
https://github.com/spryker/gui/releases/tag/3.24.0
https://github.com/spryker/product/releases/tag/6.12.0.

Best,
Spryker Support Team

**Comment by manuelhutter** [comment]
Hi @tvaleriy, we will check it.
Thanks!

Best regards,
Manuel Hutter
