### ISSUE TITLE
PriceProduct 1.3.0 - use statement is missing

### ISSUE THREAD

**Issue by mruoss** [spryker/support#237]
This is a

* [x] bug

Hi there

Don't you backport your bugfixes to older major versions? In PriceProduct version 1.3.0 a use statement is missing:

`use Generated\Shared\Transfer\MoneyValueTransfer;` is missing in:

https://github.com/spryker/price-product/blob/1.3.0/src/Spryker/Zed/PriceProduct/Business/Model/Reader.php

**Comment by tvaleriy** [comment]
Thank you for the report. I will notify when it is fixed and released.

**Comment by tvaleriy** [comment]
Hi @mruoss, should be fixed in https://github.com/spryker/price-product/releases/tag/1.3.1.
