### ISSUE TITLE
Exception message casts the SKU to `%d` instead of `%s`.

### ISSUE THREAD

**Issue by dantleech** [spryker/support#242]
This is a

* [x] bug
* [ ] enhancement

Exception message casts the SKU to `%d` instead of `%s`.

### What you did

Received exception message 'Could not change cart item "0" with "0" as value.' when adding an item to the cart (for whatever reason).

### Actual Behavior

Could not change cart item "0" with "0" as value

### Expected Behavior

Could not change cart item "THE_SKU_HERE" with "0" as value

---

In `vendor/spryker/cart/src/Spryker/Zed/Cart/Business/StorageProvider/NonPersistentProvider.php` it uses `%d` to format the SKU instead of `%s`

**Comment by dereuromark** [comment]
We need to be more careful with %d usage in general. In question, we should rather use the generic %s then.

**Comment by tvaleriy** [comment]
Thank you for the feedback. I will notify when it is fixed and released.

**Comment by dereuromark** [comment]
Please note that I also opened up a PHPStan improvement ticket so these things can be caught more reliable in the release process in the future: https://github.com/phpstan/phpstan/issues/1577

**Comment by tvaleriy** [comment]
Should be fixed in https://github.com/spryker/cart/releases/tag/5.5.2.
