### ISSUE TITLE
spryker-eco/heidelpay 1.1.0 does not allow spryker/session ^4.0.0

### ISSUE THREAD

**Issue by MarcBoeing** [spryker/support#243]
This is a

* [X] bug
* [X] enhancement

For questions please consult the [Spryker Forum](http://discuss.spryker.com/).

Please provide the exact versions of the modules involved (see composer.lock file).
spryker-eco/heidelpay  1.1.0

### What you did
I wanted to update spryker/session to 4.0.0

### Actual Behavior
Not possible, as spryker-eco/heidelpay doesn´t have an updated requirement in composer.json for spryker/session ^4.0.0

### Expected Behavior
spryker-eco/heidelpay (and other eco modules) are updated, similar to the core modules to allow a smooth update experience.

**Comment by tvaleriy** [comment]
Thank you for the feedback. I will notify when it's fixed and released.

**Comment by MarcBoeing** [comment]
https://github.com/spryker-eco/heidelpay/releases/tag/1.2.0
Thank you!
