### ISSUE TITLE
OMS: wrong calculation of "reserved items" for a sku

### ISSUE THREAD

**Issue by markuspatrick** [spryker/support#244]
This is a

* [X] bug
* [x] enhancement

Please provide the exact versions of the modules involved (see composer.lock file).
"name": "spryker/oms" / "version": "8.3.0",

### What you did
Use two different OMS  payment processes, which shares a common state (e.g. "payment accepted"). In the first process the common state has a "reserved flag", but in the other one the common state DONT have the "reserved flag". 
This can be the case, 
(1.) if you want to use a different stock handling depending on the payment method
(2.) if the stock handling, i.e. the reserved flag, for a specific state changed over the time (versioning of payment process)
  
### Actual Behavior
The reserved items were not "released/decremented", if an order reach the non flagged status "payment accepted" (in the process without reserved flags).  It always sum-up the amount of reserved items of the state "payment accepted" - independent that one state done have the flag. 

We assume a sku = "XYZ";
Items with sku="XYZ" in state "Payment accepted" for process with reserved flag = 10
Items with sku="XYZ" in state "Payment accepted" for process WITHOUT reserved flag = 5

Amount of reserved Items for sku "XYZ" = 15

### Expected Behavior

Items with sku="XYZ" in state "Payment accepted" for process with reserved flag = 10
Items with sku="XYZ" in state "Payment accepted" for process WITHOUT reserved flag = 5

Amount of reserved Items for sku "XYZ" = 10

### Work Around /QuickFix
* Rename the state in the second process
* Deactivated "older" versions of the same payment process were a specific state or rather it reserved flag did changed over time.

### Point of Error in Code
The bug starts here 
Spryker\Zed\Oms\Business\OrderStateMachine
in row 900 in the function: "getStateFromAllProcesse" : 

```
protected function updateReservation(ProcessInterface $process, $sourceStateId, $targetStateId, $sku)
    {
        $sourceStateIsReserved = $process->getStateFromAllProcesses($sourceStateId)->isReserved();
        $targetStateIsReserved = $process->getStateFromAllProcesses($targetStateId)->isReserved();
        
         if ($sourceStateIsReserved !== $targetStateIsReserved) {
            $this->reservation->updateReservationQuantity($sku);
        }
    }
 ```

**Comment by tvaleriy** [comment]
Thank you for the feedback. Confirmed. I will notify when it is fixed and released.

**Comment by tvaleriy** [comment]
Hi @markuspatrick, this should have been finally fixed in https://github.com/spryker/oms/releases/tag/10.4.0 and https://github.com/spryker/product-packaging-unit/releases/tag/3.1.0.

Best,
Spryker Support Team
