### ISSUE TITLE
ArvatoRssQueryContainer::queryApiLogByOrderReferenceAndType does not filter by order reference and type

### ISSUE THREAD

**Issue by nothingbutnet** [spryker/support#245]
This is a

* [x] bug
* [ ] enhancement

Module: `spryker-eco/arvato-rss`
Version: `2.0.1`

### What you did
Trying to filter the arvato rss api call log by order reference and type using `ArvatoRssQueryContainer::queryApiLogByOrderReferenceAndType`.

### Actual Behavior
The result is not filtered by order reference and type.

### Expected Behavior
The result should be filtered (as the method name suggests) by order reference and type.

**Comment by tvaleriy** [comment]
Thank you for the report. Internal ticket is created. I will notify when it is fixed and released.

**Comment by tvaleriy** [comment]
Hi @nothingbutnet, this should have been fixed in https://github.com/spryker-eco/arvato-rss/releases/tag/2.1.0.
