### ISSUE TITLE
Wrong order of return values in StorageClient::getMulti() with activated cache

### ISSUE THREAD

**Issue by stefankleff** [spryker/support#248]
This is a

* [ x] bug
* [ ] enhancement

For questions please consult the [Spryker Forum](http://discuss.spryker.com/).

Please provide the exact versions of the modules involved (see composer.lock file).
3.5.0

### What you did
Registered StorageCacheServiceProvider in Yves Bootstrap

$client = new StorageClient()
$values = $client->getMulti(['a','b',c'])

### Actual Behavior
$values contain the values of the given keys in undetermined order
This is dependent on (1) the order the values are saved in the cache and (2) if non-cached keys will be loaded. 

Real case scenario
Some sorted products from elasticsearch are fetched via cached multiget. The sorted products will become unsorted.

### Expected Behavior
$values contain the values of the given keys in the same order as the given keys
See https://redis.io/commands/mget

**Comment by tvaleriy** [comment]
Thank you for the report. Internal ticket is created. I will notify when it is fixed and released.

**Comment by tvaleriy** [comment]
Hi @stefankleff, this should be fixed in https://github.com/spryker/storage/releases/tag/3.7.1. Please update.
