### ISSUE TITLE
Unhandled error in filesystem cache writer

### ISSUE THREAD

**Issue by dantleech** [spryker/support#249]
This is a

* [x] bug
* [ ] enhancement

```
spryker/twig                                          3.3.3              Twig module
```

### What you did

The `FilesystemCacheWrtier` is being invoked in our CI system
### Actual Behavior

We get a raw PHP error with no contextual information:

```
Uncaught ErrorException: mkdir(): Permission denied in /app/vendor/spryker/twig/src/Spryker/Shared/Twig/Cache/CacheWriter/FilesystemCacheWriter.php:49
```

### Expected Behavior

The error should be handled and an exception thrown with some contextual information:

```
Could not create directory "/path/where/I/tried/to/create"
```

Thanks!

**Comment by tvaleriy** [comment]
Thank you for the report. I will notify when it is fixed and released.

**Comment by tvaleriy** [comment]
Hi @dantleech,

this should have been finally fixed in https://github.com/spryker/twig/releases/tag/3.7.2.

Best,
Spryker Support Team
