### ISSUE TITLE
[spryker/setup] 4.1.0  breaks jenkins job generator

### ISSUE THREAD

**Issue by mruoss** [spryker/support#250]
This is a

* [x] bug

We already discussed the issue briefly on slack. Version 4.1.0 of bundle `spryker/setup` breaks the jenkins job generator. The generator generates shell commands that fail.

Reason is the code `$destination = '\$destination_release_dir';` that was introduced [in this commit](https://github.com/spryker/setup/commit/92504862b928fba7ade327e257f918095ff10088#diff-9bf4ab0b18867a3bf963883da7eb03d5R472). The dollar character doesn't need to be escaped inside single quotes. 

The generated code contains the backslash and fails.

**Comment by tvaleriy** [comment]
Thank you. I will notify when it is fixed and released.

**Comment by tvaleriy** [comment]
Should be fixed in https://github.com/spryker/setup/releases/tag/4.1.1.
