### ISSUE TITLE
category cannot add new localized attributes

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#251]
This is a

* [x] bug
* [ ] enhancement

spryker/category    4.10.0

### What you did

editing an existing category which has less localized attributes saved then the shop has.

Save a category with just DE locale active for your shop => just DE localized attributes are created
Add EN locale to your shop
Edit the category again. You cannot edit EN localized attributes, just DE

### Expected Behavior
all possible locales should be added to the transfer object

also see https://github.com/spryker/support/issues/155

**Comment by tvaleriy** [comment]
Thank you for the report. I will notify when it is fixed and released.

**Comment by tvaleriy** [comment]
Hi @AndromedaXP,

this should have been finally fixed in https://github.com/spryker/category/releases/tag/4.16.0.

Best,
Spryker Support Team
