### ISSUE TITLE
Missing isMultiValued flag for facet search in Glue API 

### ISSUE THREAD

**Issue by newLoki** [spryker/support#254]
This is a

* [x] bug

Please provide the exact versions of the modules involved (see composer.lock file).

### What you did

Acess http://glue.de.suite.local/catalog-search/?q=some_search_string

### Actual Behavior

Part of the response is an array of "ValueFacets", but there is no information what facet is multivalued and which not.

### Expected Behavior

In Yves this is present in the ValueFacetConfig, so it should be in the Glue API too.

Our fix was to overwrite the related transfer object:

src/Pyz/Shared/CatalogSearchRestApi/Transfer/catalog_search_rest_api.transfer.xml

```
<?xml version="1.0"?>
<transfers xmlns="spryker:transfer-01"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="spryker:transfer-01 http://static.spryker.com/transfer-01.xsd">

    <transfer name="RestFacetSearchResultAttributes">
        <property name="config" type="RestFacetSearchResultAttributesConfig" />
    </transfer>

    <transfer name="RestFacetSearchResultAttributesConfig">
        <property name="isMultiValued" type="boolean" />
    </transfer>
</transfers>

```

**Comment by tvaleriy** [comment]
Thank you for the report. I will notify when it is fixed.

**Comment by tvaleriy** [comment]
Should be fixed in https://github.com/spryker/catalog-search-rest-api/releases/tag/2.1.0.
