### ISSUE TITLE
Invalid form type in Zed user reset password form

### ISSUE THREAD

**Issue by dantleech** [spryker/support#256]
This is a

* [x] bug
* [ ] enhancement

We're using `v3.3.4` of `symfony/form` which I believe only supports referencing forms by class name (or at least the Silex provider doesn't register the short names anymore).

https://github.com/spryker/user/blob/master/src/Spryker/Zed/User/Communication/Form/ResetPasswordForm.php#L95

This can simply be changed from `'password'` to `PasswordType::class`

### What you did

Click `Settings > Reset Password`

### Actual Behavior

Exception: `Symfony\Component\Form\Exception\InvalidArgumentException - Could not load type "password"`

### Expected Behavior

Show password reset form.

**Comment by tvaleriy** [comment]
Should be fixed in https://github.com/spryker/user/releases/tag/3.5.1.
Sorry, missed this release as it was fixed in different ticket.

**Comment by dantleech** [comment]
Thanks :+1:
