### ISSUE TITLE
Related product widget referencing in-active products causes exception

### ISSUE THREAD

**Issue by dantleech** [spryker/support#257]
This is a

* [x] bug
* [ ] enhancement

This is caused because the storage client throws an exception when an abstract product is not found, however the RelatedProductReader expects a `null` in this case:

https://github.com/spryker/product-relation-storage/blob/master/src/Spryker/Client/ProductRelationStorage/Relation/RelatedProductReader.php#L62

The API for `Spryker\\Client\\ProductRelationStorage\\Dependency\\Client\\ProductRelationStorageToProductStorageClientInterface` indicates that this will only return an `array` however.

### What you did

Show a widget which references related products which are currently inactive and not present in Redis.

### Actual Behavior

Throws exception

```
SprykerShop\Yves\ShopApplication\Exception\WidgetRenderException - Pyz\Client\ProductStorage\Storage\AbstractProductNotFoundException - Something went wrong in widget "SimilarProductsWidgetPlugin": Abstract product not found in redis for abstract product 18 in /app/src/Pyz/Client/ProductStorage/Storage/ProductAbstractStorageReader.php:20
```

### Expected Behavior

Ignores missing products

**Comment by tvaleriy** [comment]
Hi @dantleech, I can't confirm/reproduce this using latest master branch of the suite repository.
If you are still experiencing the same problem, could you please try to update spryker-shop/product-widget module if it isn't latest?
