### ISSUE TITLE
propel:install will not return error code

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#260]
This is a

* [x] bug
* [ ] enhancement

spryker/propel                          3.8.0

### What you did
run `sf propel:install` with an error during migration will not return correct error code. Therefore the deployment will not stop if something goes wrong here.
Problem is that, PropelInstallConsole overwrites runDependingCommand (useless) and therefore $exitCode is not set.

**Comment by tvaleriy** [comment]
Thank you for the report. I will notify when it is fixed.

**Comment by tvaleriy** [comment]
Hi @AndromedaXP, this should have been finally fixed in https://github.com/spryker/propel/releases/tag/3.10.1. Please update.
