### ISSUE TITLE
url starting with customer not callable

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#262]
This is a

* [x] bug
* [ ] enhancement

spryker-shop/customer-page              1.14.1             CustomerPage module
spryker-shop/customer-page-extension    1.2.0              CustomerPageExtension module
spryker/customer                        7.15.0             Customer module
spryker/customer-access                 1.1.0              CustomerAccess module
spryker/customer-access-permission      1.1.0              CustomerAccessPermission module
spryker/customer-access-storage         1.1.0              CustomerAccessStorage module
spryker/customer-extension              1.1.0              CustomerExtension module

### What you did
Calling an url /customer-xxx/ which is a cms page and correctly exported to redis.

### Actual Behavior
I get redirected to /login/

### Expected Behavior
I want to see the cms page

**Comment by tvaleriy** [comment]
Thank you for the report. I will notify when it is fixed and released.

**Comment by tvaleriy** [comment]
This is how it can be fixed on project level:

config/Shared/config_default.php:
-`$config[CustomerConstants::CUSTOMER_SECURED_PATTERN] = '(^/login_check$|^(/en|/de)?/customer|^(/en|/de)?/wishlist|^(/en|/de)?/shopping-list|^(/en|/de)?/company(?!/register)|^(/en|/de)?/multi-cart|^(/en|/de)?/shared-cart|^(/en|/de)?/cart(?!/add)|^(/en|/de)?/checkout)';`

+`$config[CustomerConstants::CUSTOMER_SECURED_PATTERN] = '(^/login_check$|^(/en|/de)?/customer($|/)|^(/en|/de)?/wishlist($|/)|^(/en|/de)?/shopping-list($|/)|^(/en|/de)?/company(?!/register)($|/)|^(/en|/de)?/multi-cart($|/)|^(/en|/de)?/shared-cart($|/)|^(/en|/de)?/cart(?!/add)($|/)|^(/en|/de)?/checkout($|/))';`
