### ISSUE TITLE
MonitoringExtensions doesn't work in YVES

### ISSUE THREAD

**Issue by ridculy** [spryker/support#264]
This is a

* [X ] bug
* [ ] enhancement

### What you did

We use a NewRelic Monitoring Extension in our Project and this NewRelic Monitoring Service has stoped to Show the right Transaction Name in YVES. In Zed it's working.

After undoing this commit YVES writes the Transaction Name again to NewRelic:

https://github.com/spryker/spryker-core/commit/c6433e3d91302c50410348c26694cbca0331bf85#diff-d6f085891024509a111dd690ce374812

**Comment by tvaleriy** [comment]
HI @ridculy and @AndromedaXP.

Here is the feedback of our developer who was investigating this:

>I have investigated this extensively and tried to reproduce the issue, yet I couldn't. also I reverted the mentioned commit and tested it and I can confirm, there's no change in the behaviour, it's backward compatible.

>My best guess is that the customer updated the Monitoring module to the latest version, which is a major and requires a migration, the newRelic plugin was removed from Yves (Service) MonitoringDependencyProvider and the customer should re-add the plugin to Service/Monitoring/MonitoringDependencyProvider, this is why it was released as a major.

>The mentioned commit is BC, but the release is a major release and it's not BC.
https://github.com/spryker/monitoring/compare/1.0.2...2.0.0

>Maybe the customer should have commented on and mentioned this commit instead: https://github.com/spryker/monitoring/commit/6191f2c154c607c033858ab5bd8115e0f2d282a3

Could you confirm please?

**Comment by tvaleriy** [comment]
Hi @ridculy and @AndromedaXP,

as there was no feedback from you, I have to close this ticket.

Best,
Spryker Support Team
