### ISSUE TITLE
The product labels widget creates invalid css classes

### ISSUE THREAD

**Issue by tomaheaton** [spryker/support#268]
This is a

* [x] bug
* [ ] enhancement

For questions please consult the [Spryker Forum](http://discuss.spryker.com/).

Please provide the exact versions of the modules involved (see composer.lock file).
1.1.0

### What you did
We are displaying product labels on PDPs and PLPs.

### Actual Behavior
Our product labels are created using the default spryker flag.twig file but the modifier on the atom has the name of the product with spaces/commas which is not valid:
`<span class="flag flag--Buy more, pay less" data-qa="component flag">`

### Expected Behavior
Out of the box I would expect this to be avoided, perhaps stripping out the spaces and punctuation which would make a valid css class.

**Comment by tvaleriy** [comment]
Thank you for the feedback. I will notify when it is fixed and released.

**Comment by m7moud** [comment]
Hi @tomaheaton,

Do you have an example for how do you use this `flag` component in your project?

**Comment by tvaleriy** [comment]
I'm closing this issue as not relevant then.
