### ISSUE TITLE
Discounts' max. usage pre condition fails for vouchers with infinite usage

### ISSUE THREAD

**Issue by felixgeyer** [spryker/support#269]
This is a

- [x] bug

Please provide the exact versions of the modules involved (see composer.lock file).

**spryker/discount v7.2.0**

### What you did
Added the newly introduced `VoucherDiscountMaxUsageCheckoutPreConditionPlugin` to the `CheckoutDependencyProvider`. 

Then tried to apply a voucher with _max. number of uses_ = 0 (according to ZED Gui = infinite usage).

### Actual Behavior
Validation fails, as `findVouchersExceedingUsageLimitByCodes()` in `DiscountRepository` checks if the actual number of uses is greater than the max. number of uses. 
For vouchers with infinite usage this will always be the case.

### Expected Behavior
Vouchers with unlimited number of uses should not be considered as used too often.

**Comment by tvaleriy** [comment]
Hi @felixgeyer, this should be fixed in https://github.com/spryker/discount/releases/tag/7.4.0. Please update it in your project.
