### ISSUE TITLE
Oms Flags don't work

### ISSUE THREAD

**Issue by FabianWesner** [spryker/support#270]
This is a

* [X] bug
* [ ] enhancement

For questions please consult the [Spryker Forum](http://discuss.spryker.com/).

Please provide the exact versions of the modules involved (see composer.lock file).

From peter.smith@inviqa.com

We've identified a bug in the Spryker StateMachine Module, specifically with StateMachineFacade::getItemsWithFlag()
> The return of this method is a collection of StateMachineItemTransfer, supposedly representing all state machine items which have been in a state carrying the specified flag. However, each item has the identifier of the earliest item in the list. So in our case, we are trying to discover whether the latest state machine item has been in a state with a particular flag, but all the results have the identifier of the first item to ever have that flag.
> The error is here: https://github.com/spryker/state-machine/blob/master/src/Spryker/Zed/StateMachine/Business/StateMachine/Finder.php#L341

**Comment by tvaleriy** [comment]
The ticket is created. I will notify when it is fixed and released.

**Comment by tvaleriy** [comment]
Hi @FabianWesner, this should have been fixed in https://github.com/spryker/state-machine/releases/tag/2.5.0.
