### ISSUE TITLE
Wrong property name in RestCartsDiscountsTransfer

### ISSUE THREAD

**Issue by felixgeyer** [spryker/support#272]
This is a

* [x] bug

Please provide the exact versions of the modules involved (see composer.lock file).

`spryker/discount v7.2.1`

### What you did
Applied a voucher code to a cart and requested the cart object via GLUE API.

### Actual Behavior
The `RestCartsDiscountsTransfer` has a property called `code` which should hold the voucher code.
As the original property name is `voucherCode`, it is not mapped correctly when using the `$transfer->fromArray()` method.
Example: 
```
{
"data": {
        "type": "carts",
        "id": "some-cart-id",
        "attributes": {
            "priceMode": "NET_MODE",
            "currency": "EUR",
            "store": "DE",
            "discounts": [
                {
                    "displayName": "Demo-Voucher",
                    "amount": 5332,
                    "code": null
                }
            ],
            "totals": {
                "expenseTotal": 0,
                "discountTotal": 5332,
                "taxTotal": 0,
                "subtotal": 5332,
                "grandTotal": 0
            }
        },
...
```

### Expected Behavior
The property should be renamed to `voucherCode`.
Example:
```
{
"data": {
        "type": "carts",
        "id": "some-cart-id",
        "attributes": {
            "priceMode": "NET_MODE",
            "currency": "EUR",
            "store": "DE",
            "discounts": [
                {
                    "displayName": "Demo-Voucher",
                    "amount": 5332,
                    "voucherCode": "SPECIAL100"
                }
            ],
            "totals": {
                "expenseTotal": 0,
                "discountTotal": 5332,
                "taxTotal": 0,
                "subtotal": 5332,
                "grandTotal": 0
            }
        },
...
```

**Comment by tvaleriy** [comment]
Hi @felixgeyer,

thank you for the feedback, but at the moment we are supporting only cart rules discounts in the response. Supporting of voucher codes is in our backlog, but I can't say when it's going to be implemented.

I'm closing this ticket, but feel free to let us know if you have further questions.
