### ISSUE TITLE
Databuilder not type safe

### ISSUE THREAD

**Issue by benqn** [spryker/support#273]
This is a

* [ x] bug
* [ ] enhancement

For questions please consult the [Spryker Forum](http://discuss.spryker.com/).

Please provide the exact versions of the modules involved (see composer.lock file).

### What you did
I used the databuilder in test. 

### Actual Behavior
The properties of objects are not type save. Int properties saved as strings. 

suggestion:
look at the class AbstractDatabuilder at function generateFromRule.

**Comment by tvaleriy** [comment]
Thank you for the report. I will notify if/when it is fixed and released.

**Comment by tvaleriy** [comment]
Hi @benqn, this should have been fixed in https://github.com/spryker/testify/releases/tag/3.11.3.

Best,
Spryker Support Team
