### ISSUE TITLE
Transfer object AvailabilityNotificationDataTransfer not found

### ISSUE THREAD

**Issue by senor-dingdong** [spryker/support#274]
This is a

* [x] bug
* [ ] enhancement

### What you did
Update spryker/availability from version 6.3.1 to version 6.4.0

### Actual Behavior
In class /Spryker/Zed/Availability/Business/Model/AvailabilityHandler.php a transfer object named "AvailabilityNotificationDataTransfer" is being used, the actual transfer object is called "AvailabilityNotificationTransfer" though. This renaming happened with commit 75d0ff57f08a1967b7e2a74503456abd, I think the transfer object itself should have been renamed as well...

**Comment by tvaleriy** [comment]
Thank you for the report. The fix is going through releasing process. I will notify when it is released.

**Comment by tvaleriy** [comment]
Should be fixed in https://github.com/spryker/availability/releases/tag/6.4.1.
