### ISSUE TITLE
responseClass does not work for rest documentation

### ISSUE THREAD

**Issue by newLoki** [spryker/support#275]
This is a

* [x] bug
* [ ] enhancement

Please provide the exact versions of the modules involved (see composer.lock file).

"spryker/documentation-generator-rest-api": "1.3.0"

### What you did

Tried to set a custom `responseClass` as documented at https://documentation.spryker.com/tutorials/introduction/glue_api/documenting-glue-api-resources.htm and run `console rest-api:generate:documentation` to generate the swagger documentation.

### Actual Behavior

The custom `responseClass` is not included in the generated `spryker_rest_api.schema.yml` and neither is there any code in Spryker to handle `responseClass`. (See https://github.com/search?q=org%3Aspryker+responseClass&type=Code).

### Expected Behavior

Either `responseClass` should be used to be included in the `spryker_rest_api.schema.yml` when set at a controller action annotation or this feature shouldn't be documented, as it does not exist.
I would prefer to get this as a working feature.

**Comment by v-v-volkov** [comment]
Hello newLoki,

There is an error in the documentation. The correct parameter name is `responseAttributesClassName`. Change the name in your annotation and try again.

We are sorry for any inconvenience and will fix the documentation ASAP.

**Comment by v-v-volkov** [comment]
The document has been fixed. You can find the updated version here:
https://documentation.spryker.com/tutorials/introduction/glue_api/documenting-glue-api-resources.htm
