### ISSUE TITLE
spryker-eco/heidelpay setIsSandboxMode for Basket call

### ISSUE THREAD

**Issue by egobude** [spryker/support#276]
This is a

* [X] bug
* [X] enhancement

Please provide the exact versions of the modules involved (see composer.lock file).

* spryker-eco/heidelpay: 2.0.0

### What you did

Pay an order via Heidelpay Payment

### Actual Behavior

The method `Basket::addNewBasket` does not respect the sandbox mode. 

file: vendor/spryker-eco/heidelpay/src/SprykerEco/Zed/Heidelpay/Business/Adapter/Basket/Basket.php

```php
   /**
     * @param \Generated\Shared\Transfer\HeidelpayBasketRequestTransfer $heidelpayBasketRequestTransfer
     *
     * @return \Generated\Shared\Transfer\HeidelpayBasketResponseTransfer
     */
    public function addNewBasket(HeidelpayBasketRequestTransfer $heidelpayBasketRequestTransfer): HeidelpayBasketResponseTransfer
    {
        ...

        $request = new Request($authentication, $heidelpayBasket);
        $response = $request->addNewBasket();
        
        ...
        
        return $heidelpayBasketResponseTransfer;
    }
``` 

### Expected Behavior

```php
   /**
     * @param \Generated\Shared\Transfer\HeidelpayBasketRequestTransfer $heidelpayBasketRequestTransfer
     *
     * @return \Generated\Shared\Transfer\HeidelpayBasketResponseTransfer
     */
    public function addNewBasket(HeidelpayBasketRequestTransfer $heidelpayBasketRequestTransfer): HeidelpayBasketResponseTransfer
    {
        ...

        $request = new Request($authentication, $heidelpayBasket);

        // This is missing otherwise all requests will be sent to https://test-heidelpay.hpcgw.net/ngw/basket/ instead of https://test-heidelpay.hpcgw.net/ngw/basket/ 
        $request->setIsSandboxMode($this->config->getMerchantSandboxMode());

        $response = $request->addNewBasket();
        
        ...
        
        return $heidelpayBasketResponseTransfer;
    }
```

**Comment by tvaleriy** [comment]
Hi Benedikt, thank you for the report. But we do not support configurable sandbox mode for this module.
If you think that we should, you can post this feature request here - https://spryker.ideas.aha.io. I'm closing this ticket, but feel free to contact if you have any further questions.

**Comment by egobude** [comment]
Hi @tvaleriy, 

mhm, but i don't get why. The module is not working correctly without the configurable sandbox mode and you are supporting it already:

File: vendor/spryker-eco/heidelpay/src/SprykerEco/Zed/Heidelpay/Business/Payment/Request/BaseAdapterRequestBuilder.php

```php
   /**
     * @param \Generated\Shared\Transfer\HeidelpayRequestTransfer $heidelpayRequestTransfer
     *
     * @return \Generated\Shared\Transfer\HeidelpayRequestTransfer
     */
    protected function hydrateAuthenticationInfo(HeidelpayRequestTransfer $heidelpayRequestTransfer): HeidelpayRequestTransfer
    {
        $authenticationTransfer = (new HeidelpayAuthenticationTransfer())
            ->setUserLogin($this->config->getMerchantUserLogin())
            ->setUserPassword($this->config->getMerchantUserPassword())
            ->setSecuritySender($this->config->getMerchantSecuritySender())
            ->setIsSandboxRequest($this->config->getMerchantSandboxMode());

        $heidelpayRequestTransfer->setAuth($authenticationTransfer);

        return $heidelpayRequestTransfer;
```

Best regards
Benedikt

**Comment by egobude** [comment]
The problem is that the default value is true for `$isSandbox`. So without setting it to false every request will go to https://test-heidelpay.hpcgw.net/ngw/basket/ instead of https://heidelpay.hpcgw.net/ngw/basket/ and that is not so good on a production server. 

File: vendor/heidelpay/php-basket-api/lib/Request.php

```
    /**
     * @var bool $isSandbox If the request is being sent to the test environment
     */
    protected $isSandbox = true;
```

Best regards
Benedikt

**Comment by alex-galych** [comment]
Hi @egobude,

thank you for the detailed bug report. We were a little bit confusing with your **Actual Behavior** since you wrote that a line _$request->setIsSandboxMode..._ is there. 

Now after some investigation, we can confirm that the bug is on our side and we are going to release a bugfix this week. 

Best regards,
Alex Galych

**Comment by egobude** [comment]
Hi @alex-galych,

sorry about that. I have reworked the example once again.

Best regards
Benedikt

**Comment by alex-galych** [comment]
Released - https://github.com/spryker-eco/heidelpay/releases/tag/2.0.1
