### ISSUE TITLE
Chart: Error when compiling with UglifyJs

### ISSUE THREAD

**Issue by luksha6** [spryker/support#278]
After we added chart module in our dashboard we have problems when compiling for production. We did not change any of the assets.

**Command:** 
`"zed:prod": "node ./node_modules/@spryker/oryx-for-zed/build --prod",`

**Versions:**

**(oryx for zed)**
`
"@spryker/oryx-for-zed": "^1.2.1",`

**(chart)**
`"spryker/chart": "^1.0",`

**Error:**

ERROR in ./js/spryker-zed-chart-plotly-main.js from UglifyJs
Name expected [./vendor/spryker/chart/assets/Zed/~/regl-line2d/index.js:12,0][./js/spryker-zed-chart-plotly-main.js:85398,6]

**Comment by tvaleriy** [comment]
https://support.spryker.com/hc/en-us/community/posts/360042789951-Chart-Error-when-compiling-with-UglifyJs
