### ISSUE TITLE
ProductAttributeTransferMapper missing IdProductManagementAttributeValueTranslation

### ISSUE THREAD

**Issue by Julsen** [spryker/support#279]
1. Exact versions of the modules involved (see composer.lock file)
"name": "spryker/product-attribute",
            "version": "1.1.2",
            "source": {
                "type": "git",
                "url": "https://github.com/spryker/product-attribute.git",
                "reference": "8ef9ffef7f1bfedb939651d003cda0d51159740e"
            }

2. Related bundle-name and version
product-attribute in 1.1.2

3. Steps to reproduce
$this->productAttributeTransferMapper->convertProductAttribute($productAttributeEntity)

4. Actual behavior
the localized attributes will be mapped without the ID

5. Expected behavior
the ID will be mapped too

6. Descriptive summary
In file current/vendor/spryker/product-attribute/src/Spryker/Zed/ProductAttribute/Business/Model/Attribute/Mapper/ProductAttributeTransferMapper.php in function setAttributeValues the ids are lost after fromArray ($attributeValueTransfer = (new ProductManagementAttributeValueTransfer())
                ->fromArray($attributeValueTransferData, true);) since the entity uses IdProductManagementAttributeValueTranslation and the transfer itself uses IdProductManagementAttributeValue.

**Comment by tvaleriy** [comment]
Hi @Julsen, this repository isn't an official support desk anymore as you might seen it everywhere (readme, issue template, etc.).
Could you please submit a request using our official support desk - https://support.spryker.com/hc/en-us/requests/new?

Thank you and have a nice weekend!
