### ISSUE TITLE
Possible dependency in the wrong direction 

### ISSUE THREAD

**Issue by newLoki** [spryker/support#28]
I've found a dependency from the product bundle to the tax bundle (https://github.com/spryker/spryker/blob/develop/Bundles/Product/src/Spryker/Zed/Product/Business/Product/ProductManager.php#L503) which should be the other way around.
So the TaxBundle could have a dependency to the ProductBundle but products without taxes should also be possible.

**Comment by dereuromark** [comment]
We will soon refactor and cleanup the product bundle. This will play into it.
