### ISSUE TITLE
Service::getMulti() with empty array 

### ISSUE THREAD

**Issue by ridculy** [spryker/support#29]
Service::getMulti() throws an Exception if used with an empty array. It's a core class and I don't want to move this class in our Project only for one Methode.
Class :
vendor/spryker/spryker/Bundles/Storage/src/Spryker/Client/Storage/Redis/Service.php
Reproduce:
Service::getMulti(array());

Should return an empty array or false

https://spryker.atlassian.net/servicedesk/customer/portal/2/CSN-79

**Comment by the-colorant** [comment]
@ridculy Looks like this has been fixed. Let us know if otherwise.
