### ISSUE TITLE
Use transfer for passing data to senders

### ISSUE THREAD

**Issue by rgex** [spryker/support#31]
The PasswordRestoreTokenSender use for example:
public function send($email, $token)

If I want to add the first/lastname it requires a lot of Spryker code overwritting to achieve this.

One solution would be to use Transfers so that it becomes much more easier to add and remove fields

**Comment by the-colorant** [comment]
@rgex thanks for the input and sorry for delayed answer. We do not plan to work on this topic for now, but I added it to our list of tasks for future. We will definitely consider this when we'll be touching a relevant topic (Mail bundle). We'll get back to you with more details when working on it.
