### ISSUE TITLE
propel column sorting

### ISSUE THREAD

**Issue by tobi812** [spryker/support#32]
Propel column sorting: When you add new columns to a table, that already exists on core-level, they will appear on top of the core-columns in the database:

Core:
```xml
<table name="table"">
        <column name="id" required="true" type="INTEGER" autoIncrement="true" >
        <column name="name" type="VARCHAR" size="255" />
</table>
```
Project:

```xml
<table name="table"">
        <column name="new_column" type="VARCHAR" size="255" />
</table>
```
DB-Result:

Current Order:

- new_column
- id
- name

Expected Order

- id
- name
- new_column

**Comment by dereuromark** [comment]
We will add it to our idea pool as a low priority. Thank you!

**Comment by the-colorant** [comment]
@tobi812 This feature sounds nice but the benefit of it does not cover much use cases as you guys noticed. We will not have this in plan for now unless we get more feedback at some point that this causes pain. However thanks for the idea.
