### ISSUE TITLE
Missing constants used in demoshop

### ISSUE THREAD

**Issue by newLoki** [spryker/support#34]
https://github.com/spryker/demoshop/blob/develop/src/Pyz/Zed/Sales/Communication/Plugin/Oms/Command/Mail/UnderpaidReminderMail.php#L27 
https://github.com/spryker/demoshop/blob/develop/src/Pyz/Zed/Sales/Communication/Plugin/Oms/Command/Mail/UnderpaidReminderMail.php#L46

Both times the used constant are not existing.

**Comment by the-colorant** [comment]
@newLoki This class is outdated and we don't use it in demoshop anymore.
