### ISSUE TITLE
Missing dependency in OMS command (Demoshop)

### ISSUE THREAD

**Issue by newLoki** [spryker/support#35]
https://github.com/spryker/demoshop/blob/develop/src/Pyz/Zed/Sales/Communication/Plugin/Oms/Command/Mail/UnderpaidReminderMail.php#L46

The `mailFacade` is never injected and therefore can not be resolved within the IDE

**Comment by newLoki** [comment]
What was the solution?
Maybe the next one who is stumbling upon this issue will ask the same question so it would be helpful to know how it was solved or if it was just closed without a solution.

**Comment by dereuromark** [comment]
That file was outdated/broken and has been removed because it was non functional in the demo shop.
