### ISSUE TITLE
CustomerConstants::SHOP_MAIL_FROM_EMAIL_NAME might be useless

### ISSUE THREAD

**Issue by rgex** [spryker/support#36]
In the demo shop in the config on line 150 we have

> $config[CustomerConstants::SHOP_MAIL_FROM_EMAIL_NAME] =
    $config[CustomerMailConnectorConstants::SHOP_MAIL_FROM_EMAIL_NAME] = '';

https://github.com/spryker/demoshop/blob/develop/config/Shared/config_default.php#L150

As the value of both constants is the same: 'SHOP_MAIL_FROM_EMAIL_NAME' having it referenced in two different places doesn't really make sense.
Same thing for other constants such as SHOP_MAIL_REGISTRATION_TOKEN, SHOP_MAIL_REGISTRATION_SUBJECT ....

**Comment by dereuromark** [comment]
Thank you, we added it to our cleanup backlog.
