### ISSUE TITLE
Frontend improvement

### ISSUE THREAD

**Issue by rgex** [spryker/support#37]
Currently javascript events are declared this way:

> $('.js-shipment-button').click(....)

The problem is that if the part containing js-shipment-button is charged or recharged asynchroniously using ajax for example it won't bind the event to it.
A better solution is to use $(document).on('click', .

> $(document).on('click', '.js-shipment-button', function(event) { ..... });

**Comment by dereuromark** [comment]
You are right. We will look into improving this to be more AJAX supportive here.

**Comment by the-colorant** [comment]
@rgex thanks for the suggestion. I will close this issue as this is nothing we will be able to solve with a single release. However we will keep in mind to make improvements every time we work on a specific topic.
