### ISSUE TITLE
Delete Category Bug

### ISSUE THREAD

**Issue by tobi812** [spryker/support#38]
The deletion of Categories is not working properly:

In the `ProductCategoryManager` line 414 and 427 the `$idCategoryNode` is used, but the method `deleteCategoryRecursive` expects the `$idCategory`. In a lot of cases the ids are equal, but as soon as a category has more than one node, it is not working anymore.

**Comment by dereuromark** [comment]
Released in https://github.com/spryker/ProductCategory/releases/tag/2.0.1 .
