### ISSUE TITLE
Exception Stacktrace on CLI 

### ISSUE THREAD

**Issue by ridculy** [spryker/support#43]
The Exception Stacktrace on CLI is missing if ApplicationConstants::ZED_SHOW_EXCEPTION_STACK_TRACE ist false, spryker trys to render the ErrorPage.html on Comando Line Interface.  The ErrorPage does not make much sense on CLI, on CLI should be allways the Stacktrace.

Reproduce:
$config[ApplicationConstants::ZED_SHOW_EXCEPTION_STACK_TRACE] = false;

vendor/spryker/spryker/Bundles/Library/src/Spryker/Shared/Library/Error/ErrorHandler.php:handleException should haven an switch for CLI  when ZED_SHOW_EXCEPTION_STACK_TRACE is disabled.

**Comment by the-colorant** [comment]
The issues is solved. Please review this release https://github.com/spryker/Library/releases/tag/2.2.2.
