### ISSUE TITLE
Git prune in setupscript

### ISSUE THREAD

**Issue by newLoki** [spryker/support#44]
https://github.com/spryker/demoshop/blob/master/setup-functions.sh#L145

This one will delete all staling commits and branches and therefore is really dangerous, depending on the working mode for a project this is harmful.

**Comment by marius-rizac** [comment]
I got the same problem with this. setup should only take care of the installation process of application. should **NOT** touch git or anything else. live this duty to update git to developers. Don't do it automatically. 

More than that, I would make an option to disable `composer install` when we run setup script. There are many cases where we need to run setup script and have to change it in order to skip composer install and git optimizations

**Comment by dereuromark** [comment]
We need to remove cleanup things here.
We can either have a -c cleanup flag along with it for this to specifically opt-in for these things or have a separate cleanup.sh.
Never mix setup and cleanup.

**Comment by oliwier-spryker** [comment]
If you don't want to use composer install do not use `setup.sh -i`.

Use `setup -iy` or `setup -iz` for yves or zed.

**Comment by oliwier-spryker** [comment]
I can remove `git prune` as it's redundant cause it's called by `git gc` .
Now I don't understand the issue, you are describing. Is there  a way to duplicate it?

According to git documentation on `git prune`:

```
Users are encouraged to run this task on a regular basis within each repository to maintain good disk space utilization and good operating performance.

```

**Comment by dereuromark** [comment]
So to sum it up:
- Remove optimization or put it into `-o` "optimization" opt in flag.
- Please lets also have a `nc` for "no composer" flag - skipping the composer part!

In general the setup.vm should always run the same process, only with flags to skip or add things.
Right now it sometimes does sometimes does completely different things.
We need to clean this up to be more transparent!

dump and restore DB has nothing to do in there and should be an own sh script for example

**Comment by dereuromark** [comment]
This is now in the new demoshop. Please copy from there if you want to leverage the script.
