### ISSUE TITLE
AbstractTable uses static length/limit

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#45]
in AbstractTable:getLimit() a class property 'length' is used. This property can not be set or overwritten or is configurable. Also it is not possible to overwrite this abstract class to  insert project code.
So please make this property configurable somehow or even better, save the limit/length in a session, so when you change the "results shown per page" you don't have to do that all the time again.

**Comment by feversocial** [comment]
@AndromedaXP could you please specify your use case. What you want to achieve in your project, which issue do you have currently?

**Comment by AndromedaXP** [comment]
I want to specify a project specific table length, because 10 results is to less.
Also I remember from symfony, once a user changes the limit, this value is stored in session/cookie, so that the table looks every time the same.
e.g. our content team who are working a lot for cms content want to have a limit/length of 200 items to get a better overview. So they click on 200, but the next time they open the overview page the table will show only 10 results again... that's annoying.

**Comment by dereuromark** [comment]
Release as https://github.com/spryker/Gui/releases/tag/2.1.4 .
