### ISSUE TITLE
AbstractTable does not allow unspecific first column

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#46]
in AnstractTable:runQuery() is a TODO CD-412 since 07/15/15
I think it could cause my problem, when using as first column not a column from this table. Using this 'unspecific' column not as first is no problem but on first it will be used as `$orderColumn = $columns[$order[0]['column']]` and will result in an UnknownModelException.
Why is the first column and not the first sortable column from config used here anyways?

**Comment by dereuromark** [comment]
Solved with https://github.com/spryker/Gui/releases/tag/2.1.3 .

**Comment by AndromedaXP** [comment]
Only partly solved e.g. in AbstractTable:520 is an if with `(int)($order[0][self::SORT_BY_COLUMN]) > 0 ` which makes it impossible to sort a table by first column.

**Comment by AndromedaXP** [comment]
Deleting this if part brings another problem when no sortable columns are defined. Therefore there must be a empty array by default in AbstractTable:44
`private $sortableFields = [];`

**Comment by dereuromark** [comment]
Fixed in https://github.com/spryker/Gui/releases/tag/2.1.6

**Comment by dereuromark** [comment]
For "which makes it impossible to sort a table by first column" a ticket has been opened to reproduce and fix.

**Comment by AndromedaXP** [comment]
Which ticket, so I can follow up...
