### ISSUE TITLE
Migrationskripte will only created for one Shop

### ISSUE THREAD

**Issue by ridculy** [spryker/support#47]
The Propel Migrationskripts will only created for one Shop.

If you've two or more shops the Migrations will allways only created for one shop.

And the migrationfiles don't have Namespaces in it, so you must copy them und then rename the class and filename.

**Comment by ridculy** [comment]
Lucas has fixed that for us

**Comment by newLoki** [comment]
@FabianWesner Is there a fix for other projects too or @ridculy could you share the fix?
