### ISSUE TITLE
Category CRUD in Zed is only available for currentLocale()

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#48]
It is not possible in zed to edit a category (name, attributes, url, ...) for another locale besides current locale.

**Comment by the-colorant** [comment]
@AndromedaXP Solution for this issue has been delivered.

**Comment by AndromedaXP** [comment]
@the-colorant to whom? I didn't got any instructions...

**Comment by the-colorant** [comment]
The solution has been provided. You will be able to make use of it with the Version 2 upgrade.

**Comment by AndromedaXP** [comment]
Add a locale field to the form, does not seem to me an appropriate solution. If I have a page in multiple languages (which are like 9 languages for nearly every page for us) I have to add 9 different pages??
Sounds wrong to me because we had to deactivate 9 pages instead of one. There must a better solution.
