### ISSUE TITLE
CategoryFormAddDataProvider with optional $idParentNode

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#50]
Why is the `$idParentNode` in the CategoryFormAddDataProvider not optional? This is a form where the parent Category can be chosen from a dropdown anyways. So it would be not only nicer, also the `addCategory` button in ZED would work, without having a parentCategory by the hand.
Regarding to this, the AddController should also deal without the `ProductCategoryConstants::PARAM_ID_PARENT_NODE` parameter.

**Comment by oliwier-spryker** [comment]
It's is optional.
When you pass it, the related parent will be preselected in the 'Parent' drop down input.
If you don't nothing is preselected.

**Comment by the-colorant** [comment]
@AndromedaXP Do you still have any feedback or can we close this issue?

**Comment by AndromedaXP** [comment]
@the-colorant 
then u have other code, because i get an `InvalidArgumentException - Value is not numeric` when calling this url because first row in `AddController:indexAction` is `$idParentNode = $this->castId($request->get(ProductCategoryConstants::PARAM_ID_PARENT_NODE));`

**Comment by the-colorant** [comment]
@AndromedaXP thanks for the input and sorry for delayed answer. This is a usability discussion and opinions can vary here. In any case I want to inform you that working on this topic is not in our current focus. When revisiting Category bundle we will get back to you to ask concrete use cases and possibly include your feature request, but this is not in our current roadmap.

**Comment by oliwier-spryker** [comment]
`$idParentNode = $request->get(ProductCategoryConstants::PARAM_ID_PARENT_NODE);`

no `castId` there

**Comment by dereuromark** [comment]
This bug has been resolved in March in 1477. Should be in a release after that one.

**Comment by AndromedaXP** [comment]
Perfect. Looks good.
