### ISSUE TITLE
Circular reference on database level for customer <-> customer address

### ISSUE THREAD

**Issue by newLoki** [spryker/support#51]
The customer bundle has a circular reference on database level because `spy_customer` has a reference to `spy_customer_address` (`default_shipping_address` and `default_billing_address`).
The issue now is that `spy_customer_address` has a constraint to `id_customer` (`fk_customer`).

This causes a customer which can never be deleted or archived.

The fix could be to have the information if it is a default address for shipping or billing attached to the address itself and add a unique index for `fk_customer` and `is_default_billing` (same for `fk_customer` and `is_default_shipping`). 

This change probably breaks backward compatibility but a migration script should be easy to write.

**Comment by dereuromark** [comment]
You are absolutely right.
We have this fix on the agenda and will update here as soon as it has been resolved.

**Comment by hhebbo** [comment]
The issues is solved. Please review this release https://github.com/spryker/Customer/releases/tag/2.1.3
