### ISSUE TITLE
Customer registration without double opt in

### ISSUE THREAD

**Issue by newLoki** [spryker/support#52]
At the moment it is not possible to have a customer registration without a double opt in.

In our project we patched the customer therefore, but IMO this is a feature which is useful for other too.

We replaced https://github.com/spryker/spryker/blob/master/Bundles/Customer/src/Spryker/Zed/Customer/Business/Customer/Customer.php#L161-L169 with

``` php
if ($this->customerConfig->isDoubleOptInActive()) {
    $customerEntity->setRegistered(new \DateTime());
}

$customerEntity->save();

$customerTransfer->setIdCustomer($customerEntity->getPrimaryKey());
$customerTransfer->setCustomerReference($customerEntity->getCustomerReference());

if ($this->customerConfig->isDoubleOptInActive() && $customerEntity->getPassword() !== null) {
    $customerTransfer->setRegistrationKey($customerEntity->getRegistrationKey());
    $this->sendRegistrationToken($customerTransfer);
}
```

**Comment by the-colorant** [comment]
@newLoki thanks for your input. Sounds valid. We can potentially also offer both solutions. The feature request is not in our scope right now. I'll keep this issue open so we can get back to you with more details when working on it.

**Comment by tvaleriy** [comment]
I've moved this ticket here - https://spryker.ideas.aha.io/ideas/CUSTIDEAS-I-9. You can track the progress there.
I'm closing this ticket here.
