### ISSUE TITLE
Discount calculator depends on ProductOptions

### ISSUE THREAD

**Issue by tobi812** [spryker/support#53]
We tried to remove the following bundles from composer:

"spryker/product-option-cart-connector": "~2.0.0",
"spryker/product-option-discount-connector": "~1.0.0",
"spryker/product-option-exporter": "~2.0.0",
"spryker/product-option-wishlist-connector": "~2.0.0",
"spryker/product-option": "~2.0.0"

But it is not possible, because they are used in the DiscountCalculationConnector. Instead of that, there should be a separate Connector-Bundle, which deals with ProductOptionDiscounts. Furthermore we found a circle dependency between "spryker/product-option" and "spryker/product".

**Comment by dereuromark** [comment]
The cyclic dependency of product vs product option is resolved in our current master, we will soon ship a patch.

The other issue will also be taken care of with the next discount release.

**Comment by aurisl** [comment]
We have fixed it with our tax 3.0 release. Thank you for reporting.
