### ISSUE TITLE
How to copy static assets to public folder

### ISSUE THREAD

**Issue by mirsch** [spryker/support#54]
I'd like to copy a PDF file from my bundles assets folder or the projects assets folder to the public folder using antelope. What's the right approach to copy static files like PDFs?

**Comment by FabianWesner** [comment]
@abelspry Can you please answer this question.

**Comment by abelspry** [comment]
Hi @mirsch,
thanks for contacting us.
`antelope` is a system built on top of webpack, so you need to use webpack plugins in order to copy files.
Here is a good one:
https://www.npmjs.com/package/copy-webpack-plugin

Just add it to your project `package.json`, require it in the `yourtheme-yves.antelope.js` and use it following the documentation.
Let me know if you need further info.
Cheers.

**Comment by mirsch** [comment]
Hi @abelspry,

thanks for your reply. I don't want to add it in YVES, but in ZED.
How can I overwrite zed.antelope.js at project level?

**Comment by abelspry** [comment]
Hi @mirsch,
I'm preparing an example to help you out extending Zed.
Next week will be ready.

Cheers.

**Comment by mirsch** [comment]
Hi @abelspry,

it's Friday, the week is over.
I just want to link to a File. Nothing special here and I thought this is a job of a few minutes. The Ticket is 10 days old. 10 days! Is it that hard to copy a file from assets to public respectively to overwrite zed.antelope.js at project level?

best
Mirko

**Comment by abelspry** [comment]
Hi @mirsch,
you're totally right. 
Actually, the possibility to overwrite zed configuration at project level it's not that easy, and I'm changing Antelope to make this happens. 
I'm releasing the new version, and with it new documentation on how to do it.

I'm really sorry. I'll give you what I promised today.
Best.
Alessandro

**Comment by abelspry** [comment]
We release this morning. Thanks for the patience.

Alessandro

**Comment by abelspry** [comment]
Hi @mirsch,
new `antelope` release is out now: 2.1.0.

Now you can simply extend zed configuration:
- update your antelope version (run `npm i antelope -g`);
- add `copy-webpack-plugin` as a dependency of your project (or whatever you decide to use);
- add a new file in `@project/assets/Automation/zed-yourprojectname.antelope.js`;
- use this code to extend (in `zed-yourprojectname.antelope.js`):

```
const CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = config => {
    let copy = new CopyWebpackPlugin([
        { from: 'path/from/project/root', to: 'path/from/public/Zed/folder' }
    ]);

    config.plugins.push(copy);

    return config;
}
```
- run `antelope build [zed]`;

Let me know.
Sorry again for the delay.

Best.
Alessandro

**Comment by mirsch** [comment]
Hi @abelspry,

even if @the-colorant already closed this ticket before I had the chance to answer it: I just want to let you know that this works like a charm.

Thanks
Mirko

**Comment by abelspry** [comment]
Hi @mirsch,
sounds great! Thanks!

Cheers,
Alessandro
