### ISSUE TITLE
code sniffer deletes use statement

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#56]
A class with the following use/property declaration

```
use Pyz\Zed\Category\Persistence\CategoryQueryContainer;

/**
 * @property CategoryQueryContainer $queryContainer
 */
```

will be edited by code-sniffer by deleting the use statement.
But this one is used. Otherwise the property declaration must be set to FQN by code-sniffer

**Comment by dereuromark** [comment]
It is supposed to be FQN.

**Comment by dereuromark** [comment]
The sniffer should be doing that afaik.

**Comment by AndromedaXP** [comment]
`@method` maybe the same for complex return types...

**Comment by dereuromark** [comment]
method is already working fine. I just checked, so only property needs to be fixed.

What do you mean with complex types? Do you have any examples that break?

**Comment by dereuromark** [comment]
Fixed with https://github.com/spryker/code-sniffer/releases/tag/0.4.3

**Comment by AndromedaXP** [comment]
I just meant classes, for sure not for simple types e.g. string
