### ISSUE TITLE
Discounts are calculated twice for grandTotal in orderTransfer of CustomerOrderReader

### ISSUE THREAD

**Issue by MattGronwald** [spryker/support#57]
in \Spryker\Zed\Sales\Business\Model\Customer\CustomerOrderReader::hydrateOrderListCollectionTransferFromEntityCollection the Discount inside the orderTransfer is applied twice.

This results in wrong grandTotal in the list of orders inside the customer account view of Yves.

There seems to be an unnecessary call to the salesAggregatorFacade in line 85 which calculations should be part of the orderHydrator call of line 82 already.

**Comment by the-colorant** [comment]
Hi @MattGronwald. Thanks for your input. We are currently taking care of this bug.
We'll update this issue when it's released.

**Comment by the-colorant** [comment]
Hi @MattGronwald. We have a release for [Sales Bundle](https://github.com/spryker/Sales/releases/tag/2.1.2) which fixed this issue.
