### ISSUE TITLE
Race condition for delete in collector:export

### ISSUE THREAD

**Issue by newLoki** [spryker/support#58]
There is a race condition in https://github.com/spryker/Collector/blob/master/src/Spryker/Zed/Collector/Business/Exporter/Writer/Search/ElasticsearchWriter.php#L78 where the `Elastica\Exception\NotFoundException` could easily be catched to avoid such a race condition. 

What could happen is that the `collector:export` is triggered by a cronjob and by hand /deployment at once and then for the second call of `collector:export` the document which should be deleted is already gone, but the second call will fail without a need.
In this case the result "document x does not longer exists" is already fulfilled without doing anything and proven by the `Elastica\Exception\NotFoundException`.

**Comment by oliwier-spryker** [comment]
We have opened slack communication to investigate the issue. Please contact me for further discussion.

**Comment by the-colorant** [comment]
Fix was released as a patch to [Collector](https://github.com/spryker/Collector/releases/tag/3.1.1).
