### ISSUE TITLE
Cleanup touch table before every export run

### ISSUE THREAD

**Issue by newLoki** [spryker/support#59]
The touch table should be cleaned before every *:export to avoid doing operations (like a delete) on items which are not longer valid.

Our case was that we inactivated a product which was then removed by a cronjob (running *:export) and the following *:export failed, because the touch table was in an inconsistent state.
IMO cleanup and export are not decoupled as they are now.
I would rather suggest to run cleanup before each *:export, but then I don't see the case why they are split into two commands.

**Comment by oliwier-spryker** [comment]
We have opened slack communication to investigate the issue. Please contact me for further discussion.

**Comment by newLoki** [comment]
Seems like the issue is only https://github.com/spryker/support/issues/58, so I close this.
