### ISSUE TITLE
Scaling issue in OMS lock

### ISSUE THREAD

**Issue by newLoki** [spryker/support#60]
The algorithm for building the OMS lock identifier (https://github.com/spryker/Oms/blob/master/src/Spryker/Zed/Oms/Business/OrderStateMachine/LockedOrderStateMachine.php#L173) is not build to scale well as the identifier length can exceed the database column length (VARCHAR 255) easily when the length of the order item identifier increases (which is normal for an auto increment) and you have a higher amount of order items.

Let me give you one example, we assume we are running our business for several weeks and our order item identifier already reached 3 digits.
Now a customer want to buy 60 different things, all good as 60 * (3 + 1) - 1 = 239 (the 3 + 1 for the item identifier length plus separator).
But as soon as the order item identifier increases to a 4 digit length, the customer will not be longer able to buy 60 different items (60 * (4 + 1) = 299) due to the fact that the oms lock identifier has grown to 299 chars which will not longer fit in the database.

So I would propose to use a hash function to have always the same length for the identifier and also this would avoid this inefficient casting thing you do in the algorithm (please see attached patch file).
With a proper one like sha512 even the possibility of hash collisions should be nearly impossible.

In addition to the existence of this issue another one hits us, because of a wrong exception handling in https://github.com/spryker/Oms/blob/master/src/Spryker/Zed/Oms/Business/Lock/TriggerLocker.php#L59 it's nearly impossible to find if you have run into the issue or not.
Here it would help to include the catched propel exception into the new thrown exception to at least see the issue, as well as other propel related issues.

```patch

<+>UTF-8
===================================================================
--- vendor/spryker/oms/src/Spryker/Zed/Oms/Business/OrderStateMachine/LockedOrderStateMachine.php	(revision )
+++ vendor/spryker/oms/src/Spryker/Zed/Oms/Business/OrderStateMachine/LockedOrderStateMachine.php	(revision )
@@ -171,9 +171,10 @@
     protected function buildIdentifierForOrderItemIdsLock(array $orderItemIds)
     {
         $orderItemIds = array_unique($orderItemIds);
-        array_walk($orderItemIds, 'intval');
         asort($orderItemIds);
         $identifier = implode('-', $orderItemIds);
+        $identifier = hash('sha512', $identifier);
+
         return $identifier;
     }
```

**Comment by aurisl** [comment]
Thanks for reporting. You are right field length for this field is too low. An we will apply your patch.

**Comment by the-colorant** [comment]
Added to backlog.

**Comment by the-colorant** [comment]
Has been fixed and released as 2 patches for [Oms](https://github.com/spryker/Oms/releases/tag/3.0.5 ) and [StateMachine](https://github.com/spryker/StateMachine/releases/tag/1.0.4) bundles.
