### ISSUE TITLE
wrong created at date for customer orders 

### ISSUE THREAD

**Issue by tobi812** [spryker/support#61]
When a Customer creates an order, the `created_at` value of the customer is set in the order entity. Because it is populated by the CustomerArray:

https://github.com/spryker/spryker/blob/50335bf8dd90226981087feb709b3d06d6e21249/Bundles/Sales/src/Spryker/Zed/Sales/Business/Model/Order/OrderSaver.php#L156

To fix it, set the values that should be transferred from Customer to the Order explicitly:

```php
        $customer = $quoteTransfer->getCustomer();

        $salesOrderEntity->setFkCustomer($customer->getIdCustomer());
        $salesOrderEntity->setEmail($customer->getEmail());
        $salesOrderEntity->setFirstName($customer->getFirstName());
        $salesOrderEntity->setLastName($customer->getLastName());
        $salesOrderEntity->setOrderReference($this->orderReferenceGenerator->generateOrderReference($quoteTransfer));
        $salesOrderEntity->setIsTest($this->salesConfiguration->isTestOrder($quoteTransfer));
```

**Comment by the-colorant** [comment]
Added to backlog.

**Comment by the-colorant** [comment]
Has been fixed and released as a patch for [Sales](https://github.com/spryker/Sales/releases/tag/2.2.4) bundle.
