### ISSUE TITLE
Is there a reason why packages are not published at packagist?

### ISSUE THREAD

**Issue by stefankleff** [spryker/support#62]
It would be very helpful to have an overview which versions are available and use tools like versioneye.

**Comment by reiz** [comment]
@stefankleff If the repo is accessible from outside we can add it to the VersionEye crawlers. Probably it will be integrated this week!

**Comment by newLoki** [comment]
@reiz I think the necessary information would be which versions are available, so something like the information provided by packagist.org so a project like ours could use VersionEye.
To be honest, we don't care if Spryker uses VersionEye or not, but as we would be up to date with the newest versions, when ever feasible, we would need to have this information.

As I thought you already use  ToranProxy isn't there a possibility to either provide this information via ToranProxy or publish the packages to packagist (as they are already public)?

**Comment by dereuromark** [comment]
Please see http://spryker.github.io/release/atomic-release/#checking-for-newer-versions as to how to how up to date you are with current versions. This is basically the same thing, just on command line level.

**Comment by hhebbo** [comment]
@stefankleff @reiz I'm Hussam from the Spryker core team.
Thanks for your question. We are using our own Packagist, it's called ToranProxy. ToranProxy is exactly like Packagist and developed also by Jordi, the lead developer and maintainer of Composer and Packagist.
The main difference between them is that ToranProxy is more suitable for private use, which is the case for Spryker. It gives us the ownership of our packages, the ownership of the ToranProxy code in our implementation, so we can add new functionalities and features that support our needs.

Regarding your request, Spryker customers get an update of all our new releases every two weeks for now. However, I agree that having something to show all the versions would be helpful.

**Comment by hhebbo** [comment]
@newLoki we do care about our customers and letting them having the best experience using our software, could you please mention at which project you work at, you mentioned 'project like ours', which project do you mean? :)

**Comment by newLoki** [comment]
@dereuromark Thx for mentioning this tool.
But we have set up VersionEye to check the license and version of each dependency when ever there is a pull request made, so we can ensure that now dependency with a known security issue, a unknown license or an outdated version is merged into our main branch.
This is something which, as far as I understood the tool you mentionend, has to be build ourself then.

@hhebbo The provided package.json from https://code.spryker.com/repo/private/packages.json seem to be broken (missing information) so it could not used for VersionEye.
I'm currently working for the same project as @stefankleff also does.
For us it's not only about updates but also about license changes and security notifications as mentioned above which is mainly interesting for other 3rd party packages either we or spryker use and sadly propel for example is not sending us a release mail ;)

**Comment by hhebbo** [comment]
@newLoki okay I see :) it's a valid point. We'll take care of that. Thanks for your inquiry.

**Comment by hhebbo** [comment]
For such general questions, please use our forum: http://discuss.spryker.com
Will add this feature to our backlog and will close this ticket. Thanks.
