### ISSUE TITLE
There should be a DiscountableExpenseTransfer

### ISSUE THREAD

**Issue by rgex** [spryker/support#63]
Currently collectors can only return DiscountableItemTransfer and collect items. There should also be a DiscountableExpenseTransfer in order to collect expenses such as Shipping costs.

**Comment by aurisl** [comment]
For shipment you can use DiscountableItemTransfer, Discount engine does not need to know implementation details, only data for calculation. It is: price, quantity and have reference to original calculated discount object to apply discount.

**Comment by rgex** [comment]
Ok, I got it working
