### ISSUE TITLE
Hard coded default time zone

### ISSUE THREAD

**Issue by mirsch** [spryker/support#64]
`date_default_timezone_set` ist hard coded to use UTC. 
see https://github.com/spryker/Library/blob/master/src/Spryker/Shared/Library/Application/Environment.php#L33
There is a config option `$config[ApplicationConstants::PROJECT_TIMEZONE]` (https://github.com/spryker/demoshop/blob/master/config/Shared/config_default.php#L35)  which suggest to change the Time Zone of the Project but it don't do it.

**Comment by the-colorant** [comment]
Hi @mirsch. You are right. Currently we don't have global settings for this. 
We do have the internationalisation concept as an item in our backlog. With this we will have a central place to format numbers, prices, dates, as well as a central place for converting timezones. 
But for now you can either wait for us to work on the topic or extend the solution on you project side. 

I will keep this issue open for now. We will post an update when we start working on the issue and when it's released. Thanks for your input.

**Comment by tvaleriy** [comment]
I've moved this ticket here - https://spryker.ideas.aha.io/ideas/CUSTIDEAS-I-10. You can track the progress there.
I'm closing this ticket here.
