### ISSUE TITLE
PHP 7 Support

### ISSUE THREAD

**Issue by stefankleff** [spryker/support#65]
Is there already an update? Our last known status is, that there are still some flaws.

**Comment by the-colorant** [comment]
@stefankleff We do not plan to migrate anytime soon, but assuring compatibility is in our current backlog. 

_For future please use our [forum](http://discuss.spryker.com/) for generic questions. This is a type of question other community members might also be interested to hear about. We would highly appreciate keeping the history of questions like this active in the forum._

**Comment by newLoki** [comment]
@the-colorant  http://discuss.spryker.com/t/php-7-support-for-spryker/78 ;)

**Comment by the-colorant** [comment]
Thanks :)
