### ISSUE TITLE
Storage Bundle 2.1.4 broken

### ISSUE THREAD

**Issue by stefankleff** [spryker/support#66]
We cannot use the current StorageBundle because of the use of the wrong constants.

Example:
https://github.com/spryker/Storage/blob/master/src/Spryker/Shared/Storage/Provider/AbstractKvProvider.php#L73

1. I think it should be StorageConstants instead of SessionConstants (That is what the version is about)
2. The corresponding use statement is missing

**Comment by the-colorant** [comment]
Added to backlog. I will post an update here once fixed.

**Comment by the-colorant** [comment]
@stefankleff the fix has been released as a patch for [Storage](https://github.com/spryker/Storage/releases/tag/2.1.5) bundle.
