### ISSUE TITLE
Current guzzle dependency has security issues

### ISSUE THREAD

**Issue by stefankleff** [spryker/support#67]
Currently the spryker/guzzle bundle has a dependency to guzzlehttp/guzzle >=6.1.1 <6.2.0
but the latest available guzzle version in this range 6.1.1 is officially marked as vulnerable (see https://github.com/guzzle/guzzle/blob/master/CHANGELOG.md#621---2016-07-18) and the tilde operator doesn't allow an update. 

Please update the dependency to at least guzzle 6.2.1

**Comment by the-colorant** [comment]
@stefankleff we are looking into this now. Thanks for the input.

**Comment by the-colorant** [comment]
Guzzle HTTP is now updated to v6 and therefore now complies with PSR7. See the release page [here](https://github.com/spryker/Guzzle/releases/tag/2.1.0). Additionally some more bundles have been released to update the Guzzle HTTP usage. More details on this will be published in release notes early next week (August 2nd release) at http://spryker.github.io/.
