### ISSUE TITLE
maintenance/php-info broken

### ISSUE THREAD

**Issue by mirsch** [spryker/support#68]
php info in maintenance bundle is broken because of a typo in template folder name
https://github.com/spryker/Maintenance/tree/master/src/Spryker/Zed/Maintenance/Presentation/Phpinfo
is ```Phpinfo``` should be ```PhpInfo```

**Comment by dereuromark** [comment]
This is fixed in [2.0.1](https://github.com/spryker/Maintenance/releases/tag/2.0.1) release.
