### ISSUE TITLE
Ratepay - PAYMENT_REQUEST - Bug in shipping costs

### ISSUE THREAD

**Issue by joergstick** [spryker/support#69]
The value used to export shipping costs in PAYMENT_REQUEST is not correct. In BasketMapper the expense total is used.
`$shippingUnitPrice = $this->centsToDecimal($totalsTransfer->requireExpenseTotal()->getExpenseTotal());`
The expense total only works in demoshop because there are no other expenses like packaging costs or customs duty... Other costs would be included in shipping costs. 

I think the way to go is `$this->centsToDecimal($expense->getSumGrossPriceWithDiscounts())` form the expense of type `ShipmentConstants::SHIPMENT_EXPENSE_TYPE`

(or `getUnitGrossPriceWithDiscounts` instead of `getSumGrossPriceWithDiscounts`)

(This popped up because at wine in black shipping costs are always assigned to an order and free shipping is realized via cart rule. The cart rule applies a discount to shipping expense so that it is 0€ and not included in grand total after calculation. ratepay payment_request allways exports shipping using expense total. if ratepay api sums up the basket items / shipping / discounts it does not fit with the exported grand total...)

Did a quick fix overwriting BasketMapper class:

`class BasketMapper extends CoreBasketMapper
{

```
const DEFAULT_SHIPPING_UNIT_PRICE = 0;

/**
 * @return void
 */
public function map()
{
    $totalsTransfer = $this->quoteTransfer->requireTotals()->getTotals();
    $grandTotal = $this->centsToDecimal($totalsTransfer->requireGrandTotal()->getGrandTotal());

    $shoppingBasketTransfer = new RatepayRequestShoppingBasketTransfer();
    $shoppingBasketTransfer->setAmount($grandTotal);
    $shoppingBasketTransfer->setCurrency($this->ratepayPaymentTransfer->requireCurrencyIso3()->getCurrencyIso3());

    $this->mapShipping($shoppingBasketTransfer, $this->quoteTransfer);
    $this->mapDiscount($shoppingBasketTransfer, $this->quoteTransfer);

    $this->requestTransfer->setShoppingBasket($shoppingBasketTransfer);
}

/**
 * @param \Generated\Shared\Transfer\RatepayRequestShoppingBasketTransfer $shoppingBasketTransfer
 * @param \Generated\Shared\Transfer\QuoteTransfer $quoteTransfer
 * @return void
 */
protected function mapShipping(
    RatepayRequestShoppingBasketTransfer $shoppingBasketTransfer,
    QuoteTransfer $quoteTransfer
) {
    $shoppingBasketTransfer->setShippingTitle(self::DEFAULT_SHIPPING_NODE_VALUE);
    $shoppingBasketTransfer->setShippingUnitPrice(self::DEFAULT_SHIPPING_UNIT_PRICE);
    $shoppingBasketTransfer->setShippingUnitPrice(self::DEFAULT_SHIPPING_TAX_RATE);

    foreach ($quoteTransfer->getExpenses() as $expense) {
        if ($expense->getType() === ShipmentConstants::SHIPMENT_EXPENSE_TYPE) {
            $shoppingBasketTransfer->setShippingUnitPrice(
                $this->centsToDecimal($expense->getSumGrossPriceWithDiscounts())
            );
            $shoppingBasketTransfer->setShippingTaxRate(
                $this->formatTaxRate($expense->getTaxRate())
            );

            break;
        }
    }
}

/**
 * @param \Generated\Shared\Transfer\RatepayRequestShoppingBasketTransfer $shoppingBasketTransfer
 * @param \Generated\Shared\Transfer\QuoteTransfer $quoteTransfer
 * @return void
 */
protected function mapDiscount(
    RatepayRequestShoppingBasketTransfer $shoppingBasketTransfer,
    QuoteTransfer $quoteTransfer
) {
    $shoppingBasketTransfer->setDiscountTitle(self::DEFAULT_DISCOUNT_NODE_VALUE);
    $shoppingBasketTransfer->setDiscountUnitPrice(self::DEFAULT_DISCOUNT_UNIT_PRICE * self::BASKET_DISCOUNT_COEFFICIENT);
    $shoppingBasketTransfer->setDiscountTaxRate(self::DEFAULT_DISCOUNT_TAX_RATE);
}

/**
 * @param float $taxRate
 * @return string
 */
protected function formatTaxRate($taxRate)
{
    return number_format($taxRate, 2, '.', '');
}
```

}`

**Comment by alex-galych** [comment]
Hi @joergstick,

Sorry for delay with response but I'm not sure that you have found correct way to fix you issue with wrong expense prices.

As I understood your problem is that you've multiple shipping expenses and than you've wrong expense price. But as you can see from your code example BasketMapper works with quote total transfer, which always has to contain correct final prices.

Just small explanation, for expsense prices as well as for example discounts Spryker has split for expenses and discounts in quote and order transfers and has aggregated  prices for them in total trasnfer.

So, if you would like to have multiple shippment expenses, you have to add your custom shipment expense to quote transfer shipment expenses field. Or you can have your of expenses in quote, something like CarrrierExpenses, but in this case you have to add your own [Calculator](http://spryker.github.io/tutorials/zed/calculator-plugin/) to add custom expense prices to total expense price.

**Comment by joergstick** [comment]
from my point of view spryker just does it wrong as i explained

**Comment by aurisl** [comment]
You are right that payments should not use expenseTotal directly, it should take amount from expenses with type shipment. I would recommend to include new total into `TotalsTransfer::shipmentExpenseTotal`  and calculator for this, that would me value more explicit and clear.
