### ISSUE TITLE
Order Overview Limit ignored

### ISSUE THREAD

**Issue by harmavenso** [spryker/support#70]
method querySalesOrdersByCustomerId() in the Spryker\Zed\Sales\Persistence\SalesQueryContainer ignores it's $criteria param, and as a result the overview of orders in the customer account has no limit.

**Comment by dereuromark** [comment]
This is indeed missing the usage of $criteria to build the query.
For now you can add this on project level extension for SalesQueryContainer::querySalesOrdersByCustomerId():

```php
        if ($criteria !== null) {
            $query->mergeWith($criteria);
        }
```

**Comment by dereuromark** [comment]
This is resolved with https://github.com/spryker/Sales/releases/tag/2.2.8
