### ISSUE TITLE
spy_sales_order_item_option not filled

### ISSUE THREAD

**Issue by harmavenso** [spryker/support#71]
The SpySalesOrderItemOption table (spy_sales_order_item_option) remains empty after multiple orders, with different options are made. 

It appears this OrderSaverPlugin has not been properly migrated after the v2 push of the checkout.

**Comment by harmavenso** [comment]
Closed as this might be caused by data setup.

**Comment by harmavenso** [comment]
Also with a fresh dataset, this table doesn't get filled after placing an order.

**Comment by aurisl** [comment]
Hi,

Do you have new ProductOptionOrderSaverPlugin(), added in checkout order saver plugin list?

**Comment by harmavenso** [comment]
It is part of the getCheckoutOrderSavers in the project CheckoutDependencyProvider, yes.

**Comment by aurisl** [comment]
If plugin is there, then you don't have option in `CheckoutResponseTransfer::orderItems()` which comes from quote transfer. I would try debug and get more information what are you missing, right now looks good to me.

**Comment by the-colorant** [comment]
@harmavenso please keep us posted on the status of your issue and let us know if you have more questions. We will keep this issue open till your problem is resolved.

**Comment by harmavenso** [comment]
I'm closing this ticket as with a completely fresh code/data setup I'm unable to reproduce this behavior.
