### ISSUE TITLE
OMS > 3.0.5 broken

### ISSUE THREAD

**Issue by stefankleff** [spryker/support#74]
$processedOrderItems could be unitialized in
https://github.com/spryker/Oms/blob/3.0.7/src/Spryker/Zed/Oms/Business/OrderStateMachine/OrderStateMachine.php#L196

Also the variable is overwritten on every loop iteration and therefore only the results of the last iteration will be passed to filterItemsWithOnEnterEvent() .

**Comment by dereuromark** [comment]
We will be releasing a fix for the regression tomorrow. Please use 3.0.5 until then.

**Comment by the-colorant** [comment]
Oms was released: [Oms 3.0.8](https://github.com/spryker/Oms/releases/tag/3.0.8)
