### ISSUE TITLE
ZED GUI table sorting concept wrong?

### ISSUE THREAD

**Issue by stefankleff** [spryker/support#77]
It looks like that all tables in ZED have a flaw regarding how sorting works:

Observed behaviour:
If you click on a sortable column header, a numerical index (starting at 0 for the first column) is added to the request which determines the sorting order of the table. For the first request the parameter is omitted. (see https://github.com/spryker/Gui/blob/master/src/Spryker/Zed/Gui/Communication/Table/AbstractTable.php#L541) 

We have extended the customer entity with several additional attributes. Now our customer table is by default sorted by "spy_customer.phone", because it's the first column in the generated SpyCustomerTableMap class.

What we expected:
The default sorting is by id. Additionally we expected to get a working sorting by the following config:
```
        $config->setHeader([
            self::COL_ID_CUSTOMER => '#',
            self::COL_CREATED_AT => 'Registration Date',
            self::COL_EMAIL => 'Email',
            self::COL_LAST_NAME => 'Last Name',
            self::COL_FIRST_NAME => 'First Name',
            self::COL_ZIP_CODE => 'Zip Code',
            self::COL_CITY => 'City',
            self::COL_FK_COUNTRY => 'Country',
            self::ACTIONS => self::ACTIONS,
        ]);

        $config->setSortable([
            self::COL_ID_CUSTOMER,
            self::COL_CREATED_AT,
            self::COL_EMAIL,
            self::COL_LAST_NAME,
            self::COL_FIRST_NAME,
            self::COL_ZIP_CODE,
            self::COL_CITY,
        ]);
```

**Comment by dereuromark** [comment]
Did you also set the default sort column index and optionally the default order?
```php
$config->setDefaultSortColumnIndex([$indexAsInteger]);
$config->setDefaultSortDirection([\Spryker\Zed\Gui\Communication\Table\TableConfiguration::SORT_ASC|_DESC]);
```

That is usually the way to provide a different default column to sort by.

**Comment by stefankleff** [comment]
I digged a little deeper and it seems that the only problem is, that the table cannot sort properly by column with index 0. Because if 0 is used, always the firstAvailableColumnInQuery() is used. (see AbstractTable::getOrderByColumn()) 

This does not work, if the first column in the table is not the same as the first column in the TableMap.

**Comment by dereuromark** [comment]
Just to confirm (please always provide that info in your ticket):
You are using the latest version here for Gui bundle as well as the bundle in question?

Because we cannot reproduce this with the current version, and I do remember there was a fix for it a while back.

**Comment by dereuromark** [comment]
@stefankleff Can you please confirm that the default order setup (2 lines above) will solve your issue?
We will then add this to the documentation, since it seems to be missing so far from there.

**Comment by dereuromark** [comment]
We updated the documentation accordingly.
