### ISSUE TITLE
TouchBundle bulkTouchSetXXX is buggy

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#78]
This is a

* [x] bug
* [ ] enhancement

We use Spryker/Touch bundle version 2.2.2.

When calling touchFacade > bulkTouchSetXXX the Classes IdFilterInsert and IdFilterUpdate are used. When having more $ids than the CHUNK_SIZE is, arrays will be aggregated with `+=` which works only for associated arrays. In this case the $filteredIds will never have more than 250 results. Usage of array_merge is probably a better solution.

IdFilterInsert:31
IdFilterUpdate:33
IdFilterUpdate:35

**Comment by dereuromark** [comment]
I agree that += should really only be used with string key based array structures.

**Comment by AndromedaXP** [comment]
thanks.

**Comment by dereuromark** [comment]
Resolved with https://github.com/spryker/Touch/releases/tag/2.2.3
Thank you for reporting this.

**Comment by AndromedaXP** [comment]
thanks for fixing.
