### ISSUE TITLE
onDelete="CASCADE" missing in cross-tables

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#79]
This is a
- [x] bug
- [ ] enhancement

Usage of Tax bundle 3.0.4

Like in multiple other bundles (I can write other tickets for that), the foreign keys of m-n-tables are not marked as onDelete="CASCADE". This should be the default and only left out if there is a serious reason. I don't see any for `spy_tax_set_tax.fk_tax_rate` why onDelete="CASCADE" was omitted.

**Comment by aurisl** [comment]
Yes you are right, cascade is missing, we will add this with next major.

**Comment by dereuromark** [comment]
As this is BC breaking potentially, we must find a way for projects to opt-in this for the time being, and in future majors we will have to ship this by default then.
A list of all affected bundles would be nice, here as a comment. So we can check them off and compare with our findings.

**Comment by AndromedaXP** [comment]
spy_category_attribute (fk_locale, fk_category)
spy_price_product (fk_price_type)
spy_product (fk_product_abstract)
spy_product_abstract_localized_attributes (fk_locale)
spy_product_category (fk_category, fk_product_abstract)
spy_product_localized_attributes (fk_locale)
spy_product_option_type_usage (fk_product_option_type)
spy_product_option_value_usage (fk_product_option_value)
spy_touch_search (fk_locale, fk_touch)
spy_touch_storage (fk_locale, fk_touch)
spy_shipment_method (fk_shipment_carrier)

and still some more but not important ones...

**Comment by the-colorant** [comment]
Hi @AndromedaXP. Deletion of the data must always be explicit. Cascading is dangerous because you can by mistake delete data from other tables. In general we do not recommend to delete data, please rather use deactivation. 

As we do not plan to follow up here I will be closing the issue. 

Thanks for your contribution!
