### ISSUE TITLE
NewRelic missing method in deployment command

### ISSUE THREAD

**Issue by stefankleff** [spryker/support#80]
In the last refactoring the method createNewRelicApi() was renamed to getNewRelicApi()

https://github.com/spryker/NewRelic/blob/2.1.1/src/Spryker/Zed/NewRelic/Communication/Console/RecordDeploymentConsole.php#L96

This is a

* [x] bug
* [ ] enhancement

For questions please consult the [Spryker Forum](http://discuss.spryker.com/).

If possible please provide the exact versions of the bundles involved.

### What you did
Deploy

### Actual Behavior
Exception

### Expected Behavior
Record new Relic deployment

**Comment by stereomon** [comment]
The bug is fixed in NewRelic bundle 2.1.2
