### ISSUE TITLE
Make fatal errors array in error handler more accessible.

### ISSUE THREAD

**Issue by icambridge** [spryker/support#81]
This is a

* [ ] bug
* [X] enhancement

For questions please consult the [Spryker Forum](http://discuss.spryker.com/).

If possible please provide the exact versions of the bundles involved.

### What you did

Extended the Environment and attempted to use the fatal errors array.

### Actual Behavior

It was a private member

### Expected Behavior

It was a protected member

### Change 
So `\Spryker\Shared\Library\Application\Environment` line 12 needs changed from `private static $fatalErrors = [` to `protected static $fatalErrors = [`.

**Comment by dereuromark** [comment]
From what I can see that is a part of the deprecated initializeErrorHandler() method.
You should be using the outlined new ErrorHandlerEnvironment instead, which also has the correct property as protected one.
Let me know if that resolves your issue.

**Comment by icambridge** [comment]
@dereuromark I just did a search for Classname and I can't find a `ErrorHandlerEnvironment` in PHPStorm

**Comment by dereuromark** [comment]
This is part of the new [ErrorHandler](https://github.com/spryker/ErrorHandler) bundle. Maybe you are not on the latest version?

**Comment by icambridge** [comment]
Looks like we're not on the latest copy. :(
