### ISSUE TITLE
Missing interface implementation at DiscountCalculatorPlugin

### ISSUE THREAD

**Issue by d-gerken** [spryker/support#83]
vendor/spryker/discount/src/Spryker/Zed/Discount/Dependency/Plugin/DiscountCalculatorPluginInterface.php does not implement the correct interface from Calculator Plugin.

Now it looks like:
`interface DiscountCalculatorPluginInterface`

But it should look like this:
`interface DiscountCalculatorPluginInterface extends CalculatorPluginInterface`

Therefore the following classes from the discount module must implement the recalculate method from CalculatorPluginInterface:

- Spryker\Zed\Discount\Communication\Plugin\Calculator\FixedPlugin
- Spryker\Zed\Discount\Communication\Plugin\Calculator\PercentagePlugin

**Comment by dereuromark** [comment]
:+1: Thank you for pointing that out. We will patch this accordingly, as this is a valid improvement.
We will inform you about the progress.

**Comment by dereuromark** [comment]
Actually, it turns out the methods are different, calculate() vs recalculate().
Those are doing two different things, thus the different interfaces.

**Comment by d-gerken** [comment]
Hm. But something must be still wrong. 
In the demostore Pyz\Zed\Calculation\CalculationDependencyProvider in the getCalculatorStack method the DiscountCalculatorPlugin() is used but the CalculatorPluginInterface is nowhere implemented in the discount calculator.

**Comment by dereuromark** [comment]
Bundles in Pyz do not have to reflect the bundles in Zed though. The stack method should maybe be named getDiscountCalculatorStack() as it seems to be used inside the Discount core bundle (and inside project) only. So the name just is the same by accident, without the functional overlap here, if I am not mistaken.

**Comment by aurisl** [comment]
Hi, @dereuromark  is right those are different calculators in discount bundle. Its for different discount type.  The one used in Calculator bundle is from `DiscountCalculatorConnector` bundle. And they implement `CalculatorPluginInterface`.

**Comment by d-gerken** [comment]
Ok, thanks for the explanation. No bug, therefore closed.
