### ISSUE TITLE
QueryBuilder is too narrow

### ISSUE THREAD

**Issue by lmanzke** [spryker/support#84]
This is a

* [X] bug
* [ ] enhancement

The query builder for Propel entities is too narrow.

Consider the following snippet built by the Spryker Query Builder (```\Spryker\Zed\Propel\Business\Builder\QueryBuilder```):

```
    public function filterBySku($sku = null, $comparison = Criteria::EQUAL)
    {
        if ($comparison == Criteria::LIKE) {
            $sku = str_replace('*', '%', $sku);
        }

        if ($comparison !== Criteria::IN && is_array($sku)) {
            throw new AmbiguousComparisonException('$sku of type array requires explicit Criteria::IN as comparison criteria.');
        }

        return $this->addUsingAlias(SpyProductTableMap::COL_SKU, $sku, $comparison);
    }
```

This throws an AmbiguousComparisonException with the following params:
```['sku' => ['sku1', 'sku2'], 'comparison' => Criteria::NOT_IN]```

That is not correct. NOT_IN should also be possible to be used in conjunction with an array value - and possible more operators too. This should be changed.

**Comment by dereuromark** [comment]
Closing as this is already on the internal fast track to be fixed this week.
