### ISSUE TITLE
Antelope 2.1.2 leads to known npm bug

### ISSUE THREAD

**Issue by stefankleff** [spryker/support#85]
This is a
- [x] bug
- [ ] enhancement

antelope 2.1.2
npm / node in various combinations.
### What you did

"sudo antelope install"
### Actual Behavior

`15:35:14 Installing npm modules dependencies...   
15:35:53 npm ERR! Linux 3.16.0-4-amd64    
15:35:53 npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--no-bin-links"   
15:35:53 npm ERR! node v6.2.2
15:35:53 npm ERR! npm  v3.9.5
15:35:53
15:35:53 npm ERR! Maximum call stack size exceeded`

See:
https://github.com/npm/npm/issues/10776
https://github.com/npm/npm/issues/9239
### Expected Behavior

npm dependencies should be installed

https://github.com/spryker/antelope/blob/master/lib/install.js#L21

**Comment by abelspry** [comment]
Hi @stefankleff, thanks for your ticket!
I'm trying to recreate this error, but I can't indeed. 

Can you post here your machine and OS specifications? Maybe I can find the problem in a better way and try to solve it faster.
Thanks.

Cheers. Alessandro

**Comment by dereuromark** [comment]
From the linked Github tickets, there seems to be a solution/workaround described:

> I can echo this same issue is happening. When I try to publish a module with npm 3.3.4 and have anything in my node_modules folder I get this error. If I delete my node_modules folder, publish works fine.

Is that helping?
Then this would be easy to implement in the script I imagine.

**Comment by stefankleff** [comment]
@dereuromark We have tried every proposed way to work around that - But nothing worked. The node_modules folder is created on each deployment.

@abelspry 
Production: Debian 3.16.0-4-amd64
Other Environments: Vagrant VMs (on Debian Host)
If you like to, you can come over have a look. This seems to be a heisenbug in npm :/

**Comment by abelspry** [comment]
I'm working on a new antelope version to fix this problem. I'll keep you update.

**Comment by abelspry** [comment]
New version has been released. Antelope 2.2.0.
Issue fixed by latest release.
