### ISSUE TITLE
Wrong HTTP status code check in setup:jenkins:generate

### ISSUE THREAD

**Issue by stefankleff** [spryker/support#86]
This is a

* [x] bug
* [ ] enhancement

Setup Bundle, Latest version
https://github.com/spryker/Setup/blob/master/src/Spryker/Zed/Setup/Business/Model/Cronjobs.php#L242

$code is of type int. String check is always false.

Overwrite in project code is not possible, because prepareJobXml() is private.

### What you did
console: setup:jenkins:generate

### Actual Behavior
It's not shown that the job is not updated

### Expected Behavior
Include the string '400: already exists'
Or better: Replace the whole "CREATE ..." message with "SKIPPED ... "

**Comment by dereuromark** [comment]
I can see that there is a TODO and

    $existingJobs = $this->getExistingJobs();

is not even used yet.
Based on that we could indeed skip.
What you you mean with replacing - do you have an example output of the desired content?

**Comment by dereuromark** [comment]
My example output of the fixed version is:

```
SKIPPED jenkins job: createItem?name=DE__send-mails (already exists)
SKIPPED jenkins job: createItem?name=DE__export-kv (already exists)
SKIPPED jenkins job: createItem?name=DE__export-search (already exists)
SKIPPED jenkins job: createItem?name=DE__update-search (already exists)
SKIPPED jenkins job: createItem?name=DE__check-oms-conditions (already exists)
SKIPPED jenkins job: createItem?name=DE__check-oms-timeouts (already exists)
SKIPPED jenkins job: createItem?name=DE__clear-oms-locks (already exists)
```

**Comment by dereuromark** [comment]
All mentioned issues resolved with https://github.com/spryker/Setup/releases/tag/2.0.7
Thank you for reporting it.
