### ISSUE TITLE
Billing address not being saved to customer.

### ISSUE THREAD

**Issue by icambridge** [spryker/support#87]
This is a Bug. 

We have the Customer 2.1.7 and we haven't overridden the order saver. 

*Current:*
Customer completes purchase with a separate billing address. The billing address is not saved in the Customer account (in Zed or My Addresses). It is correctly saved on Order. 

*Expected:*
1. Billing address is added to Customer Account. It is viewable in My Addresses and in Zed .
2. Where no default billing address is saved, save it as default billing address (My Account and ZED).

**Comment by kbischoff** [comment]
With the current version the bug cannot be recreated. Both addresses are displayed in the customer account in Yves as well as the customer UI in Zed.

**Comment by dereuromark** [comment]
We will close this for now. Please let us know if we need to reopen. We will need further information here then, though.
