### ISSUE TITLE
code:sniff doesn't fix newline missing

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#88]
This is a

* [x] bug
* [ ] enhancement

spryker/code-sniffer dev-master from 10/31/16

### What you did

run vendor/bin/console code:sniff -f

### Actual Behavior

Processing ProductOptionFacade.php [PHP => 1210 tokens in 208 lines]... DONE in 104ms (2 fixable violations)
        => Fixing file: 2/2 violations remaining [made 50 passes]... ERROR in 6.12 secs

### Expected Behavior

There was a newline missing after the last function which was not fixed by codesniffer.
File rights were 644

**Comment by dereuromark** [comment]
What is the code it was trying to fix?
Can you please paste that?

Also please note that there is a new release out that might actually fix that issue.

**Comment by AndromedaXP** [comment]
Just a missing newline between the last function and class closing bracket
...
    }
}
==>
...
    }

}

**Comment by dereuromark** [comment]
That is fixed with the latest release.

**Comment by AndromedaXP** [comment]
ok, thx

**Comment by dereuromark** [comment]
Please confirm and close if I am correct.

**Comment by AndromedaXP** [comment]
Yes it worked.
