### ISSUE TITLE
Search Bundle Client - Query Builder for Geo-point datatype

### ISSUE THREAD

**Issue by mruoss** [spryker/support#89]
This is an

* [ ] enhancement

Hi there,
Are there any plans to add functionality (query expanders, config builder plugins,...) to support the elasticsearch [geo-point datatype](https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-point.html)?

For a store-finder we would like to create queries including the following:

* [Distance filter](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-distance-query.html)
* [Bounding box filter](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-bounding-box-query.html)
* [Geo distance sorting](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#geo-sorting)

Thanks,
Michael

**Comment by dereuromark** [comment]
At this point we do not have this on the roadmap.
But this sounds interesting - if you implemented any of this on your side and want to share that for a future core integration, please let us know.

**Comment by mruoss** [comment]
I implemented config builders and query expander plugins for the three things I mentioned above. 

* new classes `GeoFilterConfigBuilder` and `GeoFilterQueryExpanderPlugin` for distance and bounding box filters
* extended core classes `SortConfigBuilder` and `SortedQueryExpanderPlugin` for distance sorting

Let me know if you're interested in that code and if so, how I can provide it.
Obviousely, it currently resides in the Pyz namespace of our project and I had to extend a few classes from Spryker core. But as far as I can tell, it should be straight forward to merge it back to core if you wanted.

**Comment by the-colorant** [comment]
Thank you for your suggestion. We added it to our backlog. Please keep in mind there is no timeline for this feature request.

Please subscribe to our [release newsletter](http://spryker.us9.list-manage.com/subscribe?u=2d9ae57e9daa93c97f842a702&id=8ef00c0edd) for release notifications!

**Comment by mruoss** [comment]
No problem. Still, let me know if you want me to share the code with you.
