### ISSUE TITLE
Header of Product Category Table missing

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#90]
This is a

* [x] bug
* [ ] enhancement

For questions please consult the [Spryker Forum](http://discuss.spryker.com/).

If possible please provide the exact versions of the bundles involved.
            "name": "spryker/product-category",
            "version": "dev-beta/category-locales",

### What you did
Edit a category

### Actual Behavior
The table of assigned products is without a header.
![image](https://cloud.githubusercontent.com/assets/12390718/20626158/2af0fdf6-b318-11e6-9f7b-e37f36cee822.png)

The header of the to-assigned-products-table has a misplaced header
![image](https://cloud.githubusercontent.com/assets/12390718/20626275/f3ade0c4-b318-11e6-8f61-f346e42e6803.png)

### Expected Behavior
The header of the assigned-products-table is shown.
The header of the correct to-assigned-products-table is shown and not a dummy table header from product-category/Predentation/Edit/index.twig:102-113 and 140-151

**Comment by dereuromark** [comment]
The new Product release coming beginning of next week will fix this.
It will be a major. Is that acceptable for you as solution? Or do you need a patch here for the current major version?

**Comment by dereuromark** [comment]
When trying to reproduce this on curernt master we found out that this is already fixed in the latest release of Category/ProductCategory.

**Comment by AndromedaXP** [comment]
The question is if the changes Lucas did in our used branch "dev-beta/category-locales" are in the latest release?

**Comment by dereuromark** [comment]
No, at this point they are not in the latest release yet.
We will get back to you regarding this.
