### ISSUE TITLE
Fix (default) currency in the price form field

### ISSUE THREAD

**Issue by mruoss** [spryker/support#91]
This is a

* [ ] bug

I had a look at the new product-management bundle today and found that the currency in the price form field (Price & Tax tab when creating a product) is fixed to EUR (default value of the MoneyType class of symfony).

Please define a currency option when adding that form field:

https://github.com/spryker/ProductManagement/blob/d7d2e4ec5a5f74bbd8713e4bc90c941ff41a17cf/src/Spryker/Zed/ProductManagement/Communication/Form/Product/PriceForm.php#L86
```php
        $builder->add(self::FIELD_PRICE, 'money', [
            'label' => 'Price',
            'required' => true,
            # Add currency form store:
            'currency' => Store::getInstance()->getCurrencyIsoCode(), 
        ]);
```

Thanks,
Michael

**Comment by aurisl** [comment]
Hi,

Thanks for improvement suggestion. That indeed uses EUR by default, but this is not the only place. I would probably try replace it globally and have it everywhere with possibility configure it.

**Comment by mruoss** [comment]
Hi,

I'm not sure I understood correctly. `Store::getInstance()->getCurrencyIsoCode()` is a configurable value.
Anyway, this being a feature seems odd to me. When I configure my store to USD, the administration surface shows the wrong currency. As a store manager I would be irritated as I have to enter prices in  EUR although my shop is configured to USD.

**Comment by aurisl** [comment]
Hi,

The need of `'currency' => Store::getInstance()->getCurrencyIsoCode(), ` could be encapsulated by framework based on config value, so you would not need explicitly set it.

**Comment by dereuromark** [comment]
This has been patched with https://github.com/spryker/ProductManagement/releases/tag/0.3.3 and https://github.com/spryker/Shipment/releases/tag/4.0.2 . Thank you for reporting it.
