### ISSUE TITLE
Better interface for discount calculator

### ISSUE THREAD

**Issue by mruoss** [spryker/support#92]
This is an

* [ ] enhancement

In our project we would like to enhance the Discount bundle and add custom calculator plugins such as "X for Y" (buy Y, pay X). This requires us to add custom fields to the discount calculator form and db entity.

The interface for the discount calculation (`Spryker\Zed\Discount\Dependency\Plugin\DiscountCalculatorPluginInterface::calculate()`) however takes `$percentage` as a second argument. It would be much more convenient for us to enhance the core functionality if the function took a `DiscountCalculatorTransfer` as second argument. The caller would of course have to prepare the transfer object and fill it with the data from the db but to me that seems a better interface.

The desired interface would then be:

```php
interface DiscountCalculatorPluginInterface 
{
    /**
     * @api
     *
     * @param \Generated\Shared\Transfer\DiscountableItemTransfer[] $discountableItems
     * @param \Generated\Shared\Transfer\DiscountCalculatorTransfer $discountCalculatorTransfer
     *
     * @return int
     */
    public function calculate(array $discountableItems, $discountCalculatorTransfer);

    [...]
}
```

Is such a change thinkable? I would be happy to contribute.

Thanks, 
Michael

**Comment by mruoss** [comment]
To make clear what I'm talking about, these would be the changes against the current master that don't break the API:

[new-discount-calculator-interface.patch](https://github.com/spryker/support/files/651800/new-discount-calculator-interface.patch.txt)

**Comment by aurisl** [comment]
Hi,

Thank you for the patch. Idea sounds good, I agree that more context could be passed to calculator. Would make calculation more flexible.  But we can't make changes in a way you suggesting as it will break BC.  With next major release we could include it.

**Comment by mruoss** [comment]
Hi,
The patch should not break BC as it does not change but only enhance the exposed interface.

**Comment by aurisl** [comment]
By our definitions it does.
For plugin would use interface segregation, otherwise it would cause problems for clients which implement it in their custom plugins.

**Comment by mruoss** [comment]
Oh, that even holds for deprecated functions? Alright, I see... 
Now... for our project, we kind of need that information there. I see two ways to achieve it:

* Create our own repository with the changed API and include that in composer.json
* Overwrite all that logic in the project namespace

Can you help me with this decision? Is there another option I'm not seeing? 

Thanks a lot

**Comment by aurisl** [comment]
I will update your patch to work with both versions without bc break and we will make release. 

Thank you.

**Comment by mruoss** [comment]
Wow okay, nice, thanks. Looking forward to see a correct solution to this.

**Comment by aurisl** [comment]
Hi, we have released suggested changes. https://github.com/spryker/Discount/releases/tag/3.4.0

Thank you for the patch ;)
