### ISSUE TITLE
Domain of Spryker demoshop is hardcoded in the core bundle

### ISSUE THREAD

**Issue by mruoss** [spryker/support#93]
This is a

* [ ] bug

in ProductManagement bundle version 0.1.1.

### What you did

I defined a product attribute of input type "select" with predefined values. Later, I try to assign the attribute to a product.

### Actual Behavior

I cannot fill the attribute. The ajax request to load the possible attribute values is sent to the domain of the Spryker demoshop. The URL including the demoshop's domain is hardcoded in `/vendor/spryker/product-management/assets/Zed/js/modules/main.js` Lines 149, 171, 240.

### Expected Behavior

The request is sent to the domain I configured my store to.

Thanks,
Michael

**Comment by abelspry** [comment]
Hi @mruoss,
thanks for pointing this out.

I'm gonna check and report back to you.
Thanks.

**Comment by dereuromark** [comment]
This is resolved with https://github.com/spryker/ProductManagement/releases/tag/0.1.2.
