### ISSUE TITLE
Application bundle uses deprecated twig feature

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#95]
This is a

* [x] bug
* [ ] enhancement

If possible please provide the exact versions of the bundles involved.
twig/twig 1.30
spryker/application 2.6.3

### What you did
upgrade all bundles

### Actual Behavior
getting Zed Exception
```
ErrorException - The possibility to register the same extension twice ("DateFormatterTwigExtension") is deprecated since version 1.23 and will be removed in Twig 2.0. Use proper PHP inheritance instead.
/data/pim/development/current/vendor/spryker/application/src/Spryker/Zed/Application/Communication/Plugin/ServiceProvider/DateFormatterServiceProvider.php(39)
```

### Expected Behavior
no deprecation errors when updating bundles

**Comment by dereuromark** [comment]
We are in the middle of upgrading alll dependencies.
There are also a few Symfony deprecation warnings that can not that easily be resolved at this point.

For the time being please use
```php
// In your config_default.php
$config[ErrorHandlerConstants::ERROR_LEVEL] = E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED;
```

**Comment by AndromedaXP** [comment]
Thanks. I found out the new Constant
``` $config[ErrorHandlerConstants::ERROR_LEVEL_LOG_ONLY] = E_DEPRECATED | E_USER_DEPRECATED; ```

**Comment by dereuromark** [comment]
We would at this point not recommend the logging here, as it will quickly fill up the logs.
As long as we do not provide a trigger free code, it is advised to use the mentioned level directly.

Happy holidays!

**Comment by AndromedaXP** [comment]
Thanks. All u guys too.
