### ISSUE TITLE
propel generated wrong model files

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#96]
This is a

* [x] bug
* [ ] enhancement

If possible please provide the exact versions of the bundles involved.
spryker/propel 2.3.6
propel/propel 2.0.0-alpha6
spryker/acl 2.0.2

### What you did
running ``` vendor/bin/console setup:deploy:prepare ```

### Actual Behavior
There is a syntax error in many generated base model classes e.g. in class SpyAclRule:1020
            ``` $pk = $con'spy_acl_rule_pk_seq'->lastInsertId(); ```
This error is gone when removing line 43 in spy_acl.schema.xml
```         <id-method-parameter value="spy_acl_group_pk_seq"/> ``` and running setup:deploy:prepare

### Expected Behavior
propel generated model files without syntax errors on lines e.g.
``` $pk = $con->lastInsertId(); ```

### Additional
Additional Tests with spryker/propel 2.3.2 did not show any errors
spryker/propel 2.3.3 has already the same errors

**Comment by dereuromark** [comment]
Looks like https://github.com/spryker/Propel/releases/tag/2.3.3 and alpha6 of Propel introduces this.
We will look into whether this can be patched on their side, or if we have to patch this. We will get back to you.

**Comment by ThomasKuehnel** [comment]
Unfortunately I'm not able to reproduce the issue with the most recent version of the _Propel_ bundle (2.3.6). I will do further testing with older versions of that bundle. 
Just to clarify: Did you extend or modify the _Acl_ bundle in your project in any way? It would be nice to know any changes you might have applied in order to track down the problem.

**Comment by AndromedaXP** [comment]
We didn't extend ACL but this problem exists in ALL generated files... maybe a caching problem?

**Comment by ThomasKuehnel** [comment]
I was able to reproduce this issue using MySql. I will get back to you as soon as I have tracked the issue down.

**Comment by AndromedaXP** [comment]
Thanks a lot.

**Comment by ThomasKuehnel** [comment]
I was able to track the issue down to a change that was introduced with Propel 2.0.0 alpha-6. We updated to this version with the release of _spryker/propel_ 2.2.3. I filed an issue at Propel: https://github.com/propelorm/Propel2/issues/1324
Unfortunately there's no easy workaround to this so we have to wait until Propel addresses the issue. Sorry for the inconvenience.

**Comment by AndromedaXP** [comment]
Thanks for looking into it. So we have to stay with spryker/propel2.2.2 for the moment.
Why were u not confronted with the problem yet? Is it because we use MySQL?

**Comment by ThomasKuehnel** [comment]
Unfortunately yes, it's because you're using MySql. Our continuous integration environment is currently not able to run all tests on all supported database servers (and versions) and it's running tests on PostgreSql only. We're working hard to overcome this issue as soon as possible.

**Comment by AndromedaXP** [comment]
ok, thats a pitty. But thank u so far.

**Comment by ThomasKuehnel** [comment]
The guys over at Propel were able to fix the bug quickly and they already provided a new release containing that fix. We will prepare a new version of the _Propel_ bundle as soon as possible. Thank you for your patience.

**Comment by ThomasKuehnel** [comment]
I'm happy to announce a new relese for the _Propel_ bundle: https://github.com/spryker/Propel/releases/tag/2.3.7

**Comment by AndromedaXP** [comment]
Awesome. Thx.
