### ISSUE TITLE
wrong links in category tree

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#97]
This is a

* [x] bug
* [ ] enhancement

If possible please provide the exact versions of the bundles involved.
category 2.2.3

### What you did
calling /category in PIM

### Actual Behavior
the root tree is shown with new action list in root node ```category/create ``` but in category tree (node.twig) still the removed functions from product-category bundle are used ```/product-category/add, /product-category/edit, ...``` 

### Expected Behavior
category tree should also use the new controller in category bundle

**Comment by ThomasKuehnel** [comment]
Happy New Year!

`node.twig` only gets referenced from `Spryker\Zed\Category\Communication\Controller\IndexController` which has beed deprecated (please see https://github.com/spryker/Category/blob/master/src/Spryker/Zed/Category/Communication/Controller/IndexController.php#L16). Please make sure you access categories in Zed through `/category/root`. 
Unfortunately I'm not able to reproduce the issue from your discription. Could you please explain in more detail how you managed to access the category tree that showed the falsy behaviour (did you manually enter the URL)?

Thanks.

**Comment by AndromedaXP** [comment]
Thanks, u2 guys.

Our navigation menu on the left links the point /category . How can we configure these?

**Comment by ThomasKuehnel** [comment]
Navigation should already be configured correctly (please see https://github.com/spryker/Category/blob/master/src/Spryker/Zed/Category/Communication/navigation.xml#L7). You might need to refresh the navigation cache. This can be done from the command line using the console command:
`vendor/bin/console application:build-navigation-cache`
Please let me know if this doesn't solve the issue for you.

**Comment by AndromedaXP** [comment]
Great. That helped!
