### ISSUE TITLE
transfer classes returning wrong type

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#98]
This is a

* [x] bug
* [ ] enhancement

If possible please provide the exact versions of the bundles involved.
spryker/transfer                            2.3.0

### What you did
Using generated Transfer Classes

### Actual Behavior
when defining a property as bool or int the return value of getter function can also be string or anything which was set.

### Expected Behavior
The return value should be of type defined in xxx.transfer.xml

**Comment by dereuromark** [comment]
You are right about this.
But as of right now (PHP5.6/PHP7.0) PHP itself does not strictly check this, and if we introduce an assert of it now, it would be BC breaking. We can revisit this for the future when switching to PHP7.1 only and introducing stricter typehinting.

It could, however, make sense to cast internally.
Until we internally decide to go into that direction, you can already manually cast before setting - if you use the separate setter functions.

Classifying as feature request as the input currently is expected to be of the appropriate type.

**Comment by AndromedaXP** [comment]
Ok, good to know!

**Comment by dereuromark** [comment]
This can be re-evaluated with PHP7.1+ then and stricter typehinting in the language itself.
Also please see `console transfer:validate` as a tool to auto-check some of the types, e.g. via CI tool.

**Comment by AndromedaXP** [comment]
thanks for that hint!
