### ISSUE TITLE
category form error not shown

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#99]
This is a

* [x] bug
* [ ] enhancement

If possible please provide the exact versions of the bundles involved.
spryker/category 2.2.3

### What you did
Editing a category

### Actual Behavior
When saving a category with an error in the CategoryLocalizedAttributeType subform, it is not displayed if this locale tab is collapsed. Getting console error:
```An invalid form control with name='category[localized_attributes][en_GB][name]' is not focusable.``` 

### Expected Behavior
localized tab should show error or expand

**Comment by ThomasKuehnel** [comment]
Hi @AndromedaXP,
that's a good point. We're trying to address it as soon as possible.

**Comment by dereuromark** [comment]
This is resolved with https://github.com/spryker/Category/releases/tag/2.3.2 and https://github.com/spryker/Gui/releases/tag/2.4.0
Thank you for reporting this.
